// Generated by: python3 tools/gen_small.py gen-accessors --batch 0
// Do not edit by hand; regenerate instead.
//
// This immutable TU is emitted only from the closed, byte-validated accessor
// batch. Every row remains marked gen-shim: the synthetic recipe proves bytes
// and does not claim a recovered retail identity.

extern volatile float g_01075954;
struct AccessWord { unsigned value; };

struct Gen_000c9040 { bool m(); };
bool Gen_000c9040::m() { int value = *(int *)((char *)this + 56); return value != 0; }
struct Gen_0026e740 { bool m(); };
bool Gen_0026e740::m() { int value = *(int *)((char *)this + 88); return value != 0; }
struct Gen_002b9e40 { bool m(); };
bool Gen_002b9e40::m() { int value = *(int *)((char *)this + 116); return value != 0; }
struct Gen_00180380 { bool m(); };
bool Gen_00180380::m() { int value = *(int *)((char *)this + 40); return value == 2; }
struct Gen_00235140 { bool m(); };
bool Gen_00235140::m() { int value = *(int *)((char *)this + 52); return value == 0; }
struct Gen_0009ed10 { bool m(); };
bool Gen_0009ed10::m() { unsigned *value = *(unsigned **)((char *)this + 20); return *(unsigned *)value != (unsigned)value; }
struct Gen_000c9ca0 { unsigned char m(int a); };
unsigned char Gen_000c9ca0::m(int a) { return *((unsigned char *)((char *)a + (int)this + 671)); }
struct Gen_0018f0b0 { char *m(); };
char *Gen_0018f0b0::m() { if (*((char *)this + 50)) return (char *)this + 60; return 0; }
struct Gen_001de210 { float m(int a); };
float Gen_001de210::m(int a) { return ((float *)this)[a + 0x10]; }
struct Gen_0020e860 { float m(); };
float Gen_0020e860::m() { return *(float *)((char *)*(int **)((char *)this - 12) + 60); }
struct Gen_0020fac0 { AccessWord m(); };
AccessWord Gen_0020fac0::m() { return *(AccessWord *)((char *)this + 192); }
struct Gen_00233f20 { int m(); };
int Gen_00233f20::m() { return *(int *)((char *)*(int **)((char *)this - 224) + 360); }
struct Gen_002c60c0 { int m(); };
int Gen_002c60c0::m() { return *(int *)((char *)*(int **)((char *)this - 828) + 128); }
struct Gen_0073a6b0 { float m(); };
float Gen_0073a6b0::m() { float value = *(float *)((char *)this + 1220); return value * g_01075954; }
struct Gen_007fbbb0 { int m(int a, int b); };
int Gen_007fbbb0::m(int a, int b) { return *(int *)((char *)a + 640); }
struct Gen_00928ee0 { int m(int a); };
int Gen_00928ee0::m(int a) { return ((int *)*(int **)((char *)this + 8))[a]; }
struct Gen_005241e0 { unsigned short m(int a, int b); };
unsigned short Gen_005241e0::m(int a, int b) { return (unsigned short)a; }
struct Gen_0056b9e0 { unsigned short m(int a, int b); };
unsigned short Gen_0056b9e0::m(int a, int b) { return (unsigned short)a; }
struct Gen_0044f350 { void m(); };
void Gen_0044f350::m() { *(unsigned *)((char *)this + 4) |= 16777216; }
