// cl: /DNDEBUG /DWIN32 /D_WINDOWS /MD /EHsc /D_STLP_USE_STATIC_LIB
// stlport
// Generated by: python3 tools/gen_small.py family-emit --only all
// Do not edit by hand; regenerate instead.
//
// Each row this file carries is a retail body that IS this instantiation:
// the game links STLport 4.5.3, so a container member's code is the vendor
// template over a payload of that shape, and the payload's name never
// reaches the bytes. The synthetic payloads below are anonymous by design --
// they reproduce a layout and a lifecycle, never a class identity -- and
// every call target is read out of the retail bytes and pinned in
// targets/game/reverse/symbols.csv, so the bytes prove the callee.

#include <hash_map>

// 0x00431210 hash_uint_ptr
typedef _STL::pair<const unsigned int, void * > TgPair_hash_uint_ptr_00431210;
template class _STL::hash_map<unsigned int, void *, _STL::hash<unsigned int >, _STL::equal_to<unsigned int >, _STL::allocator<TgPair_hash_uint_ptr_00431210 > >;
