// Generated by: python3 tools/gen_small.py gen-shims --batch 1 --limit 200
// Do not edit by hand; regenerate instead.
//
// Each Gen_<rva>::m() reproduces the anonymous retail body at that RVA: the
// instruction skeleton is one tools/gen_small.py proved byte-exact, and every
// operand comes from the retail bytes. These are shims, not identities — the
// ledger rows are marked gen-shim so a later real name can replace them.

struct T_000382c1 { void m(); };

struct Gen_00171900 { bool m(); };
bool Gen_00171900::m() { return true; }
struct Gen_00171980 { bool m(); };
bool Gen_00171980::m() { return true; }
struct Gen_00171da0 { unsigned m(); };
unsigned Gen_00171da0::m() { return 0x01098594u; }
struct Gen_00172140 { unsigned m(); };
unsigned Gen_00172140::m() { return 0x01098604u; }
struct Gen_00173670 { unsigned m(); };
unsigned Gen_00173670::m() { return 0x01099000u; }
struct Gen_00174500 { unsigned m(); };
unsigned Gen_00174500::m() { return 0x01099228u; }
struct Gen_00178120 { char m(); };
char Gen_00178120::m() { return *((char *)this + 116); }
struct Gen_001795e0 { unsigned m(); };
unsigned Gen_001795e0::m() { return 0x01099C60u; }
struct Gen_0017f5f0 { char m(); };
char Gen_0017f5f0::m() { return *((char *)this + 117); }
struct Gen_0017f670 { unsigned m(); };
unsigned Gen_0017f670::m() { return 0x0109A598u; }
struct Gen_0017f850 { unsigned m(); };
unsigned Gen_0017f850::m() { return 0x0109A718u; }
struct Gen_0017f9f0 { unsigned m(); };
unsigned Gen_0017f9f0::m() { return 0x0109A808u; }
struct Gen_0017faf0 { unsigned m(); };
unsigned Gen_0017faf0::m() { return 0x0109A880u; }
struct Gen_0017fb70 { unsigned m(); };
unsigned Gen_0017fb70::m() { return 0x0109A900u; }
struct Gen_0017fbd0 { unsigned m(); };
unsigned Gen_0017fbd0::m() { return 0x0109A968u; }
struct Gen_0017fc50 { unsigned m(); };
unsigned Gen_0017fc50::m() { return 0x0109A9E0u; }
struct Gen_001804a0 { unsigned m(); };
unsigned Gen_001804a0::m() { return 0x0109ADE0u; }
struct Gen_00180500 { unsigned m(); };
unsigned Gen_00180500::m() { return 0x0109AE58u; }
struct Gen_00183da0 { bool m(); };
bool Gen_00183da0::m() { return true; }
struct Gen_0018c2f0 { unsigned m(); };
unsigned Gen_0018c2f0::m() { return 0x0109B874u; }
struct Gen_0018ca50 { int m(); };
int Gen_0018ca50::m() { return 0; }
struct Gen_0018d6d0 { int m(); };
int Gen_0018d6d0::m() { return 0; }
struct Gen_0018d6e0 { unsigned m(); };
unsigned Gen_0018d6e0::m() { return 0x0109BC08u; }
struct Gen_00191da0 { void *m(int a, int b); };
void *Gen_00191da0::m(int a, int b) { *(int *)this = b; return this; }
struct Gen_001922a0 { void *m(void *o); };
void *Gen_001922a0::m(void *o) { *(int *)this = *(int *)o; return this; }
struct Gen_001922c0 { void *m(void *o); };
void *Gen_001922c0::m(void *o) { *(int *)this = *(int *)o; return this; }
struct Gen_00192470 { int m(int a); };
int Gen_00192470::m(int a) { return a; }
struct Gen_001924a0 { int m(int a); };
int Gen_001924a0::m(int a) { return a; }
struct Gen_001924d0 { int m(int a); };
int Gen_001924d0::m(int a) { return a; }
struct Gen_00192f20 { int m(int a); };
int Gen_00192f20::m(int a) { return a; }
struct Gen_00193110 { void *m(int a, int b); };
void *Gen_00193110::m(int a, int b) { *(int *)this = b; return this; }
struct Gen_001932f0 { void *m(int a, int b); };
void *Gen_001932f0::m(int a, int b) { *(int *)this = b; return this; }
struct Gen_00193410 { void *m(int a, int b); };
void *Gen_00193410::m(int a, int b) { *(int *)this = b; return this; }
struct Gen_001a2bd0 { void m(); };
void Gen_001a2bd0::m() { }
struct Gen_001b0c50 { void m(); };
void Gen_001b0c50::m() { }
struct Gen_001b0c60 { void m(); };
void Gen_001b0c60::m() { }
struct Gen_001b0c70 { void m(); };
void Gen_001b0c70::m() { }
struct Gen_001b0d10 { void m(); };
void Gen_001b0d10::m() { }
struct Gen_001b2000 { void m(int a); };
void Gen_001b2000::m(int a) { *(int *)((char *)this + 24) = a; }
struct Gen_001b2030 { bool m(int a); };
bool Gen_001b2030::m(int a) { return false; }
struct Gen_001b2060 { void m(int a); };
void Gen_001b2060::m(int a) { *(int *)((char *)this + 12) = a; }
struct Gen_001b2370 { unsigned m(); };
unsigned Gen_001b2370::m() { return 0x0109C9A4u; }
struct Gen_001b2ad0 { int m(); };
int Gen_001b2ad0::m() { return 0; }
struct Gen_001b3af0 { void m(); };
void Gen_001b3af0::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001b3e30 { void m(int a); };
void Gen_001b3e30::m(int a) { *(int *)((char *)this - 8) = a; }
struct Gen_001b3e50 { int m(); };
int Gen_001b3e50::m() { return *(int *)((char *)this - 8); }
struct Gen_001b4680 { void m(); };
void Gen_001b4680::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001b4690 { void m(); };
void Gen_001b4690::m() { }
struct Gen_001bdc10 { void m(); };
void Gen_001bdc10::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001bdc30 { void m(); };
void Gen_001bdc30::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001bdc50 { void m(); };
void Gen_001bdc50::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001bdc70 { void m(); };
void Gen_001bdc70::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001bdc90 { void m(); };
void Gen_001bdc90::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001bdcb0 { void m(); };
void Gen_001bdcb0::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001be760 { void m(int a); };
void Gen_001be760::m(int a) { }
struct Gen_001c0d00 { void m(); };
void Gen_001c0d00::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001c55c0 { unsigned m(); };
unsigned Gen_001c55c0::m() { return 0x0109EBF0u; }
struct Gen_001d3e70 { void *m(); };
void *Gen_001d3e70::m() { return this; }
struct Gen_001d3f30 { int m(); };
int Gen_001d3f30::m() { return *(int *)((char *)this + 840); }
struct Gen_001d3f80 { void m(int a); };
void Gen_001d3f80::m(int a) { *(int *)((char *)this - 16) = a; }
struct Gen_001d3fa0 { int m(); };
int Gen_001d3fa0::m() { return *(int *)((char *)this - 16); }
struct Gen_001d5e10 { void m(); };
void Gen_001d5e10::m() { *(unsigned *)this = 0x0109F0C4u; }
struct Gen_001d6440 { void m(); };
void Gen_001d6440::m() { *(unsigned *)this = 0x0109F0C4u; }
struct Gen_001d66e0 { void m(); };
void Gen_001d66e0::m() { *(unsigned *)this = 0x0109F0C4u; }
struct Gen_001d6950 { void *m(int a, int b); };
void *Gen_001d6950::m(int a, int b) { *(int *)this = b; return this; }
struct Gen_001d6a60 { int m(int a); };
int Gen_001d6a60::m(int a) { return a; }
struct Gen_001dd420 { void m(); };
void Gen_001dd420::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_001dd580 { void m(); };
void Gen_001dd580::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_001ddc30 { void m(); };
void Gen_001ddc30::m() { *(unsigned *)this = 0x0109FB88u; }
struct Gen_001e1760 { bool m(); };
bool Gen_001e1760::m() { return false; }
struct Gen_001e1790 { char m(); };
char Gen_001e1790::m() { return *((char *)this + 112); }
struct Gen_001e3b20 { void *m(int a, int b); };
void *Gen_001e3b20::m(int a, int b) { *(int *)this = b; return this; }
struct Gen_001eaf40 { int m(); };
int Gen_001eaf40::m() { return *(int *)((char *)this + 28); }
struct Gen_001ecff0 { unsigned m(); };
unsigned Gen_001ecff0::m() { return 0x01090C5Cu; }
struct Gen_001ed150 { void m(); };
void Gen_001ed150::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001ed550 { void m(); };
void Gen_001ed550::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_001ed890 { void m(); };
void Gen_001ed890::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001ef410 { void m(); };
void Gen_001ef410::m() { }
struct Gen_001efe80 { void m(); };
void Gen_001efe80::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001f03e0 { bool m(); };
bool Gen_001f03e0::m() { return false; }
struct Gen_001f35e0 { char *m(); };
char *Gen_001f35e0::m() { char *p = (char *)this - 12; return p ? (char *)this + 4 : 0; }
struct Gen_001f5ab0 { char *m(); };
char *Gen_001f5ab0::m() { char *p = (char *)this - 12; return p ? (char *)this + 20 : 0; }
struct Gen_001f6fa0 { char *m(); };
char *Gen_001f6fa0::m() { char *p = (char *)this - 12; return p ? (char *)this + 68 : 0; }
struct Gen_001f7060 { void m(); };
void Gen_001f7060::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_001f7b00 { void m(); };
void Gen_001f7b00::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001f8070 { void m(); };
void Gen_001f8070::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001f8370 { bool m(); };
bool Gen_001f8370::m() { return false; }
struct Gen_001f8c40 { char *m(); };
char *Gen_001f8c40::m() { char *p = (char *)this - 12; return p ? (char *)this + 20 : 0; }
struct Gen_001f8f80 { int m(int a); };
int Gen_001f8f80::m(int a) { return a; }
struct Gen_001fae20 { void m(); };
void Gen_001fae20::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_001fb1f0 { char *m(); };
char *Gen_001fb1f0::m() { char *p = (char *)this - 12; return p ? (char *)this + 20 : 0; }
struct Gen_001fbeb0 { void m(); };
void Gen_001fbeb0::m() { }
struct Gen_001fc2e0 { void m(); };
void Gen_001fc2e0::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_001fe480 { char *m(); };
char *Gen_001fe480::m() { char *p = (char *)this - 12; return p ? (char *)this + 20 : 0; }
struct Gen_001fe4e0 { void m(char a); };
void Gen_001fe4e0::m(char a) { *((char *)this + 22) = a; }
struct Gen_001fe4f0 { char m(); };
char Gen_001fe4f0::m() { return *((char *)this + 22); }
struct Gen_001ffbf0 { bool m(); };
bool Gen_001ffbf0::m() { return true; }
struct Gen_002002b0 { unsigned m(); };
unsigned Gen_002002b0::m() { return 0x01090CDCu; }
struct Gen_00200410 { void m(); };
void Gen_00200410::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_00201170 { void *m(int a); };
void *Gen_00201170::m(int a) { int *p = (int *)this; p[0] = 0; p[1] = 0; p[2] = 0; return this; }
struct Gen_002011d0 { void *m(int a); };
void *Gen_002011d0::m(int a) { int *p = (int *)this; p[0] = 0; p[1] = 0; p[2] = 0; return this; }
struct Gen_00201f10 { void m(); };
void Gen_00201f10::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_00202ad0 { char *m(); };
char *Gen_00202ad0::m() { char *p = (char *)this - 12; return p ? (char *)this + 20 : 0; }
struct Gen_00202de0 { void m(); };
void Gen_00202de0::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_00204390 { void m(); };
void Gen_00204390::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_002050b0 { unsigned m(); };
unsigned Gen_002050b0::m() { return 0x01090908u; }
struct Gen_002050c0 { char *m(); };
char *Gen_002050c0::m() { char *p = (char *)this - 12; return p ? (char *)this + 4 : 0; }
struct Gen_00205810 { char *m(); };
char *Gen_00205810::m() { char *p = (char *)this - 12; return p ? (char *)this + 20 : 0; }
struct Gen_002060a0 { void m(); };
void Gen_002060a0::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_002063a0 { char *m(); };
char *Gen_002063a0::m() { char *p = (char *)this - 12; return p ? (char *)this + 20 : 0; }
struct Gen_002072a0 { int m(); };
int Gen_002072a0::m() { return *(int *)((char *)this + 32); }
struct Gen_0020b010 { unsigned m(); };
unsigned Gen_0020b010::m() { return 0x01090BE4u; }
struct Gen_0020d170 { unsigned m(); };
unsigned Gen_0020d170::m() { return 0x01090B8Cu; }
struct Gen_0020d920 { void m(); };
void Gen_0020d920::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_0020db60 { int m(); };
int Gen_0020db60::m() { return 0; }
struct Gen_0020dbb0 { bool m(); };
bool Gen_0020dbb0::m() { return false; }
struct Gen_0020e500 { char *m(); };
char *Gen_0020e500::m() { char *p = (char *)this - 12; return p ? (char *)this + 4 : 0; }
struct Gen_0020e520 { bool m(); };
bool Gen_0020e520::m() { return true; }
struct Gen_0020fa90 { int m(); };
int Gen_0020fa90::m() { return *(int *)((char *)this + 144); }
struct Gen_00212d10 { void m(); };
void Gen_00212d10::m() { }
struct Gen_00216210 { bool m(); };
bool Gen_00216210::m() { return false; }
struct Gen_002162c0 { char *m(); };
char *Gen_002162c0::m() { char *p = (char *)this - 12; return p ? (char *)this + 4 : 0; }
struct Gen_00216930 { void m(); };
void Gen_00216930::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_00216d80 { void m(); };
void Gen_00216d80::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_00217430 { unsigned m(); };
unsigned Gen_00217430::m() { return 0x0108FBB8u; }
struct Gen_002176e0 { bool m(); };
bool Gen_002176e0::m() { return false; }
struct Gen_002176f0 { bool m(); };
bool Gen_002176f0::m() { return false; }
struct Gen_00217b10 { unsigned m(); };
unsigned Gen_00217b10::m() { return 0x0108FC4Cu; }
struct Gen_00217d50 { unsigned m(); };
unsigned Gen_00217d50::m() { return 0x0108FC34u; }
struct Gen_00218020 { void m(); };
void Gen_00218020::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_00219340 { char *m(); };
char *Gen_00219340::m() { char *p = (char *)this - 12; return p ? (char *)this + 24 : 0; }
struct Gen_002193b0 { bool m(); };
bool Gen_002193b0::m() { return false; }
struct Gen_002193c0 { void m(int a, int b); };
void Gen_002193c0::m(int a, int b) { }
struct Gen_002193e0 { bool m(); };
bool Gen_002193e0::m() { return false; }
struct Gen_00219420 { bool m(); };
bool Gen_00219420::m() { return false; }
struct Gen_00219480 { int m(); };
int Gen_00219480::m() { return 0; }
struct Gen_002194d0 { int m(int a); };
int Gen_002194d0::m(int a) { return 0; }
struct Gen_002195b0 { int m(); };
int Gen_002195b0::m() { return 0; }
struct Gen_002195c0 { int m(); };
int Gen_002195c0::m() { return *(int *)((char *)this + 68); }
struct Gen_002195d0 { int m(); };
int Gen_002195d0::m() { return 0; }
struct Gen_002195f0 { short m(); };
short Gen_002195f0::m() { return *(short *)((char *)this + 84); }
struct Gen_00219600 { bool m(); };
bool Gen_00219600::m() { return false; }
struct Gen_00219670 { bool m(); };
bool Gen_00219670::m() { return false; }
struct Gen_00219700 { bool m(); };
bool Gen_00219700::m() { return false; }
struct Gen_0021d9b0 { unsigned m(); };
unsigned Gen_0021d9b0::m() { return 0x01090AC0u; }
struct Gen_00220660 { bool m(); };
bool Gen_00220660::m() { return false; }
struct Gen_00226440 { unsigned m(); };
unsigned Gen_00226440::m() { return 0x01090BA4u; }
struct Gen_0022a050 { int m(); };
int Gen_0022a050::m() { return *(int *)((char *)this + 184); }
struct Gen_0022cdd0 { void m(); };
void Gen_0022cdd0::m() { }
struct Gen_0022ef00 { char *m(); };
char *Gen_0022ef00::m() { char *p = (char *)this - 12; return p ? (char *)this + 40 : 0; }
struct Gen_0022ef30 { bool m(); };
bool Gen_0022ef30::m() { return false; }
struct Gen_002307f0 { int m(); };
int Gen_002307f0::m() { return *(int *)((char *)this + 256); }
struct Gen_002321c0 { bool m(); };
bool Gen_002321c0::m() { return false; }
struct Gen_00249070 { unsigned m(); };
unsigned Gen_00249070::m() { return 0x01090A30u; }
struct Gen_0024e840 { bool m(); };
bool Gen_0024e840::m() { return true; }
struct Gen_0024f4b0 { char *m(); };
char *Gen_0024f4b0::m() { char *p = (char *)this - 12; return p ? (char *)this + 4 : 0; }
struct Gen_0024f5a0 { unsigned m(); };
unsigned Gen_0024f5a0::m() { return 0x0108FD00u; }
struct Gen_0024f690 { void m(); };
void Gen_0024f690::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_0024f7c0 { bool m(); };
bool Gen_0024f7c0::m() { return true; }
struct Gen_0024f800 { void m(); };
void Gen_0024f800::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_0024fe50 { void m(); };
void Gen_0024fe50::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_0024feb0 { unsigned m(); };
unsigned Gen_0024feb0::m() { return 0x0108FD80u; }
struct Gen_002500b0 { unsigned m(); };
unsigned Gen_002500b0::m() { return 0x0108FD34u; }
struct Gen_002504a0 { unsigned m(); };
unsigned Gen_002504a0::m() { return 0x0108FD4Cu; }
struct Gen_002518a0 { void m(); };
void Gen_002518a0::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_002519d0 { void m(); };
void Gen_002519d0::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_00253ec0 { unsigned m(); };
unsigned Gen_00253ec0::m() { return 0x01090888u; }
struct Gen_002546d0 { unsigned m(); };
unsigned Gen_002546d0::m() { return 0x01090868u; }
struct Gen_00255140 { unsigned m(); };
unsigned Gen_00255140::m() { return 0x010B2E70u; }
struct Gen_002556c0 { unsigned m(); };
unsigned Gen_002556c0::m() { return 0x0109089Cu; }
struct Gen_00255830 { void m(); };
void Gen_00255830::m() { *(unsigned *)this = 0x01073744u; }
struct Gen_002558c0 { unsigned m(); };
unsigned Gen_002558c0::m() { return 0x01090828u; }
struct Gen_002567d0 { unsigned m(); };
unsigned Gen_002567d0::m() { return 0x010B3648u; }
struct Gen_002582f0 { unsigned m(); };
unsigned Gen_002582f0::m() { return 0x0108FA90u; }
struct Gen_00259f90 { unsigned m(); };
unsigned Gen_00259f90::m() { return 0x0108FA74u; }
struct Gen_0025a260 { bool m(); };
bool Gen_0025a260::m() { return false; }
struct Gen_0025a280 { bool m(); };
bool Gen_0025a280::m() { return false; }
struct Gen_0025a330 { bool m(); };
bool Gen_0025a330::m() { return false; }
struct Gen_0025a350 { bool m(); };
bool Gen_0025a350::m() { return false; }
struct Gen_0025a380 { int m(); };
int Gen_0025a380::m() { return 0; }
struct Gen_0025d960 { void m(); };
void Gen_0025d960::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_00263f90 { unsigned m(); };
unsigned Gen_00263f90::m() { return 0x0108F884u; }
struct Gen_00264490 { unsigned m(); };
unsigned Gen_00264490::m() { return 0x0108FA3Cu; }
struct Gen_00264aa0 { void m(); };
void Gen_00264aa0::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_002662d0 { unsigned m(); };
unsigned Gen_002662d0::m() { return 0x0108F924u; }
struct Gen_0026b690 { unsigned m(); };
unsigned Gen_0026b690::m() { return 0x0108F994u; }
struct Gen_0026c060 { int m(); };
int Gen_0026c060::m() { return *(int *)((char *)this + 232); }
struct Gen_0026c590 { unsigned m(); };
unsigned Gen_0026c590::m() { return 0x010903D0u; }
struct Gen_0026e000 { unsigned m(); };
unsigned Gen_0026e000::m() { return 0x0108F8D8u; }
struct Gen_0026e920 { void m(); };
void Gen_0026e920::m() { }
struct Gen_0026f940 { int m(); };
int Gen_0026f940::m() { return *(int *)((char *)this + 356); }
struct Gen_0026fb20 { void m(); };
void Gen_0026fb20::m() { *(unsigned *)this = 0x01083B5Cu; }
struct Gen_0026fb30 { void m(); };
void Gen_0026fb30::m() { ((T_000382c1 *)*(void **)((char *)this + 8))->m(); }
struct Gen_00270010 { void *m(void *o); };
void *Gen_00270010::m(void *o) { *(int *)this = *(int *)o; return this; }
struct Gen_0027eec0 { unsigned m(); };
unsigned Gen_0027eec0::m() { return 0x010BA7A4u; }
struct Gen_0027f1f0 { char *m(); };
char *Gen_0027f1f0::m() { char *p = (char *)this - 12; return p ? (char *)this + 24 : 0; }
struct Gen_0027f290 { int m(); };
int Gen_0027f290::m() { return 0; }
struct Gen_0027f2c0 { int m(); };
int Gen_0027f2c0::m() { return 0; }
struct Gen_0027f2e0 { int m(); };
int Gen_0027f2e0::m() { return 0; }
struct Gen_0027f350 { int m(int a); };
int Gen_0027f350::m(int a) { return 0; }
