// Generated by: python3 tools/gen_small.py gen-imports --batch 0 --limit 500
// Do not edit by hand; regenerate instead.
//
// Each ji_<rva> reproduces the retail six-byte import thunk at that RVA. A
// tail call to a __declspec(dllimport) function is exactly `FF 25` plus a DIR32
// reloc on the __imp_ slot, and the gate copies DIR32 sites from the retail
// bytes, so these rows prove the opcode and the length, not the slot: the IAT
// address the retail thunk reads is recorded in each row's notes instead.

__declspec(dllimport) void i_0007b670();
__declspec(dllimport) void i_00336760();
__declspec(dllimport) void i_00339090();
__declspec(dllimport) void i_0081bda2();
__declspec(dllimport) void i_0081bda8();
__declspec(dllimport) void i_0081bdae();
__declspec(dllimport) void i_0081bdb4();
__declspec(dllimport) void i_0081bdba();
__declspec(dllimport) void i_0081bdc0();
__declspec(dllimport) void i_0081bdc6();
__declspec(dllimport) void i_0081bdcc();
__declspec(dllimport) void i_0081bdd2();
__declspec(dllimport) void i_0081bdd8();
__declspec(dllimport) void i_0081bdde();
__declspec(dllimport) void i_0081bde4();
__declspec(dllimport) void i_0081bdea();
__declspec(dllimport) void i_0081bdf0();
__declspec(dllimport) void i_0081bdf6();
__declspec(dllimport) void i_0081bdfc();
__declspec(dllimport) void i_0081be02();
__declspec(dllimport) void i_0081be08();
__declspec(dllimport) void i_0081be0e();
__declspec(dllimport) void i_0081be14();
__declspec(dllimport) void i_0081be1a();
__declspec(dllimport) void i_0081be20();
__declspec(dllimport) void i_0081be26();
__declspec(dllimport) void i_0081be2c();
__declspec(dllimport) void i_0081be32();
__declspec(dllimport) void i_0081be38();
__declspec(dllimport) void i_0081be3e();
__declspec(dllimport) void i_0081be44();
__declspec(dllimport) void i_0081be4a();
__declspec(dllimport) void i_0081be50();
__declspec(dllimport) void i_0081be56();
__declspec(dllimport) void i_0081be5c();
__declspec(dllimport) void i_0081be62();
__declspec(dllimport) void i_0081be68();
__declspec(dllimport) void i_0081be6e();
__declspec(dllimport) void i_0081be74();
__declspec(dllimport) void i_0081be7a();
__declspec(dllimport) void i_0081be80();
__declspec(dllimport) void i_008542e0();
__declspec(dllimport) void i_00879190();
__declspec(dllimport) void i_008793a0();
__declspec(dllimport) void i_00891690();
__declspec(dllimport) void i_00891700();
__declspec(dllimport) void i_00891750();
__declspec(dllimport) void i_008917f0();
__declspec(dllimport) void i_00891a80();
__declspec(dllimport) void i_008926c0();
__declspec(dllimport) void i_00894c50();
__declspec(dllimport) void i_00894d50();
__declspec(dllimport) void i_008976d0();
__declspec(dllimport) void i_008979b0();
__declspec(dllimport) void i_008a05b0();
__declspec(dllimport) void i_008bd020();
__declspec(dllimport) void i_008bd040();
__declspec(dllimport) void i_008bd0c0();
__declspec(dllimport) void i_009db580();
__declspec(dllimport) void i_009f6bc2();
__declspec(dllimport) void i_009f6bc8();
__declspec(dllimport) void i_009f6bce();
__declspec(dllimport) void i_009f6bd4();
__declspec(dllimport) void i_009f6bda();
__declspec(dllimport) void i_009f6be0();
__declspec(dllimport) void i_009f6be6();
__declspec(dllimport) void i_009f6bec();
__declspec(dllimport) void i_009f6bf2();
__declspec(dllimport) void i_009f6bf8();
__declspec(dllimport) void i_009f6bfe();
__declspec(dllimport) void i_009f6c04();
__declspec(dllimport) void i_009f6c0a();
__declspec(dllimport) void i_009f6c10();
__declspec(dllimport) void i_009f6c16();
__declspec(dllimport) void i_009f6c1c();
__declspec(dllimport) void i_009f6c22();
__declspec(dllimport) void i_009f6c34();
__declspec(dllimport) void i_009f6c3a();
__declspec(dllimport) void i_009f6d00();
__declspec(dllimport) void i_009f6dd6();
__declspec(dllimport) void i_009f6de2();
__declspec(dllimport) void i_009f6de8();
__declspec(dllimport) void i_009f6dee();
__declspec(dllimport) void i_009f6dfa();
__declspec(dllimport) void i_009f6eae();
__declspec(dllimport) void i_009f6eb4();
__declspec(dllimport) void i_009f6ec0();
__declspec(dllimport) void i_009f6ec6();
__declspec(dllimport) void i_009f6ed2();
__declspec(dllimport) void i_009f6f52();
__declspec(dllimport) void i_009f6f7c();
__declspec(dllimport) void i_009f6f9a();
__declspec(dllimport) void i_009f6fa0();
__declspec(dllimport) void i_009f6fa6();
__declspec(dllimport) void i_009f6fac();
__declspec(dllimport) void i_009f6fb8();
__declspec(dllimport) void i_009f6fc4();
__declspec(dllimport) void i_009f6fe2();
__declspec(dllimport) void i_009f700c();
__declspec(dllimport) void i_009f7024();
__declspec(dllimport) void i_009f702a();
__declspec(dllimport) void i_009f7030();
__declspec(dllimport) void i_009f709c();
__declspec(dllimport) void i_009f70a2();
__declspec(dllimport) void i_009f70a8();
__declspec(dllimport) void i_009f70ae();
__declspec(dllimport) void i_009f70ba();
__declspec(dllimport) void i_009f70c0();
__declspec(dllimport) void i_009f70cc();
__declspec(dllimport) void i_009f719c();
__declspec(dllimport) void i_009f71ae();
__declspec(dllimport) void i_009f71cc();
__declspec(dllimport) void i_009f71d8();
__declspec(dllimport) void i_009f71ea();
__declspec(dllimport) void i_009f7244();
__declspec(dllimport) void i_009f75b8();
__declspec(dllimport) void i_009f75be();
__declspec(dllimport) void i_009f75c4();
__declspec(dllimport) void i_009f75ca();
__declspec(dllimport) void i_009f75d0();
__declspec(dllimport) void i_009f75d6();
__declspec(dllimport) void i_009f7b8e();
__declspec(dllimport) void i_009f7b94();
__declspec(dllimport) void i_009f7b9a();
__declspec(dllimport) void i_009f7ba0();
__declspec(dllimport) void i_009f7cc6();
__declspec(dllimport) void i_009f7ccc();
__declspec(dllimport) void i_009f7d20();
__declspec(dllimport) void i_009f7d26();
__declspec(dllimport) void i_009f7d7a();
__declspec(dllimport) void i_009f7d80();
__declspec(dllimport) void i_009f7d9e();
__declspec(dllimport) void i_009f7df2();
__declspec(dllimport) void i_009f7e04();
__declspec(dllimport) void i_009f7e0a();
__declspec(dllimport) void i_009f7e10();
__declspec(dllimport) void i_009f7e28();
__declspec(dllimport) void i_009f7e40();
__declspec(dllimport) void i_009f7e4c();
__declspec(dllimport) void i_009f7ed4();
__declspec(dllimport) void i_009f7ee0();
__declspec(dllimport) void i_009f7efe();
__declspec(dllimport) void i_009f7f92();
__declspec(dllimport) void i_009f802e();
__declspec(dllimport) void i_009f8088();
__declspec(dllimport) void i_009f8878();
__declspec(dllimport) void i_009f887e();
__declspec(dllimport) void i_009f8884();
__declspec(dllimport) void i_009f888a();
__declspec(dllimport) void i_009f8890();
__declspec(dllimport) void i_009f8896();
__declspec(dllimport) void i_009f889c();
__declspec(dllimport) void i_009f88a2();
__declspec(dllimport) void i_009f88a8();
__declspec(dllimport) void i_009f88ae();
__declspec(dllimport) void i_009f88b4();
__declspec(dllimport) void i_009f9af0();
__declspec(dllimport) void i_009f9b70();
__declspec(dllimport) void i_009f9b76();
__declspec(dllimport) void i_009f9bd4();
__declspec(dllimport) void i_009f9c76();
__declspec(dllimport) void i_009f9f56();
__declspec(dllimport) void i_009f9f80();
__declspec(dllimport) void i_009f9fcc();
__declspec(dllimport) void i_009fa00b();
__declspec(dllimport) void i_009fa11f();
__declspec(dllimport) void i_009fa24e();
__declspec(dllimport) void i_009fa2be();
__declspec(dllimport) void i_009fa437();
__declspec(dllimport) void i_009fa44e();
__declspec(dllimport) void i_009fa4a3();
__declspec(dllimport) void i_009fa9be();
__declspec(dllimport) void i_009facad();
__declspec(dllimport) void i_009fafba();
__declspec(dllimport) void i_009fb6f4();
__declspec(dllimport) void i_009fb784();
__declspec(dllimport) void i_009fb802();
__declspec(dllimport) void i_009fb89e();
__declspec(dllimport) void i_009fb93b();
__declspec(dllimport) void i_009fb9f7();
__declspec(dllimport) void i_009fbb0c();
__declspec(dllimport) void i_009fcb4e();
__declspec(dllimport) void i_009fcc3a();
__declspec(dllimport) void i_009fcdac();
__declspec(dllimport) void i_009fce70();
__declspec(dllimport) void i_009fcefe();
__declspec(dllimport) void i_009fcfc0();
__declspec(dllimport) void i_009fd211();
__declspec(dllimport) void i_009fd37a();
__declspec(dllimport) void i_009fd9a4();
__declspec(dllimport) void i_00afd504();
__declspec(dllimport) void i_00afd510();
__declspec(dllimport) void i_00afd528();
__declspec(dllimport) void i_00afe3ea();
__declspec(dllimport) void i_00afe3f0();
__declspec(dllimport) void i_00afe3f6();
__declspec(dllimport) void i_00afe426();
__declspec(dllimport) void i_00afe432();
__declspec(dllimport) void i_00b02898();
__declspec(dllimport) void i_00b0289e();
__declspec(dllimport) void i_00b028c4();
__declspec(dllimport) void i_00b028ca();
__declspec(dllimport) void i_00b028d0();
__declspec(dllimport) void i_00b028d6();
__declspec(dllimport) void i_00b028dc();
__declspec(dllimport) void i_00b028e2();
__declspec(dllimport) void i_00b028e8();

void ji_0007b670() { i_0007b670(); }
void ji_00336760() { i_00336760(); }
void ji_00339090() { i_00339090(); }
void ji_0081bda2() { i_0081bda2(); }
void ji_0081bda8() { i_0081bda8(); }
void ji_0081bdae() { i_0081bdae(); }
void ji_0081bdb4() { i_0081bdb4(); }
void ji_0081bdba() { i_0081bdba(); }
void ji_0081bdc0() { i_0081bdc0(); }
void ji_0081bdc6() { i_0081bdc6(); }
void ji_0081bdcc() { i_0081bdcc(); }
void ji_0081bdd2() { i_0081bdd2(); }
void ji_0081bdd8() { i_0081bdd8(); }
void ji_0081bdde() { i_0081bdde(); }
void ji_0081bde4() { i_0081bde4(); }
void ji_0081bdea() { i_0081bdea(); }
void ji_0081bdf0() { i_0081bdf0(); }
void ji_0081bdf6() { i_0081bdf6(); }
void ji_0081bdfc() { i_0081bdfc(); }
void ji_0081be02() { i_0081be02(); }
void ji_0081be08() { i_0081be08(); }
void ji_0081be0e() { i_0081be0e(); }
void ji_0081be14() { i_0081be14(); }
void ji_0081be1a() { i_0081be1a(); }
void ji_0081be20() { i_0081be20(); }
void ji_0081be26() { i_0081be26(); }
void ji_0081be2c() { i_0081be2c(); }
void ji_0081be32() { i_0081be32(); }
void ji_0081be38() { i_0081be38(); }
void ji_0081be3e() { i_0081be3e(); }
void ji_0081be44() { i_0081be44(); }
void ji_0081be4a() { i_0081be4a(); }
void ji_0081be50() { i_0081be50(); }
void ji_0081be56() { i_0081be56(); }
void ji_0081be5c() { i_0081be5c(); }
void ji_0081be62() { i_0081be62(); }
void ji_0081be68() { i_0081be68(); }
void ji_0081be6e() { i_0081be6e(); }
void ji_0081be74() { i_0081be74(); }
void ji_0081be7a() { i_0081be7a(); }
void ji_0081be80() { i_0081be80(); }
void ji_008542e0() { i_008542e0(); }
void ji_00879190() { i_00879190(); }
void ji_008793a0() { i_008793a0(); }
void ji_00891690() { i_00891690(); }
void ji_00891700() { i_00891700(); }
void ji_00891750() { i_00891750(); }
void ji_008917f0() { i_008917f0(); }
void ji_00891a80() { i_00891a80(); }
void ji_008926c0() { i_008926c0(); }
void ji_00894c50() { i_00894c50(); }
void ji_00894d50() { i_00894d50(); }
void ji_008976d0() { i_008976d0(); }
void ji_008979b0() { i_008979b0(); }
void ji_008a05b0() { i_008a05b0(); }
void ji_008bd020() { i_008bd020(); }
void ji_008bd040() { i_008bd040(); }
void ji_008bd0c0() { i_008bd0c0(); }
void ji_009db580() { i_009db580(); }
void ji_009f6bc2() { i_009f6bc2(); }
void ji_009f6bc8() { i_009f6bc8(); }
void ji_009f6bce() { i_009f6bce(); }
void ji_009f6bd4() { i_009f6bd4(); }
void ji_009f6bda() { i_009f6bda(); }
void ji_009f6be0() { i_009f6be0(); }
void ji_009f6be6() { i_009f6be6(); }
void ji_009f6bec() { i_009f6bec(); }
void ji_009f6bf2() { i_009f6bf2(); }
void ji_009f6bf8() { i_009f6bf8(); }
void ji_009f6bfe() { i_009f6bfe(); }
void ji_009f6c04() { i_009f6c04(); }
void ji_009f6c0a() { i_009f6c0a(); }
void ji_009f6c10() { i_009f6c10(); }
void ji_009f6c16() { i_009f6c16(); }
void ji_009f6c1c() { i_009f6c1c(); }
void ji_009f6c22() { i_009f6c22(); }
void ji_009f6c34() { i_009f6c34(); }
void ji_009f6c3a() { i_009f6c3a(); }
void ji_009f6d00() { i_009f6d00(); }
void ji_009f6dd6() { i_009f6dd6(); }
void ji_009f6de2() { i_009f6de2(); }
void ji_009f6de8() { i_009f6de8(); }
void ji_009f6dee() { i_009f6dee(); }
void ji_009f6dfa() { i_009f6dfa(); }
void ji_009f6eae() { i_009f6eae(); }
void ji_009f6eb4() { i_009f6eb4(); }
void ji_009f6ec0() { i_009f6ec0(); }
void ji_009f6ec6() { i_009f6ec6(); }
void ji_009f6ed2() { i_009f6ed2(); }
void ji_009f6f52() { i_009f6f52(); }
void ji_009f6f7c() { i_009f6f7c(); }
void ji_009f6f9a() { i_009f6f9a(); }
void ji_009f6fa0() { i_009f6fa0(); }
void ji_009f6fa6() { i_009f6fa6(); }
void ji_009f6fac() { i_009f6fac(); }
void ji_009f6fb8() { i_009f6fb8(); }
void ji_009f6fc4() { i_009f6fc4(); }
void ji_009f6fe2() { i_009f6fe2(); }
void ji_009f700c() { i_009f700c(); }
void ji_009f7024() { i_009f7024(); }
void ji_009f702a() { i_009f702a(); }
void ji_009f7030() { i_009f7030(); }
void ji_009f709c() { i_009f709c(); }
void ji_009f70a2() { i_009f70a2(); }
void ji_009f70a8() { i_009f70a8(); }
void ji_009f70ae() { i_009f70ae(); }
void ji_009f70ba() { i_009f70ba(); }
void ji_009f70c0() { i_009f70c0(); }
void ji_009f70cc() { i_009f70cc(); }
void ji_009f719c() { i_009f719c(); }
void ji_009f71ae() { i_009f71ae(); }
void ji_009f71cc() { i_009f71cc(); }
void ji_009f71d8() { i_009f71d8(); }
void ji_009f71ea() { i_009f71ea(); }
void ji_009f7244() { i_009f7244(); }
void ji_009f75b8() { i_009f75b8(); }
void ji_009f75be() { i_009f75be(); }
void ji_009f75c4() { i_009f75c4(); }
void ji_009f75ca() { i_009f75ca(); }
void ji_009f75d0() { i_009f75d0(); }
void ji_009f75d6() { i_009f75d6(); }
void ji_009f7b8e() { i_009f7b8e(); }
void ji_009f7b94() { i_009f7b94(); }
void ji_009f7b9a() { i_009f7b9a(); }
void ji_009f7ba0() { i_009f7ba0(); }
void ji_009f7cc6() { i_009f7cc6(); }
void ji_009f7ccc() { i_009f7ccc(); }
void ji_009f7d20() { i_009f7d20(); }
void ji_009f7d26() { i_009f7d26(); }
void ji_009f7d7a() { i_009f7d7a(); }
void ji_009f7d80() { i_009f7d80(); }
void ji_009f7d9e() { i_009f7d9e(); }
void ji_009f7df2() { i_009f7df2(); }
void ji_009f7e04() { i_009f7e04(); }
void ji_009f7e0a() { i_009f7e0a(); }
void ji_009f7e10() { i_009f7e10(); }
void ji_009f7e28() { i_009f7e28(); }
void ji_009f7e40() { i_009f7e40(); }
void ji_009f7e4c() { i_009f7e4c(); }
void ji_009f7ed4() { i_009f7ed4(); }
void ji_009f7ee0() { i_009f7ee0(); }
void ji_009f7efe() { i_009f7efe(); }
void ji_009f7f92() { i_009f7f92(); }
void ji_009f802e() { i_009f802e(); }
void ji_009f8088() { i_009f8088(); }
void ji_009f8878() { i_009f8878(); }
void ji_009f887e() { i_009f887e(); }
void ji_009f8884() { i_009f8884(); }
void ji_009f888a() { i_009f888a(); }
void ji_009f8890() { i_009f8890(); }
void ji_009f8896() { i_009f8896(); }
void ji_009f889c() { i_009f889c(); }
void ji_009f88a2() { i_009f88a2(); }
void ji_009f88a8() { i_009f88a8(); }
void ji_009f88ae() { i_009f88ae(); }
void ji_009f88b4() { i_009f88b4(); }
void ji_009f9af0() { i_009f9af0(); }
void ji_009f9b70() { i_009f9b70(); }
void ji_009f9b76() { i_009f9b76(); }
void ji_009f9bd4() { i_009f9bd4(); }
void ji_009f9c76() { i_009f9c76(); }
void ji_009f9f56() { i_009f9f56(); }
void ji_009f9f80() { i_009f9f80(); }
void ji_009f9fcc() { i_009f9fcc(); }
void ji_009fa00b() { i_009fa00b(); }
void ji_009fa11f() { i_009fa11f(); }
void ji_009fa24e() { i_009fa24e(); }
void ji_009fa2be() { i_009fa2be(); }
void ji_009fa437() { i_009fa437(); }
void ji_009fa44e() { i_009fa44e(); }
void ji_009fa4a3() { i_009fa4a3(); }
void ji_009fa9be() { i_009fa9be(); }
void ji_009facad() { i_009facad(); }
void ji_009fafba() { i_009fafba(); }
void ji_009fb6f4() { i_009fb6f4(); }
void ji_009fb784() { i_009fb784(); }
void ji_009fb802() { i_009fb802(); }
void ji_009fb89e() { i_009fb89e(); }
void ji_009fb93b() { i_009fb93b(); }
void ji_009fb9f7() { i_009fb9f7(); }
void ji_009fbb0c() { i_009fbb0c(); }
void ji_009fcb4e() { i_009fcb4e(); }
void ji_009fcc3a() { i_009fcc3a(); }
void ji_009fcdac() { i_009fcdac(); }
void ji_009fce70() { i_009fce70(); }
void ji_009fcefe() { i_009fcefe(); }
void ji_009fcfc0() { i_009fcfc0(); }
void ji_009fd211() { i_009fd211(); }
void ji_009fd37a() { i_009fd37a(); }
void ji_009fd9a4() { i_009fd9a4(); }
void ji_00afd504() { i_00afd504(); }
void ji_00afd510() { i_00afd510(); }
void ji_00afd528() { i_00afd528(); }
void ji_00afe3ea() { i_00afe3ea(); }
void ji_00afe3f0() { i_00afe3f0(); }
void ji_00afe3f6() { i_00afe3f6(); }
void ji_00afe426() { i_00afe426(); }
void ji_00afe432() { i_00afe432(); }
void ji_00b02898() { i_00b02898(); }
void ji_00b0289e() { i_00b0289e(); }
void ji_00b028c4() { i_00b028c4(); }
void ji_00b028ca() { i_00b028ca(); }
void ji_00b028d0() { i_00b028d0(); }
void ji_00b028d6() { i_00b028d6(); }
void ji_00b028dc() { i_00b028dc(); }
void ji_00b028e2() { i_00b028e2(); }
void ji_00b028e8() { i_00b028e8(); }
