// cl: /EHsc
// stlport
// Generated by: python3 tools/gen_small.py gen-tgrid
// Do not edit by hand; regenerate instead.
//
// Each row this file carries is a retail body that IS this instantiation:
// the game links STLport 4.5.3, so a container member's code is the vendor
// template over a payload of that shape, and the payload's name never
// reaches the bytes. The synthetic payloads below are anonymous by design --
// they reproduce a layout and a lifecycle, never a class identity -- and
// every call target is read out of the retail bytes and pinned in
// targets/game/reverse/symbols.csv, so the bytes prove the callee.

#include <list>
#include <map>
#include <vector>

// 0x003416C0 tree_int_p8cd
struct Gen_t_003416c0_p8cd { int a[2]; Gen_t_003416c0_p8cd(); Gen_t_003416c0_p8cd(const Gen_t_003416c0_p8cd&); ~Gen_t_003416c0_p8cd(); Gen_t_003416c0_p8cd& operator=(const Gen_t_003416c0_p8cd&); };
bool operator==(const Gen_t_003416c0_p8cd&, const Gen_t_003416c0_p8cd&);
bool operator<(const Gen_t_003416c0_p8cd&, const Gen_t_003416c0_p8cd&);
typedef _STL::pair<const int, Gen_t_003416c0_p8cd > TgPair_tree_int_p8cd_003416c0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p8cd_003416c0, _STL::_Select1st<TgPair_tree_int_p8cd_003416c0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p8cd_003416c0 > >;
// 0x00341760 tree_int_p12cd
struct Gen_t_00341760_p12cd { int a[3]; Gen_t_00341760_p12cd(); Gen_t_00341760_p12cd(const Gen_t_00341760_p12cd&); ~Gen_t_00341760_p12cd(); Gen_t_00341760_p12cd& operator=(const Gen_t_00341760_p12cd&); };
bool operator==(const Gen_t_00341760_p12cd&, const Gen_t_00341760_p12cd&);
bool operator<(const Gen_t_00341760_p12cd&, const Gen_t_00341760_p12cd&);
typedef _STL::pair<const int, Gen_t_00341760_p12cd > TgPair_tree_int_p12cd_00341760;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00341760, _STL::_Select1st<TgPair_tree_int_p12cd_00341760 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00341760 > >;
// 0x003417A0 tree_int_p8cd
struct Gen_t_003417a0_p8cd { int a[2]; Gen_t_003417a0_p8cd(); Gen_t_003417a0_p8cd(const Gen_t_003417a0_p8cd&); ~Gen_t_003417a0_p8cd(); Gen_t_003417a0_p8cd& operator=(const Gen_t_003417a0_p8cd&); };
bool operator==(const Gen_t_003417a0_p8cd&, const Gen_t_003417a0_p8cd&);
bool operator<(const Gen_t_003417a0_p8cd&, const Gen_t_003417a0_p8cd&);
typedef _STL::pair<const int, Gen_t_003417a0_p8cd > TgPair_tree_int_p8cd_003417a0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p8cd_003417a0, _STL::_Select1st<TgPair_tree_int_p8cd_003417a0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p8cd_003417a0 > >;
// 0x00341840 tree_int_p12cd
struct Gen_t_00341840_p12cd { int a[3]; Gen_t_00341840_p12cd(); Gen_t_00341840_p12cd(const Gen_t_00341840_p12cd&); ~Gen_t_00341840_p12cd(); Gen_t_00341840_p12cd& operator=(const Gen_t_00341840_p12cd&); };
bool operator==(const Gen_t_00341840_p12cd&, const Gen_t_00341840_p12cd&);
bool operator<(const Gen_t_00341840_p12cd&, const Gen_t_00341840_p12cd&);
typedef _STL::pair<const int, Gen_t_00341840_p12cd > TgPair_tree_int_p12cd_00341840;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00341840, _STL::_Select1st<TgPair_tree_int_p12cd_00341840 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00341840 > >;
// 0x00341880 tree_int_p12cd
struct Gen_t_00341880_p12cd { int a[3]; Gen_t_00341880_p12cd(); Gen_t_00341880_p12cd(const Gen_t_00341880_p12cd&); ~Gen_t_00341880_p12cd(); Gen_t_00341880_p12cd& operator=(const Gen_t_00341880_p12cd&); };
bool operator==(const Gen_t_00341880_p12cd&, const Gen_t_00341880_p12cd&);
bool operator<(const Gen_t_00341880_p12cd&, const Gen_t_00341880_p12cd&);
typedef _STL::pair<const int, Gen_t_00341880_p12cd > TgPair_tree_int_p12cd_00341880;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00341880, _STL::_Select1st<TgPair_tree_int_p12cd_00341880 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00341880 > >;
// 0x003418C0 tree_int_p4pod
struct Gen_t_003418c0_p4pod { int a[1]; };
bool operator==(const Gen_t_003418c0_p4pod&, const Gen_t_003418c0_p4pod&);
bool operator<(const Gen_t_003418c0_p4pod&, const Gen_t_003418c0_p4pod&);
typedef _STL::pair<const int, Gen_t_003418c0_p4pod > TgPair_tree_int_p4pod_003418c0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p4pod_003418c0, _STL::_Select1st<TgPair_tree_int_p4pod_003418c0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p4pod_003418c0 > >;
// 0x003419A0 list_p8cd
struct Gen_t_003419a0_p8cd { int a[2]; Gen_t_003419a0_p8cd(); Gen_t_003419a0_p8cd(const Gen_t_003419a0_p8cd&); ~Gen_t_003419a0_p8cd(); Gen_t_003419a0_p8cd& operator=(const Gen_t_003419a0_p8cd&); };
bool operator==(const Gen_t_003419a0_p8cd&, const Gen_t_003419a0_p8cd&);
bool operator<(const Gen_t_003419a0_p8cd&, const Gen_t_003419a0_p8cd&);
template class _STL::list<Gen_t_003419a0_p8cd >;
// 0x00343BB0 vec_p8cd
struct Gen_t_00343bb0_p8cd { int a[2]; Gen_t_00343bb0_p8cd(); Gen_t_00343bb0_p8cd(const Gen_t_00343bb0_p8cd&); ~Gen_t_00343bb0_p8cd(); Gen_t_00343bb0_p8cd& operator=(const Gen_t_00343bb0_p8cd&); };
bool operator==(const Gen_t_00343bb0_p8cd&, const Gen_t_00343bb0_p8cd&);
bool operator<(const Gen_t_00343bb0_p8cd&, const Gen_t_00343bb0_p8cd&);
template class _STL::vector<Gen_t_00343bb0_p8cd >;
// 0x00343CA0 list_p8cd
struct Gen_t_00343ca0_p8cd { int a[2]; Gen_t_00343ca0_p8cd(); Gen_t_00343ca0_p8cd(const Gen_t_00343ca0_p8cd&); ~Gen_t_00343ca0_p8cd(); Gen_t_00343ca0_p8cd& operator=(const Gen_t_00343ca0_p8cd&); };
bool operator==(const Gen_t_00343ca0_p8cd&, const Gen_t_00343ca0_p8cd&);
bool operator<(const Gen_t_00343ca0_p8cd&, const Gen_t_00343ca0_p8cd&);
template class _STL::list<Gen_t_00343ca0_p8cd >;
// 0x003441D0 vec_p8cd
struct Gen_t_003441d0_p8cd { int a[2]; Gen_t_003441d0_p8cd(); Gen_t_003441d0_p8cd(const Gen_t_003441d0_p8cd&); ~Gen_t_003441d0_p8cd(); Gen_t_003441d0_p8cd& operator=(const Gen_t_003441d0_p8cd&); };
bool operator==(const Gen_t_003441d0_p8cd&, const Gen_t_003441d0_p8cd&);
bool operator<(const Gen_t_003441d0_p8cd&, const Gen_t_003441d0_p8cd&);
template class _STL::vector<Gen_t_003441d0_p8cd >;
// 0x00344240 vec_p16cd
struct Gen_t_00344240_p16cd { int a[4]; Gen_t_00344240_p16cd(); Gen_t_00344240_p16cd(const Gen_t_00344240_p16cd&); ~Gen_t_00344240_p16cd(); Gen_t_00344240_p16cd& operator=(const Gen_t_00344240_p16cd&); };
bool operator==(const Gen_t_00344240_p16cd&, const Gen_t_00344240_p16cd&);
bool operator<(const Gen_t_00344240_p16cd&, const Gen_t_00344240_p16cd&);
template class _STL::vector<Gen_t_00344240_p16cd >;
// 0x00349190 vec_p8cd
struct Gen_t_00349190_p8cd { int a[2]; Gen_t_00349190_p8cd(); Gen_t_00349190_p8cd(const Gen_t_00349190_p8cd&); ~Gen_t_00349190_p8cd(); Gen_t_00349190_p8cd& operator=(const Gen_t_00349190_p8cd&); };
bool operator==(const Gen_t_00349190_p8cd&, const Gen_t_00349190_p8cd&);
bool operator<(const Gen_t_00349190_p8cd&, const Gen_t_00349190_p8cd&);
template class _STL::vector<Gen_t_00349190_p8cd >;
// 0x003491E0 vec_p16cd
struct Gen_t_003491e0_p16cd { int a[4]; Gen_t_003491e0_p16cd(); Gen_t_003491e0_p16cd(const Gen_t_003491e0_p16cd&); ~Gen_t_003491e0_p16cd(); Gen_t_003491e0_p16cd& operator=(const Gen_t_003491e0_p16cd&); };
bool operator==(const Gen_t_003491e0_p16cd&, const Gen_t_003491e0_p16cd&);
bool operator<(const Gen_t_003491e0_p16cd&, const Gen_t_003491e0_p16cd&);
template class _STL::vector<Gen_t_003491e0_p16cd >;
// 0x00351EA0 list_p12cd
struct Gen_t_00351ea0_p12cd { int a[3]; Gen_t_00351ea0_p12cd(); Gen_t_00351ea0_p12cd(const Gen_t_00351ea0_p12cd&); ~Gen_t_00351ea0_p12cd(); Gen_t_00351ea0_p12cd& operator=(const Gen_t_00351ea0_p12cd&); };
bool operator==(const Gen_t_00351ea0_p12cd&, const Gen_t_00351ea0_p12cd&);
bool operator<(const Gen_t_00351ea0_p12cd&, const Gen_t_00351ea0_p12cd&);
template class _STL::list<Gen_t_00351ea0_p12cd >;
// 0x00351ED0 list_p12cd
struct Gen_t_00351ed0_p12cd { int a[3]; Gen_t_00351ed0_p12cd(); Gen_t_00351ed0_p12cd(const Gen_t_00351ed0_p12cd&); ~Gen_t_00351ed0_p12cd(); Gen_t_00351ed0_p12cd& operator=(const Gen_t_00351ed0_p12cd&); };
bool operator==(const Gen_t_00351ed0_p12cd&, const Gen_t_00351ed0_p12cd&);
bool operator<(const Gen_t_00351ed0_p12cd&, const Gen_t_00351ed0_p12cd&);
template class _STL::list<Gen_t_00351ed0_p12cd >;
// 0x00351F00 list_p12cd
struct Gen_t_00351f00_p12cd { int a[3]; Gen_t_00351f00_p12cd(); Gen_t_00351f00_p12cd(const Gen_t_00351f00_p12cd&); ~Gen_t_00351f00_p12cd(); Gen_t_00351f00_p12cd& operator=(const Gen_t_00351f00_p12cd&); };
bool operator==(const Gen_t_00351f00_p12cd&, const Gen_t_00351f00_p12cd&);
bool operator<(const Gen_t_00351f00_p12cd&, const Gen_t_00351f00_p12cd&);
template class _STL::list<Gen_t_00351f00_p12cd >;
// 0x00356ED0 vec_p4pod
struct Gen_t_00356ed0_p4pod { int a[1]; };
bool operator==(const Gen_t_00356ed0_p4pod&, const Gen_t_00356ed0_p4pod&);
bool operator<(const Gen_t_00356ed0_p4pod&, const Gen_t_00356ed0_p4pod&);
template class _STL::vector<Gen_t_00356ed0_p4pod >;
// 0x003620E0 vec_p4cd
struct Gen_t_003620e0_p4cd { int a[1]; Gen_t_003620e0_p4cd(); Gen_t_003620e0_p4cd(const Gen_t_003620e0_p4cd&); ~Gen_t_003620e0_p4cd(); Gen_t_003620e0_p4cd& operator=(const Gen_t_003620e0_p4cd&); };
bool operator==(const Gen_t_003620e0_p4cd&, const Gen_t_003620e0_p4cd&);
bool operator<(const Gen_t_003620e0_p4cd&, const Gen_t_003620e0_p4cd&);
template class _STL::vector<Gen_t_003620e0_p4cd >;
// 0x00363A60 tree_k4_p12cd
struct Gen_t_00363a60_k4 { int a[1]; Gen_t_00363a60_k4(); Gen_t_00363a60_k4(const Gen_t_00363a60_k4&); ~Gen_t_00363a60_k4(); Gen_t_00363a60_k4& operator=(const Gen_t_00363a60_k4&); };
bool operator==(const Gen_t_00363a60_k4&, const Gen_t_00363a60_k4&);
bool operator<(const Gen_t_00363a60_k4&, const Gen_t_00363a60_k4&);
struct Gen_t_00363a60_p12cd { int a[3]; Gen_t_00363a60_p12cd(); Gen_t_00363a60_p12cd(const Gen_t_00363a60_p12cd&); ~Gen_t_00363a60_p12cd(); Gen_t_00363a60_p12cd& operator=(const Gen_t_00363a60_p12cd&); };
bool operator==(const Gen_t_00363a60_p12cd&, const Gen_t_00363a60_p12cd&);
bool operator<(const Gen_t_00363a60_p12cd&, const Gen_t_00363a60_p12cd&);
typedef _STL::pair<const Gen_t_00363a60_k4, Gen_t_00363a60_p12cd > TgPair_tree_k4_p12cd_00363a60;
template class _STL::_Rb_tree<Gen_t_00363a60_k4, TgPair_tree_k4_p12cd_00363a60, _STL::_Select1st<TgPair_tree_k4_p12cd_00363a60 >, _STL::less<Gen_t_00363a60_k4 >, _STL::allocator<TgPair_tree_k4_p12cd_00363a60 > >;
// 0x003661E0 tree_k4_p12cd
struct Gen_t_003661e0_k4 { int a[1]; Gen_t_003661e0_k4(); Gen_t_003661e0_k4(const Gen_t_003661e0_k4&); ~Gen_t_003661e0_k4(); Gen_t_003661e0_k4& operator=(const Gen_t_003661e0_k4&); };
bool operator==(const Gen_t_003661e0_k4&, const Gen_t_003661e0_k4&);
bool operator<(const Gen_t_003661e0_k4&, const Gen_t_003661e0_k4&);
struct Gen_t_003661e0_p12cd { int a[3]; Gen_t_003661e0_p12cd(); Gen_t_003661e0_p12cd(const Gen_t_003661e0_p12cd&); ~Gen_t_003661e0_p12cd(); Gen_t_003661e0_p12cd& operator=(const Gen_t_003661e0_p12cd&); };
bool operator==(const Gen_t_003661e0_p12cd&, const Gen_t_003661e0_p12cd&);
bool operator<(const Gen_t_003661e0_p12cd&, const Gen_t_003661e0_p12cd&);
typedef _STL::pair<const Gen_t_003661e0_k4, Gen_t_003661e0_p12cd > TgPair_tree_k4_p12cd_003661e0;
template class _STL::_Rb_tree<Gen_t_003661e0_k4, TgPair_tree_k4_p12cd_003661e0, _STL::_Select1st<TgPair_tree_k4_p12cd_003661e0 >, _STL::less<Gen_t_003661e0_k4 >, _STL::allocator<TgPair_tree_k4_p12cd_003661e0 > >;
// 0x00369A60 vec_p16cd
struct Gen_t_00369a60_p16cd { int a[4]; Gen_t_00369a60_p16cd(); Gen_t_00369a60_p16cd(const Gen_t_00369a60_p16cd&); ~Gen_t_00369a60_p16cd(); Gen_t_00369a60_p16cd& operator=(const Gen_t_00369a60_p16cd&); };
bool operator==(const Gen_t_00369a60_p16cd&, const Gen_t_00369a60_p16cd&);
bool operator<(const Gen_t_00369a60_p16cd&, const Gen_t_00369a60_p16cd&);
template class _STL::vector<Gen_t_00369a60_p16cd >;
// 0x0036A520 vec_p16cd
struct Gen_t_0036a520_p16cd { int a[4]; Gen_t_0036a520_p16cd(); Gen_t_0036a520_p16cd(const Gen_t_0036a520_p16cd&); ~Gen_t_0036a520_p16cd(); Gen_t_0036a520_p16cd& operator=(const Gen_t_0036a520_p16cd&); };
bool operator==(const Gen_t_0036a520_p16cd&, const Gen_t_0036a520_p16cd&);
bool operator<(const Gen_t_0036a520_p16cd&, const Gen_t_0036a520_p16cd&);
template class _STL::vector<Gen_t_0036a520_p16cd >;
// 0x0036CC30 tree_k4_p12cd
struct Gen_t_0036cc30_k4 { int a[1]; Gen_t_0036cc30_k4(); Gen_t_0036cc30_k4(const Gen_t_0036cc30_k4&); ~Gen_t_0036cc30_k4(); Gen_t_0036cc30_k4& operator=(const Gen_t_0036cc30_k4&); };
bool operator==(const Gen_t_0036cc30_k4&, const Gen_t_0036cc30_k4&);
bool operator<(const Gen_t_0036cc30_k4&, const Gen_t_0036cc30_k4&);
struct Gen_t_0036cc30_p12cd { int a[3]; Gen_t_0036cc30_p12cd(); Gen_t_0036cc30_p12cd(const Gen_t_0036cc30_p12cd&); ~Gen_t_0036cc30_p12cd(); Gen_t_0036cc30_p12cd& operator=(const Gen_t_0036cc30_p12cd&); };
bool operator==(const Gen_t_0036cc30_p12cd&, const Gen_t_0036cc30_p12cd&);
bool operator<(const Gen_t_0036cc30_p12cd&, const Gen_t_0036cc30_p12cd&);
typedef _STL::pair<const Gen_t_0036cc30_k4, Gen_t_0036cc30_p12cd > TgPair_tree_k4_p12cd_0036cc30;
template class _STL::_Rb_tree<Gen_t_0036cc30_k4, TgPair_tree_k4_p12cd_0036cc30, _STL::_Select1st<TgPair_tree_k4_p12cd_0036cc30 >, _STL::less<Gen_t_0036cc30_k4 >, _STL::allocator<TgPair_tree_k4_p12cd_0036cc30 > >;
// 0x0036D490 tree_k4_p4pod
struct Gen_t_0036d490_k4 { int a[1]; Gen_t_0036d490_k4(); Gen_t_0036d490_k4(const Gen_t_0036d490_k4&); ~Gen_t_0036d490_k4(); Gen_t_0036d490_k4& operator=(const Gen_t_0036d490_k4&); };
bool operator==(const Gen_t_0036d490_k4&, const Gen_t_0036d490_k4&);
bool operator<(const Gen_t_0036d490_k4&, const Gen_t_0036d490_k4&);
struct Gen_t_0036d490_p4pod { int a[1]; };
bool operator==(const Gen_t_0036d490_p4pod&, const Gen_t_0036d490_p4pod&);
bool operator<(const Gen_t_0036d490_p4pod&, const Gen_t_0036d490_p4pod&);
typedef _STL::pair<const Gen_t_0036d490_k4, Gen_t_0036d490_p4pod > TgPair_tree_k4_p4pod_0036d490;
template class _STL::_Rb_tree<Gen_t_0036d490_k4, TgPair_tree_k4_p4pod_0036d490, _STL::_Select1st<TgPair_tree_k4_p4pod_0036d490 >, _STL::less<Gen_t_0036d490_k4 >, _STL::allocator<TgPair_tree_k4_p4pod_0036d490 > >;
// 0x0036D500 tree_k4_p12cd
struct Gen_t_0036d500_k4 { int a[1]; Gen_t_0036d500_k4(); Gen_t_0036d500_k4(const Gen_t_0036d500_k4&); ~Gen_t_0036d500_k4(); Gen_t_0036d500_k4& operator=(const Gen_t_0036d500_k4&); };
bool operator==(const Gen_t_0036d500_k4&, const Gen_t_0036d500_k4&);
bool operator<(const Gen_t_0036d500_k4&, const Gen_t_0036d500_k4&);
struct Gen_t_0036d500_p12cd { int a[3]; Gen_t_0036d500_p12cd(); Gen_t_0036d500_p12cd(const Gen_t_0036d500_p12cd&); ~Gen_t_0036d500_p12cd(); Gen_t_0036d500_p12cd& operator=(const Gen_t_0036d500_p12cd&); };
bool operator==(const Gen_t_0036d500_p12cd&, const Gen_t_0036d500_p12cd&);
bool operator<(const Gen_t_0036d500_p12cd&, const Gen_t_0036d500_p12cd&);
typedef _STL::pair<const Gen_t_0036d500_k4, Gen_t_0036d500_p12cd > TgPair_tree_k4_p12cd_0036d500;
template class _STL::_Rb_tree<Gen_t_0036d500_k4, TgPair_tree_k4_p12cd_0036d500, _STL::_Select1st<TgPair_tree_k4_p12cd_0036d500 >, _STL::less<Gen_t_0036d500_k4 >, _STL::allocator<TgPair_tree_k4_p12cd_0036d500 > >;
// 0x0036D7D0 vec_p4cd
struct Gen_t_0036d7d0_p4cd { int a[1]; Gen_t_0036d7d0_p4cd(); Gen_t_0036d7d0_p4cd(const Gen_t_0036d7d0_p4cd&); ~Gen_t_0036d7d0_p4cd(); Gen_t_0036d7d0_p4cd& operator=(const Gen_t_0036d7d0_p4cd&); };
bool operator==(const Gen_t_0036d7d0_p4cd&, const Gen_t_0036d7d0_p4cd&);
bool operator<(const Gen_t_0036d7d0_p4cd&, const Gen_t_0036d7d0_p4cd&);
template class _STL::vector<Gen_t_0036d7d0_p4cd >;
// 0x0036DDD0 tree_int_p12cd
struct Gen_t_0036ddd0_p12cd { int a[3]; Gen_t_0036ddd0_p12cd(); Gen_t_0036ddd0_p12cd(const Gen_t_0036ddd0_p12cd&); ~Gen_t_0036ddd0_p12cd(); Gen_t_0036ddd0_p12cd& operator=(const Gen_t_0036ddd0_p12cd&); };
bool operator==(const Gen_t_0036ddd0_p12cd&, const Gen_t_0036ddd0_p12cd&);
bool operator<(const Gen_t_0036ddd0_p12cd&, const Gen_t_0036ddd0_p12cd&);
typedef _STL::pair<const int, Gen_t_0036ddd0_p12cd > TgPair_tree_int_p12cd_0036ddd0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_0036ddd0, _STL::_Select1st<TgPair_tree_int_p12cd_0036ddd0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_0036ddd0 > >;
// 0x0036E8C0 tree_int_p12cd
struct Gen_t_0036e8c0_p12cd { int a[3]; Gen_t_0036e8c0_p12cd(); Gen_t_0036e8c0_p12cd(const Gen_t_0036e8c0_p12cd&); ~Gen_t_0036e8c0_p12cd(); Gen_t_0036e8c0_p12cd& operator=(const Gen_t_0036e8c0_p12cd&); };
bool operator==(const Gen_t_0036e8c0_p12cd&, const Gen_t_0036e8c0_p12cd&);
bool operator<(const Gen_t_0036e8c0_p12cd&, const Gen_t_0036e8c0_p12cd&);
typedef _STL::pair<const int, Gen_t_0036e8c0_p12cd > TgPair_tree_int_p12cd_0036e8c0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_0036e8c0, _STL::_Select1st<TgPair_tree_int_p12cd_0036e8c0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_0036e8c0 > >;
// 0x0036EA00 tree_int_p12cd
struct Gen_t_0036ea00_p12cd { int a[3]; Gen_t_0036ea00_p12cd(); Gen_t_0036ea00_p12cd(const Gen_t_0036ea00_p12cd&); ~Gen_t_0036ea00_p12cd(); Gen_t_0036ea00_p12cd& operator=(const Gen_t_0036ea00_p12cd&); };
bool operator==(const Gen_t_0036ea00_p12cd&, const Gen_t_0036ea00_p12cd&);
bool operator<(const Gen_t_0036ea00_p12cd&, const Gen_t_0036ea00_p12cd&);
typedef _STL::pair<const int, Gen_t_0036ea00_p12cd > TgPair_tree_int_p12cd_0036ea00;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_0036ea00, _STL::_Select1st<TgPair_tree_int_p12cd_0036ea00 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_0036ea00 > >;
// 0x0036ECF0 tree_int_p12cd
struct Gen_t_0036ecf0_p12cd { int a[3]; Gen_t_0036ecf0_p12cd(); Gen_t_0036ecf0_p12cd(const Gen_t_0036ecf0_p12cd&); ~Gen_t_0036ecf0_p12cd(); Gen_t_0036ecf0_p12cd& operator=(const Gen_t_0036ecf0_p12cd&); };
bool operator==(const Gen_t_0036ecf0_p12cd&, const Gen_t_0036ecf0_p12cd&);
bool operator<(const Gen_t_0036ecf0_p12cd&, const Gen_t_0036ecf0_p12cd&);
typedef _STL::pair<const int, Gen_t_0036ecf0_p12cd > TgPair_tree_int_p12cd_0036ecf0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_0036ecf0, _STL::_Select1st<TgPair_tree_int_p12cd_0036ecf0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_0036ecf0 > >;
// 0x0036EE10 vec_p4pod
struct Gen_t_0036ee10_p4pod { int a[1]; };
bool operator==(const Gen_t_0036ee10_p4pod&, const Gen_t_0036ee10_p4pod&);
bool operator<(const Gen_t_0036ee10_p4pod&, const Gen_t_0036ee10_p4pod&);
template class _STL::vector<Gen_t_0036ee10_p4pod >;
// 0x00370A00 tree_int_p12cd
struct Gen_t_00370a00_p12cd { int a[3]; Gen_t_00370a00_p12cd(); Gen_t_00370a00_p12cd(const Gen_t_00370a00_p12cd&); ~Gen_t_00370a00_p12cd(); Gen_t_00370a00_p12cd& operator=(const Gen_t_00370a00_p12cd&); };
bool operator==(const Gen_t_00370a00_p12cd&, const Gen_t_00370a00_p12cd&);
bool operator<(const Gen_t_00370a00_p12cd&, const Gen_t_00370a00_p12cd&);
typedef _STL::pair<const int, Gen_t_00370a00_p12cd > TgPair_tree_int_p12cd_00370a00;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00370a00, _STL::_Select1st<TgPair_tree_int_p12cd_00370a00 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00370a00 > >;
// 0x00372430 tree_int_p12cd
struct Gen_t_00372430_p12cd { int a[3]; Gen_t_00372430_p12cd(); Gen_t_00372430_p12cd(const Gen_t_00372430_p12cd&); ~Gen_t_00372430_p12cd(); Gen_t_00372430_p12cd& operator=(const Gen_t_00372430_p12cd&); };
bool operator==(const Gen_t_00372430_p12cd&, const Gen_t_00372430_p12cd&);
bool operator<(const Gen_t_00372430_p12cd&, const Gen_t_00372430_p12cd&);
typedef _STL::pair<const int, Gen_t_00372430_p12cd > TgPair_tree_int_p12cd_00372430;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00372430, _STL::_Select1st<TgPair_tree_int_p12cd_00372430 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00372430 > >;
// 0x00372470 tree_int_p12cd
struct Gen_t_00372470_p12cd { int a[3]; Gen_t_00372470_p12cd(); Gen_t_00372470_p12cd(const Gen_t_00372470_p12cd&); ~Gen_t_00372470_p12cd(); Gen_t_00372470_p12cd& operator=(const Gen_t_00372470_p12cd&); };
bool operator==(const Gen_t_00372470_p12cd&, const Gen_t_00372470_p12cd&);
bool operator<(const Gen_t_00372470_p12cd&, const Gen_t_00372470_p12cd&);
typedef _STL::pair<const int, Gen_t_00372470_p12cd > TgPair_tree_int_p12cd_00372470;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00372470, _STL::_Select1st<TgPair_tree_int_p12cd_00372470 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00372470 > >;
// 0x00372870 tree_int_p12cd
struct Gen_t_00372870_p12cd { int a[3]; Gen_t_00372870_p12cd(); Gen_t_00372870_p12cd(const Gen_t_00372870_p12cd&); ~Gen_t_00372870_p12cd(); Gen_t_00372870_p12cd& operator=(const Gen_t_00372870_p12cd&); };
bool operator==(const Gen_t_00372870_p12cd&, const Gen_t_00372870_p12cd&);
bool operator<(const Gen_t_00372870_p12cd&, const Gen_t_00372870_p12cd&);
typedef _STL::pair<const int, Gen_t_00372870_p12cd > TgPair_tree_int_p12cd_00372870;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00372870, _STL::_Select1st<TgPair_tree_int_p12cd_00372870 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00372870 > >;
// 0x003748D0 vec_p8cd
struct Gen_t_003748d0_p8cd { int a[2]; Gen_t_003748d0_p8cd(); Gen_t_003748d0_p8cd(const Gen_t_003748d0_p8cd&); ~Gen_t_003748d0_p8cd(); Gen_t_003748d0_p8cd& operator=(const Gen_t_003748d0_p8cd&); };
bool operator==(const Gen_t_003748d0_p8cd&, const Gen_t_003748d0_p8cd&);
bool operator<(const Gen_t_003748d0_p8cd&, const Gen_t_003748d0_p8cd&);
template class _STL::vector<Gen_t_003748d0_p8cd >;
// 0x00374B60 vec_p12cd
struct Gen_t_00374b60_p12cd { int a[3]; Gen_t_00374b60_p12cd(); Gen_t_00374b60_p12cd(const Gen_t_00374b60_p12cd&); ~Gen_t_00374b60_p12cd(); Gen_t_00374b60_p12cd& operator=(const Gen_t_00374b60_p12cd&); };
bool operator==(const Gen_t_00374b60_p12cd&, const Gen_t_00374b60_p12cd&);
bool operator<(const Gen_t_00374b60_p12cd&, const Gen_t_00374b60_p12cd&);
template class _STL::vector<Gen_t_00374b60_p12cd >;
// 0x00374BC0 vec_p8cd
struct Gen_t_00374bc0_p8cd { int a[2]; Gen_t_00374bc0_p8cd(); Gen_t_00374bc0_p8cd(const Gen_t_00374bc0_p8cd&); ~Gen_t_00374bc0_p8cd(); Gen_t_00374bc0_p8cd& operator=(const Gen_t_00374bc0_p8cd&); };
bool operator==(const Gen_t_00374bc0_p8cd&, const Gen_t_00374bc0_p8cd&);
bool operator<(const Gen_t_00374bc0_p8cd&, const Gen_t_00374bc0_p8cd&);
template class _STL::vector<Gen_t_00374bc0_p8cd >;
// 0x00374C30 vec_p12cd
struct Gen_t_00374c30_p12cd { int a[3]; Gen_t_00374c30_p12cd(); Gen_t_00374c30_p12cd(const Gen_t_00374c30_p12cd&); ~Gen_t_00374c30_p12cd(); Gen_t_00374c30_p12cd& operator=(const Gen_t_00374c30_p12cd&); };
bool operator==(const Gen_t_00374c30_p12cd&, const Gen_t_00374c30_p12cd&);
bool operator<(const Gen_t_00374c30_p12cd&, const Gen_t_00374c30_p12cd&);
template class _STL::vector<Gen_t_00374c30_p12cd >;
// 0x00375460 tree_int_p12cd
struct Gen_t_00375460_p12cd { int a[3]; Gen_t_00375460_p12cd(); Gen_t_00375460_p12cd(const Gen_t_00375460_p12cd&); ~Gen_t_00375460_p12cd(); Gen_t_00375460_p12cd& operator=(const Gen_t_00375460_p12cd&); };
bool operator==(const Gen_t_00375460_p12cd&, const Gen_t_00375460_p12cd&);
bool operator<(const Gen_t_00375460_p12cd&, const Gen_t_00375460_p12cd&);
typedef _STL::pair<const int, Gen_t_00375460_p12cd > TgPair_tree_int_p12cd_00375460;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00375460, _STL::_Select1st<TgPair_tree_int_p12cd_00375460 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00375460 > >;
