// cl: /EHsc
// stlport
// Generated by: python3 tools/gen_small.py gen-tgrid
// Do not edit by hand; regenerate instead.
//
// Each row this file carries is a retail body that IS this instantiation:
// the game links STLport 4.5.3, so a container member's code is the vendor
// template over a payload of that shape, and the payload's name never
// reaches the bytes. The synthetic payloads below are anonymous by design --
// they reproduce a layout and a lifecycle, never a class identity -- and
// every call target is read out of the retail bytes and pinned in
// targets/game/reverse/symbols.csv, so the bytes prove the callee.

#include <hash_map>

struct Gen_p4pod { int a[1]; };
bool operator==(const Gen_p4pod&, const Gen_p4pod&);
bool operator<(const Gen_p4pod&, const Gen_p4pod&);
struct Gen_p8pod { int a[2]; };
bool operator==(const Gen_p8pod&, const Gen_p8pod&);
bool operator<(const Gen_p8pod&, const Gen_p8pod&);
struct Gen_p12pod { int a[3]; };
bool operator==(const Gen_p12pod&, const Gen_p12pod&);
bool operator<(const Gen_p12pod&, const Gen_p12pod&);
struct Gen_p8cd { int a[2]; Gen_p8cd(); Gen_p8cd(const Gen_p8cd&); ~Gen_p8cd(); Gen_p8cd& operator=(const Gen_p8cd&); };
bool operator==(const Gen_p8cd&, const Gen_p8cd&);
bool operator<(const Gen_p8cd&, const Gen_p8cd&);
struct Gen_p12cd { int a[3]; Gen_p12cd(); Gen_p12cd(const Gen_p12cd&); ~Gen_p12cd(); Gen_p12cd& operator=(const Gen_p12cd&); };
bool operator==(const Gen_p12cd&, const Gen_p12cd&);
bool operator<(const Gen_p12cd&, const Gen_p12cd&);
struct Gen_p16cd { int a[4]; Gen_p16cd(); Gen_p16cd(const Gen_p16cd&); ~Gen_p16cd(); Gen_p16cd& operator=(const Gen_p16cd&); };
bool operator==(const Gen_p16cd&, const Gen_p16cd&);
bool operator<(const Gen_p16cd&, const Gen_p16cd&);

typedef _STL::pair<const int, Gen_p4pod > TgPair_hash_int_p4pod;
template class _STL::hash_map<int, Gen_p4pod, _STL::hash<int >, _STL::equal_to<int >, _STL::allocator<TgPair_hash_int_p4pod > >;
typedef _STL::pair<const int, Gen_p8pod > TgPair_hash_int_p8pod;
template class _STL::hash_map<int, Gen_p8pod, _STL::hash<int >, _STL::equal_to<int >, _STL::allocator<TgPair_hash_int_p8pod > >;
typedef _STL::pair<const int, Gen_p12pod > TgPair_hash_int_p12pod;
template class _STL::hash_map<int, Gen_p12pod, _STL::hash<int >, _STL::equal_to<int >, _STL::allocator<TgPair_hash_int_p12pod > >;
typedef _STL::pair<const int, Gen_p8cd > TgPair_hash_int_p8cd;
template class _STL::hash_map<int, Gen_p8cd, _STL::hash<int >, _STL::equal_to<int >, _STL::allocator<TgPair_hash_int_p8cd > >;
typedef _STL::pair<const int, Gen_p12cd > TgPair_hash_int_p12cd;
template class _STL::hash_map<int, Gen_p12cd, _STL::hash<int >, _STL::equal_to<int >, _STL::allocator<TgPair_hash_int_p12cd > >;
typedef _STL::pair<const int, Gen_p16cd > TgPair_hash_int_p16cd;
template class _STL::hash_map<int, Gen_p16cd, _STL::hash<int >, _STL::equal_to<int >, _STL::allocator<TgPair_hash_int_p16cd > >;
