// cl: /EHsc
// stlport
// Generated by: python3 tools/gen_small.py gen-tgrid
// Do not edit by hand; regenerate instead.
//
// Each row this file carries is a retail body that IS this instantiation:
// the game links STLport 4.5.3, so a container member's code is the vendor
// template over a payload of that shape, and the payload's name never
// reaches the bytes. The synthetic payloads below are anonymous by design --
// they reproduce a layout and a lifecycle, never a class identity -- and
// every call target is read out of the retail bytes and pinned in
// targets/game/reverse/symbols.csv, so the bytes prove the callee.

#include <list>
#include <map>
#include <memory>
#include <utility>

// 0x00647AD0 tree_int_p12cd
struct Gen_t_00647ad0_p12cd { int a[3]; Gen_t_00647ad0_p12cd(); Gen_t_00647ad0_p12cd(const Gen_t_00647ad0_p12cd&); ~Gen_t_00647ad0_p12cd(); Gen_t_00647ad0_p12cd& operator=(const Gen_t_00647ad0_p12cd&); };
bool operator==(const Gen_t_00647ad0_p12cd&, const Gen_t_00647ad0_p12cd&);
bool operator<(const Gen_t_00647ad0_p12cd&, const Gen_t_00647ad0_p12cd&);
typedef _STL::pair<const int, Gen_t_00647ad0_p12cd > TgPair_tree_int_p12cd_00647ad0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00647ad0, _STL::_Select1st<TgPair_tree_int_p12cd_00647ad0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00647ad0 > >;
// 0x00647B20 tree_k4_p12cd
struct Gen_t_00647b20_k4 { int a[1]; Gen_t_00647b20_k4(); Gen_t_00647b20_k4(const Gen_t_00647b20_k4&); ~Gen_t_00647b20_k4(); Gen_t_00647b20_k4& operator=(const Gen_t_00647b20_k4&); };
bool operator==(const Gen_t_00647b20_k4&, const Gen_t_00647b20_k4&);
bool operator<(const Gen_t_00647b20_k4&, const Gen_t_00647b20_k4&);
struct Gen_t_00647b20_p12cd { int a[3]; Gen_t_00647b20_p12cd(); Gen_t_00647b20_p12cd(const Gen_t_00647b20_p12cd&); ~Gen_t_00647b20_p12cd(); Gen_t_00647b20_p12cd& operator=(const Gen_t_00647b20_p12cd&); };
bool operator==(const Gen_t_00647b20_p12cd&, const Gen_t_00647b20_p12cd&);
bool operator<(const Gen_t_00647b20_p12cd&, const Gen_t_00647b20_p12cd&);
typedef _STL::pair<const Gen_t_00647b20_k4, Gen_t_00647b20_p12cd > TgPair_tree_k4_p12cd_00647b20;
template class _STL::_Rb_tree<Gen_t_00647b20_k4, TgPair_tree_k4_p12cd_00647b20, _STL::_Select1st<TgPair_tree_k4_p12cd_00647b20 >, _STL::less<Gen_t_00647b20_k4 >, _STL::allocator<TgPair_tree_k4_p12cd_00647b20 > >;
// 0x006487D0 tree_int_p12cd
struct Gen_t_006487d0_p12cd { int a[3]; Gen_t_006487d0_p12cd(); Gen_t_006487d0_p12cd(const Gen_t_006487d0_p12cd&); ~Gen_t_006487d0_p12cd(); Gen_t_006487d0_p12cd& operator=(const Gen_t_006487d0_p12cd&); };
bool operator==(const Gen_t_006487d0_p12cd&, const Gen_t_006487d0_p12cd&);
bool operator<(const Gen_t_006487d0_p12cd&, const Gen_t_006487d0_p12cd&);
typedef _STL::pair<const int, Gen_t_006487d0_p12cd > TgPair_tree_int_p12cd_006487d0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_006487d0, _STL::_Select1st<TgPair_tree_int_p12cd_006487d0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_006487d0 > >;
// 0x0064C250 tree_int_p12cd
struct Gen_t_0064c250_p12cd { int a[3]; Gen_t_0064c250_p12cd(); Gen_t_0064c250_p12cd(const Gen_t_0064c250_p12cd&); ~Gen_t_0064c250_p12cd(); Gen_t_0064c250_p12cd& operator=(const Gen_t_0064c250_p12cd&); };
bool operator==(const Gen_t_0064c250_p12cd&, const Gen_t_0064c250_p12cd&);
bool operator<(const Gen_t_0064c250_p12cd&, const Gen_t_0064c250_p12cd&);
typedef _STL::pair<const int, Gen_t_0064c250_p12cd > TgPair_tree_int_p12cd_0064c250;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_0064c250, _STL::_Select1st<TgPair_tree_int_p12cd_0064c250 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_0064c250 > >;
// 0x0064C290 tree_int_p12cd
struct Gen_t_0064c290_p12cd { int a[3]; Gen_t_0064c290_p12cd(); Gen_t_0064c290_p12cd(const Gen_t_0064c290_p12cd&); ~Gen_t_0064c290_p12cd(); Gen_t_0064c290_p12cd& operator=(const Gen_t_0064c290_p12cd&); };
bool operator==(const Gen_t_0064c290_p12cd&, const Gen_t_0064c290_p12cd&);
bool operator<(const Gen_t_0064c290_p12cd&, const Gen_t_0064c290_p12cd&);
typedef _STL::pair<const int, Gen_t_0064c290_p12cd > TgPair_tree_int_p12cd_0064c290;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_0064c290, _STL::_Select1st<TgPair_tree_int_p12cd_0064c290 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_0064c290 > >;
// 0x00652490 tree_int_p4pod
struct Gen_t_00652490_p4pod { int a[1]; };
bool operator==(const Gen_t_00652490_p4pod&, const Gen_t_00652490_p4pod&);
bool operator<(const Gen_t_00652490_p4pod&, const Gen_t_00652490_p4pod&);
typedef _STL::pair<const int, Gen_t_00652490_p4pod > TgPair_tree_int_p4pod_00652490;
template class _STL::_Rb_tree<int, TgPair_tree_int_p4pod_00652490, _STL::_Select1st<TgPair_tree_int_p4pod_00652490 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p4pod_00652490 > >;
// 0x00652C00 tree_int_p12cd
struct Gen_t_00652c00_p12cd { int a[3]; Gen_t_00652c00_p12cd(); Gen_t_00652c00_p12cd(const Gen_t_00652c00_p12cd&); ~Gen_t_00652c00_p12cd(); Gen_t_00652c00_p12cd& operator=(const Gen_t_00652c00_p12cd&); };
bool operator==(const Gen_t_00652c00_p12cd&, const Gen_t_00652c00_p12cd&);
bool operator<(const Gen_t_00652c00_p12cd&, const Gen_t_00652c00_p12cd&);
typedef _STL::pair<const int, Gen_t_00652c00_p12cd > TgPair_tree_int_p12cd_00652c00;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00652c00, _STL::_Select1st<TgPair_tree_int_p12cd_00652c00 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00652c00 > >;
// 0x00653080 uninit_p12cd
struct Gen_t_00653080_p12cd { int a[3]; Gen_t_00653080_p12cd(); Gen_t_00653080_p12cd(const Gen_t_00653080_p12cd&); ~Gen_t_00653080_p12cd(); Gen_t_00653080_p12cd& operator=(const Gen_t_00653080_p12cd&); };
bool operator==(const Gen_t_00653080_p12cd&, const Gen_t_00653080_p12cd&);
bool operator<(const Gen_t_00653080_p12cd&, const Gen_t_00653080_p12cd&);
template Gen_t_00653080_p12cd* _STL::uninitialized_copy(const Gen_t_00653080_p12cd*, const Gen_t_00653080_p12cd*, Gen_t_00653080_p12cd*);
template Gen_t_00653080_p12cd* _STL::uninitialized_fill_n(Gen_t_00653080_p12cd*, unsigned int, const Gen_t_00653080_p12cd&);
// 0x006536B0 tree_int_p12cd
struct Gen_t_006536b0_p12cd { int a[3]; Gen_t_006536b0_p12cd(); Gen_t_006536b0_p12cd(const Gen_t_006536b0_p12cd&); ~Gen_t_006536b0_p12cd(); Gen_t_006536b0_p12cd& operator=(const Gen_t_006536b0_p12cd&); };
bool operator==(const Gen_t_006536b0_p12cd&, const Gen_t_006536b0_p12cd&);
bool operator<(const Gen_t_006536b0_p12cd&, const Gen_t_006536b0_p12cd&);
typedef _STL::pair<const int, Gen_t_006536b0_p12cd > TgPair_tree_int_p12cd_006536b0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_006536b0, _STL::_Select1st<TgPair_tree_int_p12cd_006536b0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_006536b0 > >;
// 0x00653710 tree_int_p4pod
struct Gen_t_00653710_p4pod { int a[1]; };
bool operator==(const Gen_t_00653710_p4pod&, const Gen_t_00653710_p4pod&);
bool operator<(const Gen_t_00653710_p4pod&, const Gen_t_00653710_p4pod&);
typedef _STL::pair<const int, Gen_t_00653710_p4pod > TgPair_tree_int_p4pod_00653710;
template class _STL::_Rb_tree<int, TgPair_tree_int_p4pod_00653710, _STL::_Select1st<TgPair_tree_int_p4pod_00653710 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p4pod_00653710 > >;
// 0x00654460 tree_int_p12cd
struct Gen_t_00654460_p12cd { int a[3]; Gen_t_00654460_p12cd(); Gen_t_00654460_p12cd(const Gen_t_00654460_p12cd&); ~Gen_t_00654460_p12cd(); Gen_t_00654460_p12cd& operator=(const Gen_t_00654460_p12cd&); };
bool operator==(const Gen_t_00654460_p12cd&, const Gen_t_00654460_p12cd&);
bool operator<(const Gen_t_00654460_p12cd&, const Gen_t_00654460_p12cd&);
typedef _STL::pair<const int, Gen_t_00654460_p12cd > TgPair_tree_int_p12cd_00654460;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00654460, _STL::_Select1st<TgPair_tree_int_p12cd_00654460 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00654460 > >;
// 0x00656C40 tree_int_p12cd
struct Gen_t_00656c40_p12cd { int a[3]; Gen_t_00656c40_p12cd(); Gen_t_00656c40_p12cd(const Gen_t_00656c40_p12cd&); ~Gen_t_00656c40_p12cd(); Gen_t_00656c40_p12cd& operator=(const Gen_t_00656c40_p12cd&); };
bool operator==(const Gen_t_00656c40_p12cd&, const Gen_t_00656c40_p12cd&);
bool operator<(const Gen_t_00656c40_p12cd&, const Gen_t_00656c40_p12cd&);
typedef _STL::pair<const int, Gen_t_00656c40_p12cd > TgPair_tree_int_p12cd_00656c40;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00656c40, _STL::_Select1st<TgPair_tree_int_p12cd_00656c40 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00656c40 > >;
// 0x0065AA20 tree_k4_p12cd
struct Gen_t_0065aa20_k4 { int a[1]; Gen_t_0065aa20_k4(); Gen_t_0065aa20_k4(const Gen_t_0065aa20_k4&); ~Gen_t_0065aa20_k4(); Gen_t_0065aa20_k4& operator=(const Gen_t_0065aa20_k4&); };
bool operator==(const Gen_t_0065aa20_k4&, const Gen_t_0065aa20_k4&);
bool operator<(const Gen_t_0065aa20_k4&, const Gen_t_0065aa20_k4&);
struct Gen_t_0065aa20_p12cd { int a[3]; Gen_t_0065aa20_p12cd(); Gen_t_0065aa20_p12cd(const Gen_t_0065aa20_p12cd&); ~Gen_t_0065aa20_p12cd(); Gen_t_0065aa20_p12cd& operator=(const Gen_t_0065aa20_p12cd&); };
bool operator==(const Gen_t_0065aa20_p12cd&, const Gen_t_0065aa20_p12cd&);
bool operator<(const Gen_t_0065aa20_p12cd&, const Gen_t_0065aa20_p12cd&);
typedef _STL::pair<const Gen_t_0065aa20_k4, Gen_t_0065aa20_p12cd > TgPair_tree_k4_p12cd_0065aa20;
template class _STL::_Rb_tree<Gen_t_0065aa20_k4, TgPair_tree_k4_p12cd_0065aa20, _STL::_Select1st<TgPair_tree_k4_p12cd_0065aa20 >, _STL::less<Gen_t_0065aa20_k4 >, _STL::allocator<TgPair_tree_k4_p12cd_0065aa20 > >;
// 0x0065AA80 tree_k4_p12cd
struct Gen_t_0065aa80_k4 { int a[1]; Gen_t_0065aa80_k4(); Gen_t_0065aa80_k4(const Gen_t_0065aa80_k4&); ~Gen_t_0065aa80_k4(); Gen_t_0065aa80_k4& operator=(const Gen_t_0065aa80_k4&); };
bool operator==(const Gen_t_0065aa80_k4&, const Gen_t_0065aa80_k4&);
bool operator<(const Gen_t_0065aa80_k4&, const Gen_t_0065aa80_k4&);
struct Gen_t_0065aa80_p12cd { int a[3]; Gen_t_0065aa80_p12cd(); Gen_t_0065aa80_p12cd(const Gen_t_0065aa80_p12cd&); ~Gen_t_0065aa80_p12cd(); Gen_t_0065aa80_p12cd& operator=(const Gen_t_0065aa80_p12cd&); };
bool operator==(const Gen_t_0065aa80_p12cd&, const Gen_t_0065aa80_p12cd&);
bool operator<(const Gen_t_0065aa80_p12cd&, const Gen_t_0065aa80_p12cd&);
typedef _STL::pair<const Gen_t_0065aa80_k4, Gen_t_0065aa80_p12cd > TgPair_tree_k4_p12cd_0065aa80;
template class _STL::_Rb_tree<Gen_t_0065aa80_k4, TgPair_tree_k4_p12cd_0065aa80, _STL::_Select1st<TgPair_tree_k4_p12cd_0065aa80 >, _STL::less<Gen_t_0065aa80_k4 >, _STL::allocator<TgPair_tree_k4_p12cd_0065aa80 > >;
// 0x0065AAE0 tree_int_p12cd
struct Gen_t_0065aae0_p12cd { int a[3]; Gen_t_0065aae0_p12cd(); Gen_t_0065aae0_p12cd(const Gen_t_0065aae0_p12cd&); ~Gen_t_0065aae0_p12cd(); Gen_t_0065aae0_p12cd& operator=(const Gen_t_0065aae0_p12cd&); };
bool operator==(const Gen_t_0065aae0_p12cd&, const Gen_t_0065aae0_p12cd&);
bool operator<(const Gen_t_0065aae0_p12cd&, const Gen_t_0065aae0_p12cd&);
typedef _STL::pair<const int, Gen_t_0065aae0_p12cd > TgPair_tree_int_p12cd_0065aae0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_0065aae0, _STL::_Select1st<TgPair_tree_int_p12cd_0065aae0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_0065aae0 > >;
// 0x0065DD60 tree_int_p12cd
struct Gen_t_0065dd60_p12cd { int a[3]; Gen_t_0065dd60_p12cd(); Gen_t_0065dd60_p12cd(const Gen_t_0065dd60_p12cd&); ~Gen_t_0065dd60_p12cd(); Gen_t_0065dd60_p12cd& operator=(const Gen_t_0065dd60_p12cd&); };
bool operator==(const Gen_t_0065dd60_p12cd&, const Gen_t_0065dd60_p12cd&);
bool operator<(const Gen_t_0065dd60_p12cd&, const Gen_t_0065dd60_p12cd&);
typedef _STL::pair<const int, Gen_t_0065dd60_p12cd > TgPair_tree_int_p12cd_0065dd60;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_0065dd60, _STL::_Select1st<TgPair_tree_int_p12cd_0065dd60 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_0065dd60 > >;
// 0x00665170 tree_int_p4pod
struct Gen_t_00665170_p4pod { int a[1]; };
bool operator==(const Gen_t_00665170_p4pod&, const Gen_t_00665170_p4pod&);
bool operator<(const Gen_t_00665170_p4pod&, const Gen_t_00665170_p4pod&);
typedef _STL::pair<const int, Gen_t_00665170_p4pod > TgPair_tree_int_p4pod_00665170;
template class _STL::_Rb_tree<int, TgPair_tree_int_p4pod_00665170, _STL::_Select1st<TgPair_tree_int_p4pod_00665170 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p4pod_00665170 > >;
// 0x00666D70 tree_int_p12cd
struct Gen_t_00666d70_p12cd { int a[3]; Gen_t_00666d70_p12cd(); Gen_t_00666d70_p12cd(const Gen_t_00666d70_p12cd&); ~Gen_t_00666d70_p12cd(); Gen_t_00666d70_p12cd& operator=(const Gen_t_00666d70_p12cd&); };
bool operator==(const Gen_t_00666d70_p12cd&, const Gen_t_00666d70_p12cd&);
bool operator<(const Gen_t_00666d70_p12cd&, const Gen_t_00666d70_p12cd&);
typedef _STL::pair<const int, Gen_t_00666d70_p12cd > TgPair_tree_int_p12cd_00666d70;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00666d70, _STL::_Select1st<TgPair_tree_int_p12cd_00666d70 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00666d70 > >;
// 0x00666DE0 tree_int_p12cd
struct Gen_t_00666de0_p12cd { int a[3]; Gen_t_00666de0_p12cd(); Gen_t_00666de0_p12cd(const Gen_t_00666de0_p12cd&); ~Gen_t_00666de0_p12cd(); Gen_t_00666de0_p12cd& operator=(const Gen_t_00666de0_p12cd&); };
bool operator==(const Gen_t_00666de0_p12cd&, const Gen_t_00666de0_p12cd&);
bool operator<(const Gen_t_00666de0_p12cd&, const Gen_t_00666de0_p12cd&);
typedef _STL::pair<const int, Gen_t_00666de0_p12cd > TgPair_tree_int_p12cd_00666de0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00666de0, _STL::_Select1st<TgPair_tree_int_p12cd_00666de0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00666de0 > >;
// 0x006677E0 tree_int_p12cd
struct Gen_t_006677e0_p12cd { int a[3]; Gen_t_006677e0_p12cd(); Gen_t_006677e0_p12cd(const Gen_t_006677e0_p12cd&); ~Gen_t_006677e0_p12cd(); Gen_t_006677e0_p12cd& operator=(const Gen_t_006677e0_p12cd&); };
bool operator==(const Gen_t_006677e0_p12cd&, const Gen_t_006677e0_p12cd&);
bool operator<(const Gen_t_006677e0_p12cd&, const Gen_t_006677e0_p12cd&);
typedef _STL::pair<const int, Gen_t_006677e0_p12cd > TgPair_tree_int_p12cd_006677e0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_006677e0, _STL::_Select1st<TgPair_tree_int_p12cd_006677e0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_006677e0 > >;
// 0x006678C0 tree_int_p12cd
struct Gen_t_006678c0_p12cd { int a[3]; Gen_t_006678c0_p12cd(); Gen_t_006678c0_p12cd(const Gen_t_006678c0_p12cd&); ~Gen_t_006678c0_p12cd(); Gen_t_006678c0_p12cd& operator=(const Gen_t_006678c0_p12cd&); };
bool operator==(const Gen_t_006678c0_p12cd&, const Gen_t_006678c0_p12cd&);
bool operator<(const Gen_t_006678c0_p12cd&, const Gen_t_006678c0_p12cd&);
typedef _STL::pair<const int, Gen_t_006678c0_p12cd > TgPair_tree_int_p12cd_006678c0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_006678c0, _STL::_Select1st<TgPair_tree_int_p12cd_006678c0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_006678c0 > >;
// 0x00667900 tree_int_p4pod
struct Gen_t_00667900_p4pod { int a[1]; };
bool operator==(const Gen_t_00667900_p4pod&, const Gen_t_00667900_p4pod&);
bool operator<(const Gen_t_00667900_p4pod&, const Gen_t_00667900_p4pod&);
typedef _STL::pair<const int, Gen_t_00667900_p4pod > TgPair_tree_int_p4pod_00667900;
template class _STL::_Rb_tree<int, TgPair_tree_int_p4pod_00667900, _STL::_Select1st<TgPair_tree_int_p4pod_00667900 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p4pod_00667900 > >;
// 0x00667B50 tree_k4_p4pod
struct Gen_t_00667b50_k4 { int a[1]; Gen_t_00667b50_k4(); Gen_t_00667b50_k4(const Gen_t_00667b50_k4&); ~Gen_t_00667b50_k4(); Gen_t_00667b50_k4& operator=(const Gen_t_00667b50_k4&); };
bool operator==(const Gen_t_00667b50_k4&, const Gen_t_00667b50_k4&);
bool operator<(const Gen_t_00667b50_k4&, const Gen_t_00667b50_k4&);
struct Gen_t_00667b50_p4pod { int a[1]; };
bool operator==(const Gen_t_00667b50_p4pod&, const Gen_t_00667b50_p4pod&);
bool operator<(const Gen_t_00667b50_p4pod&, const Gen_t_00667b50_p4pod&);
typedef _STL::pair<const Gen_t_00667b50_k4, Gen_t_00667b50_p4pod > TgPair_tree_k4_p4pod_00667b50;
template class _STL::_Rb_tree<Gen_t_00667b50_k4, TgPair_tree_k4_p4pod_00667b50, _STL::_Select1st<TgPair_tree_k4_p4pod_00667b50 >, _STL::less<Gen_t_00667b50_k4 >, _STL::allocator<TgPair_tree_k4_p4pod_00667b50 > >;
// 0x00668090 tree_int_p12cd
struct Gen_t_00668090_p12cd { int a[3]; Gen_t_00668090_p12cd(); Gen_t_00668090_p12cd(const Gen_t_00668090_p12cd&); ~Gen_t_00668090_p12cd(); Gen_t_00668090_p12cd& operator=(const Gen_t_00668090_p12cd&); };
bool operator==(const Gen_t_00668090_p12cd&, const Gen_t_00668090_p12cd&);
bool operator<(const Gen_t_00668090_p12cd&, const Gen_t_00668090_p12cd&);
typedef _STL::pair<const int, Gen_t_00668090_p12cd > TgPair_tree_int_p12cd_00668090;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00668090, _STL::_Select1st<TgPair_tree_int_p12cd_00668090 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00668090 > >;
// 0x00668950 tree_int_p12cd
struct Gen_t_00668950_p12cd { int a[3]; Gen_t_00668950_p12cd(); Gen_t_00668950_p12cd(const Gen_t_00668950_p12cd&); ~Gen_t_00668950_p12cd(); Gen_t_00668950_p12cd& operator=(const Gen_t_00668950_p12cd&); };
bool operator==(const Gen_t_00668950_p12cd&, const Gen_t_00668950_p12cd&);
bool operator<(const Gen_t_00668950_p12cd&, const Gen_t_00668950_p12cd&);
typedef _STL::pair<const int, Gen_t_00668950_p12cd > TgPair_tree_int_p12cd_00668950;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00668950, _STL::_Select1st<TgPair_tree_int_p12cd_00668950 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00668950 > >;
// 0x00668990 tree_int_p4pod
struct Gen_t_00668990_p4pod { int a[1]; };
bool operator==(const Gen_t_00668990_p4pod&, const Gen_t_00668990_p4pod&);
bool operator<(const Gen_t_00668990_p4pod&, const Gen_t_00668990_p4pod&);
typedef _STL::pair<const int, Gen_t_00668990_p4pod > TgPair_tree_int_p4pod_00668990;
template class _STL::_Rb_tree<int, TgPair_tree_int_p4pod_00668990, _STL::_Select1st<TgPair_tree_int_p4pod_00668990 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p4pod_00668990 > >;
// 0x00681420 list_p4cd
struct Gen_t_00681420_p4cd { int a[1]; Gen_t_00681420_p4cd(); Gen_t_00681420_p4cd(const Gen_t_00681420_p4cd&); ~Gen_t_00681420_p4cd(); Gen_t_00681420_p4cd& operator=(const Gen_t_00681420_p4cd&); };
bool operator==(const Gen_t_00681420_p4cd&, const Gen_t_00681420_p4cd&);
bool operator<(const Gen_t_00681420_p4cd&, const Gen_t_00681420_p4cd&);
template class _STL::list<Gen_t_00681420_p4cd >;
// 0x0068F960 tree_k4_p4pod
struct Gen_t_0068f960_k4 { int a[1]; Gen_t_0068f960_k4(); Gen_t_0068f960_k4(const Gen_t_0068f960_k4&); ~Gen_t_0068f960_k4(); Gen_t_0068f960_k4& operator=(const Gen_t_0068f960_k4&); };
bool operator==(const Gen_t_0068f960_k4&, const Gen_t_0068f960_k4&);
bool operator<(const Gen_t_0068f960_k4&, const Gen_t_0068f960_k4&);
struct Gen_t_0068f960_p4pod { int a[1]; };
bool operator==(const Gen_t_0068f960_p4pod&, const Gen_t_0068f960_p4pod&);
bool operator<(const Gen_t_0068f960_p4pod&, const Gen_t_0068f960_p4pod&);
typedef _STL::pair<const Gen_t_0068f960_k4, Gen_t_0068f960_p4pod > TgPair_tree_k4_p4pod_0068f960;
template class _STL::_Rb_tree<Gen_t_0068f960_k4, TgPair_tree_k4_p4pod_0068f960, _STL::_Select1st<TgPair_tree_k4_p4pod_0068f960 >, _STL::less<Gen_t_0068f960_k4 >, _STL::allocator<TgPair_tree_k4_p4pod_0068f960 > >;
// 0x0068F9E0 tree_int_p12cd
struct Gen_t_0068f9e0_p12cd { int a[3]; Gen_t_0068f9e0_p12cd(); Gen_t_0068f9e0_p12cd(const Gen_t_0068f9e0_p12cd&); ~Gen_t_0068f9e0_p12cd(); Gen_t_0068f9e0_p12cd& operator=(const Gen_t_0068f9e0_p12cd&); };
bool operator==(const Gen_t_0068f9e0_p12cd&, const Gen_t_0068f9e0_p12cd&);
bool operator<(const Gen_t_0068f9e0_p12cd&, const Gen_t_0068f9e0_p12cd&);
typedef _STL::pair<const int, Gen_t_0068f9e0_p12cd > TgPair_tree_int_p12cd_0068f9e0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_0068f9e0, _STL::_Select1st<TgPair_tree_int_p12cd_0068f9e0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_0068f9e0 > >;
// 0x0068FEA0 tree_int_p4pod
struct Gen_t_0068fea0_p4pod { int a[1]; };
bool operator==(const Gen_t_0068fea0_p4pod&, const Gen_t_0068fea0_p4pod&);
bool operator<(const Gen_t_0068fea0_p4pod&, const Gen_t_0068fea0_p4pod&);
typedef _STL::pair<const int, Gen_t_0068fea0_p4pod > TgPair_tree_int_p4pod_0068fea0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p4pod_0068fea0, _STL::_Select1st<TgPair_tree_int_p4pod_0068fea0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p4pod_0068fea0 > >;
// 0x00692480 tree_k4_p4pod
struct Gen_t_00692480_k4 { int a[1]; Gen_t_00692480_k4(); Gen_t_00692480_k4(const Gen_t_00692480_k4&); ~Gen_t_00692480_k4(); Gen_t_00692480_k4& operator=(const Gen_t_00692480_k4&); };
bool operator==(const Gen_t_00692480_k4&, const Gen_t_00692480_k4&);
bool operator<(const Gen_t_00692480_k4&, const Gen_t_00692480_k4&);
struct Gen_t_00692480_p4pod { int a[1]; };
bool operator==(const Gen_t_00692480_p4pod&, const Gen_t_00692480_p4pod&);
bool operator<(const Gen_t_00692480_p4pod&, const Gen_t_00692480_p4pod&);
typedef _STL::pair<const Gen_t_00692480_k4, Gen_t_00692480_p4pod > TgPair_tree_k4_p4pod_00692480;
template class _STL::_Rb_tree<Gen_t_00692480_k4, TgPair_tree_k4_p4pod_00692480, _STL::_Select1st<TgPair_tree_k4_p4pod_00692480 >, _STL::less<Gen_t_00692480_k4 >, _STL::allocator<TgPair_tree_k4_p4pod_00692480 > >;
// 0x00692510 tree_int_p12cd
struct Gen_t_00692510_p12cd { int a[3]; Gen_t_00692510_p12cd(); Gen_t_00692510_p12cd(const Gen_t_00692510_p12cd&); ~Gen_t_00692510_p12cd(); Gen_t_00692510_p12cd& operator=(const Gen_t_00692510_p12cd&); };
bool operator==(const Gen_t_00692510_p12cd&, const Gen_t_00692510_p12cd&);
bool operator<(const Gen_t_00692510_p12cd&, const Gen_t_00692510_p12cd&);
typedef _STL::pair<const int, Gen_t_00692510_p12cd > TgPair_tree_int_p12cd_00692510;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00692510, _STL::_Select1st<TgPair_tree_int_p12cd_00692510 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00692510 > >;
// 0x00692630 tree_k4_p4pod
struct Gen_t_00692630_k4 { int a[1]; Gen_t_00692630_k4(); Gen_t_00692630_k4(const Gen_t_00692630_k4&); ~Gen_t_00692630_k4(); Gen_t_00692630_k4& operator=(const Gen_t_00692630_k4&); };
bool operator==(const Gen_t_00692630_k4&, const Gen_t_00692630_k4&);
bool operator<(const Gen_t_00692630_k4&, const Gen_t_00692630_k4&);
struct Gen_t_00692630_p4pod { int a[1]; };
bool operator==(const Gen_t_00692630_p4pod&, const Gen_t_00692630_p4pod&);
bool operator<(const Gen_t_00692630_p4pod&, const Gen_t_00692630_p4pod&);
typedef _STL::pair<const Gen_t_00692630_k4, Gen_t_00692630_p4pod > TgPair_tree_k4_p4pod_00692630;
template class _STL::_Rb_tree<Gen_t_00692630_k4, TgPair_tree_k4_p4pod_00692630, _STL::_Select1st<TgPair_tree_k4_p4pod_00692630 >, _STL::less<Gen_t_00692630_k4 >, _STL::allocator<TgPair_tree_k4_p4pod_00692630 > >;
// 0x00692870 tree_k4_p4pod
struct Gen_t_00692870_k4 { int a[1]; Gen_t_00692870_k4(); Gen_t_00692870_k4(const Gen_t_00692870_k4&); ~Gen_t_00692870_k4(); Gen_t_00692870_k4& operator=(const Gen_t_00692870_k4&); };
bool operator==(const Gen_t_00692870_k4&, const Gen_t_00692870_k4&);
bool operator<(const Gen_t_00692870_k4&, const Gen_t_00692870_k4&);
struct Gen_t_00692870_p4pod { int a[1]; };
bool operator==(const Gen_t_00692870_p4pod&, const Gen_t_00692870_p4pod&);
bool operator<(const Gen_t_00692870_p4pod&, const Gen_t_00692870_p4pod&);
typedef _STL::pair<const Gen_t_00692870_k4, Gen_t_00692870_p4pod > TgPair_tree_k4_p4pod_00692870;
template class _STL::_Rb_tree<Gen_t_00692870_k4, TgPair_tree_k4_p4pod_00692870, _STL::_Select1st<TgPair_tree_k4_p4pod_00692870 >, _STL::less<Gen_t_00692870_k4 >, _STL::allocator<TgPair_tree_k4_p4pod_00692870 > >;
// 0x00692BA0 tree_k4_p4pod
struct Gen_t_00692ba0_k4 { int a[1]; Gen_t_00692ba0_k4(); Gen_t_00692ba0_k4(const Gen_t_00692ba0_k4&); ~Gen_t_00692ba0_k4(); Gen_t_00692ba0_k4& operator=(const Gen_t_00692ba0_k4&); };
bool operator==(const Gen_t_00692ba0_k4&, const Gen_t_00692ba0_k4&);
bool operator<(const Gen_t_00692ba0_k4&, const Gen_t_00692ba0_k4&);
struct Gen_t_00692ba0_p4pod { int a[1]; };
bool operator==(const Gen_t_00692ba0_p4pod&, const Gen_t_00692ba0_p4pod&);
bool operator<(const Gen_t_00692ba0_p4pod&, const Gen_t_00692ba0_p4pod&);
typedef _STL::pair<const Gen_t_00692ba0_k4, Gen_t_00692ba0_p4pod > TgPair_tree_k4_p4pod_00692ba0;
template class _STL::_Rb_tree<Gen_t_00692ba0_k4, TgPair_tree_k4_p4pod_00692ba0, _STL::_Select1st<TgPair_tree_k4_p4pod_00692ba0 >, _STL::less<Gen_t_00692ba0_k4 >, _STL::allocator<TgPair_tree_k4_p4pod_00692ba0 > >;
// 0x00692C00 tree_int_p12cd
struct Gen_t_00692c00_p12cd { int a[3]; Gen_t_00692c00_p12cd(); Gen_t_00692c00_p12cd(const Gen_t_00692c00_p12cd&); ~Gen_t_00692c00_p12cd(); Gen_t_00692c00_p12cd& operator=(const Gen_t_00692c00_p12cd&); };
bool operator==(const Gen_t_00692c00_p12cd&, const Gen_t_00692c00_p12cd&);
bool operator<(const Gen_t_00692c00_p12cd&, const Gen_t_00692c00_p12cd&);
typedef _STL::pair<const int, Gen_t_00692c00_p12cd > TgPair_tree_int_p12cd_00692c00;
template class _STL::_Rb_tree<int, TgPair_tree_int_p12cd_00692c00, _STL::_Select1st<TgPair_tree_int_p12cd_00692c00 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p12cd_00692c00 > >;
// 0x00693350 tree_int_p4pod
struct Gen_t_00693350_p4pod { int a[1]; };
bool operator==(const Gen_t_00693350_p4pod&, const Gen_t_00693350_p4pod&);
bool operator<(const Gen_t_00693350_p4pod&, const Gen_t_00693350_p4pod&);
typedef _STL::pair<const int, Gen_t_00693350_p4pod > TgPair_tree_int_p4pod_00693350;
template class _STL::_Rb_tree<int, TgPair_tree_int_p4pod_00693350, _STL::_Select1st<TgPair_tree_int_p4pod_00693350 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p4pod_00693350 > >;
// 0x00693480 tree_k4_p12cd
struct Gen_t_00693480_k4 { int a[1]; Gen_t_00693480_k4(); Gen_t_00693480_k4(const Gen_t_00693480_k4&); ~Gen_t_00693480_k4(); Gen_t_00693480_k4& operator=(const Gen_t_00693480_k4&); };
bool operator==(const Gen_t_00693480_k4&, const Gen_t_00693480_k4&);
bool operator<(const Gen_t_00693480_k4&, const Gen_t_00693480_k4&);
struct Gen_t_00693480_p12cd { int a[3]; Gen_t_00693480_p12cd(); Gen_t_00693480_p12cd(const Gen_t_00693480_p12cd&); ~Gen_t_00693480_p12cd(); Gen_t_00693480_p12cd& operator=(const Gen_t_00693480_p12cd&); };
bool operator==(const Gen_t_00693480_p12cd&, const Gen_t_00693480_p12cd&);
bool operator<(const Gen_t_00693480_p12cd&, const Gen_t_00693480_p12cd&);
typedef _STL::pair<const Gen_t_00693480_k4, Gen_t_00693480_p12cd > TgPair_tree_k4_p12cd_00693480;
template class _STL::_Rb_tree<Gen_t_00693480_k4, TgPair_tree_k4_p12cd_00693480, _STL::_Select1st<TgPair_tree_k4_p12cd_00693480 >, _STL::less<Gen_t_00693480_k4 >, _STL::allocator<TgPair_tree_k4_p12cd_00693480 > >;
// 0x00693A30 tree_k4_p12cd
struct Gen_t_00693a30_k4 { int a[1]; Gen_t_00693a30_k4(); Gen_t_00693a30_k4(const Gen_t_00693a30_k4&); ~Gen_t_00693a30_k4(); Gen_t_00693a30_k4& operator=(const Gen_t_00693a30_k4&); };
bool operator==(const Gen_t_00693a30_k4&, const Gen_t_00693a30_k4&);
bool operator<(const Gen_t_00693a30_k4&, const Gen_t_00693a30_k4&);
struct Gen_t_00693a30_p12cd { int a[3]; Gen_t_00693a30_p12cd(); Gen_t_00693a30_p12cd(const Gen_t_00693a30_p12cd&); ~Gen_t_00693a30_p12cd(); Gen_t_00693a30_p12cd& operator=(const Gen_t_00693a30_p12cd&); };
bool operator==(const Gen_t_00693a30_p12cd&, const Gen_t_00693a30_p12cd&);
bool operator<(const Gen_t_00693a30_p12cd&, const Gen_t_00693a30_p12cd&);
typedef _STL::pair<const Gen_t_00693a30_k4, Gen_t_00693a30_p12cd > TgPair_tree_k4_p12cd_00693a30;
template class _STL::_Rb_tree<Gen_t_00693a30_k4, TgPair_tree_k4_p12cd_00693a30, _STL::_Select1st<TgPair_tree_k4_p12cd_00693a30 >, _STL::less<Gen_t_00693a30_k4 >, _STL::allocator<TgPair_tree_k4_p12cd_00693a30 > >;
// 0x0069C240 tree_int_p4pod
struct Gen_t_0069c240_p4pod { int a[1]; };
bool operator==(const Gen_t_0069c240_p4pod&, const Gen_t_0069c240_p4pod&);
bool operator<(const Gen_t_0069c240_p4pod&, const Gen_t_0069c240_p4pod&);
typedef _STL::pair<const int, Gen_t_0069c240_p4pod > TgPair_tree_int_p4pod_0069c240;
template class _STL::_Rb_tree<int, TgPair_tree_int_p4pod_0069c240, _STL::_Select1st<TgPair_tree_int_p4pod_0069c240 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p4pod_0069c240 > >;
