// cl: /EHsc
// stlport
// Generated by: python3 tools/gen_small.py gen-tgrid
// Do not edit by hand; regenerate instead.
//
// Each row this file carries is a retail body that IS this instantiation:
// the game links STLport 4.5.3, so a container member's code is the vendor
// template over a payload of that shape, and the payload's name never
// reaches the bytes. The synthetic payloads below are anonymous by design --
// they reproduce a layout and a lifecycle, never a class identity -- and
// every call target is read out of the retail bytes and pinned in
// targets/game/reverse/symbols.csv, so the bytes prove the callee.

#include <map>
#include <set>

struct Gen_p24pod { int a[6]; };
bool operator==(const Gen_p24pod&, const Gen_p24pod&);
bool operator<(const Gen_p24pod&, const Gen_p24pod&);
struct Gen_p32pod { int a[8]; };
bool operator==(const Gen_p32pod&, const Gen_p32pod&);
bool operator<(const Gen_p32pod&, const Gen_p32pod&);
struct Gen_p4cd { int a[1]; Gen_p4cd(); Gen_p4cd(const Gen_p4cd&); ~Gen_p4cd(); Gen_p4cd& operator=(const Gen_p4cd&); };
bool operator==(const Gen_p4cd&, const Gen_p4cd&);
bool operator<(const Gen_p4cd&, const Gen_p4cd&);
struct Gen_p32cd { int a[8]; Gen_p32cd(); Gen_p32cd(const Gen_p32cd&); ~Gen_p32cd(); Gen_p32cd& operator=(const Gen_p32cd&); };
bool operator==(const Gen_p32cd&, const Gen_p32cd&);
bool operator<(const Gen_p32cd&, const Gen_p32cd&);
struct Gen_k4 { int a[1]; Gen_k4(); Gen_k4(const Gen_k4&); ~Gen_k4(); Gen_k4& operator=(const Gen_k4&); };
bool operator==(const Gen_k4&, const Gen_k4&);
bool operator<(const Gen_k4&, const Gen_k4&);
struct Gen_p8cd { int a[2]; Gen_p8cd(); Gen_p8cd(const Gen_p8cd&); ~Gen_p8cd(); Gen_p8cd& operator=(const Gen_p8cd&); };
bool operator==(const Gen_p8cd&, const Gen_p8cd&);
bool operator<(const Gen_p8cd&, const Gen_p8cd&);
struct Gen_p12cd { int a[3]; Gen_p12cd(); Gen_p12cd(const Gen_p12cd&); ~Gen_p12cd(); Gen_p12cd& operator=(const Gen_p12cd&); };
bool operator==(const Gen_p12cd&, const Gen_p12cd&);
bool operator<(const Gen_p12cd&, const Gen_p12cd&);

typedef _STL::pair<const int, Gen_p24pod > TgPair_tree_int_p24pod;
template class _STL::_Rb_tree<int, TgPair_tree_int_p24pod, _STL::_Select1st<TgPair_tree_int_p24pod >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p24pod > >;
typedef _STL::pair<const int, Gen_p32pod > TgPair_tree_int_p32pod;
template class _STL::_Rb_tree<int, TgPair_tree_int_p32pod, _STL::_Select1st<TgPair_tree_int_p32pod >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p32pod > >;
typedef _STL::pair<const int, Gen_p4cd > TgPair_tree_int_p4cd;
template class _STL::_Rb_tree<int, TgPair_tree_int_p4cd, _STL::_Select1st<TgPair_tree_int_p4cd >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p4cd > >;
typedef _STL::pair<const int, Gen_p32cd > TgPair_tree_int_p32cd;
template class _STL::_Rb_tree<int, TgPair_tree_int_p32cd, _STL::_Select1st<TgPair_tree_int_p32cd >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p32cd > >;
typedef _STL::pair<const Gen_k4, Gen_p24pod > TgPair_tree_k4_p24pod;
template class _STL::_Rb_tree<Gen_k4, TgPair_tree_k4_p24pod, _STL::_Select1st<TgPair_tree_k4_p24pod >, _STL::less<Gen_k4 >, _STL::allocator<TgPair_tree_k4_p24pod > >;
typedef _STL::pair<const Gen_k4, Gen_p32pod > TgPair_tree_k4_p32pod;
template class _STL::_Rb_tree<Gen_k4, TgPair_tree_k4_p32pod, _STL::_Select1st<TgPair_tree_k4_p32pod >, _STL::less<Gen_k4 >, _STL::allocator<TgPair_tree_k4_p32pod > >;
typedef _STL::pair<const Gen_k4, Gen_p4cd > TgPair_tree_k4_p4cd;
template class _STL::_Rb_tree<Gen_k4, TgPair_tree_k4_p4cd, _STL::_Select1st<TgPair_tree_k4_p4cd >, _STL::less<Gen_k4 >, _STL::allocator<TgPair_tree_k4_p4cd > >;
typedef _STL::pair<const Gen_k4, Gen_p32cd > TgPair_tree_k4_p32cd;
template class _STL::_Rb_tree<Gen_k4, TgPair_tree_k4_p32cd, _STL::_Select1st<TgPair_tree_k4_p32cd >, _STL::less<Gen_k4 >, _STL::allocator<TgPair_tree_k4_p32cd > >;
template class _STL::_Rb_tree<int, int, _STL::_Identity<int >, _STL::less<int >, _STL::allocator<int > >;
template class _STL::_Rb_tree<void *, void *, _STL::_Identity<void * >, _STL::less<void * >, _STL::allocator<void * > >;
template class _STL::_Rb_tree<Gen_k4, Gen_k4, _STL::_Identity<Gen_k4 >, _STL::less<Gen_k4 >, _STL::allocator<Gen_k4 > >;
template class _STL::_Rb_tree<Gen_p8cd, Gen_p8cd, _STL::_Identity<Gen_p8cd >, _STL::less<Gen_p8cd >, _STL::allocator<Gen_p8cd > >;
template class _STL::_Rb_tree<Gen_p12cd, Gen_p12cd, _STL::_Identity<Gen_p12cd >, _STL::less<Gen_p12cd >, _STL::allocator<Gen_p12cd > >;
