// cl: /EHsc
// stlport
// Generated by: python3 tools/gen_small.py gen-tgrid
// Do not edit by hand; regenerate instead.
//
// Each row this file carries is a retail body that IS this instantiation:
// the game links STLport 4.5.3, so a container member's code is the vendor
// template over a payload of that shape, and the payload's name never
// reaches the bytes. The synthetic payloads below are anonymous by design --
// they reproduce a layout and a lifecycle, never a class identity -- and
// every call target is read out of the retail bytes and pinned in
// targets/game/reverse/symbols.csv, so the bytes prove the callee.

#include <map>
#include <set>
#include <vector>

// 0x000648F0 tree_int_p24pod
struct Gen_t_000648f0_p24pod { int a[6]; };
bool operator==(const Gen_t_000648f0_p24pod&, const Gen_t_000648f0_p24pod&);
bool operator<(const Gen_t_000648f0_p24pod&, const Gen_t_000648f0_p24pod&);
typedef _STL::pair<const int, Gen_t_000648f0_p24pod > TgPair_tree_int_p24pod_000648f0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p24pod_000648f0, _STL::_Select1st<TgPair_tree_int_p24pod_000648f0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p24pod_000648f0 > >;
// 0x00076A90 set_k4
struct Gen_t_00076a90_k4 { int a[1]; Gen_t_00076a90_k4(); Gen_t_00076a90_k4(const Gen_t_00076a90_k4&); ~Gen_t_00076a90_k4(); Gen_t_00076a90_k4& operator=(const Gen_t_00076a90_k4&); };
bool operator==(const Gen_t_00076a90_k4&, const Gen_t_00076a90_k4&);
bool operator<(const Gen_t_00076a90_k4&, const Gen_t_00076a90_k4&);
template class _STL::_Rb_tree<Gen_t_00076a90_k4, Gen_t_00076a90_k4, _STL::_Identity<Gen_t_00076a90_k4 >, _STL::less<Gen_t_00076a90_k4 >, _STL::allocator<Gen_t_00076a90_k4 > >;
// 0x000EF440 set_k4
struct Gen_t_000ef440_k4 { int a[1]; Gen_t_000ef440_k4(); Gen_t_000ef440_k4(const Gen_t_000ef440_k4&); ~Gen_t_000ef440_k4(); Gen_t_000ef440_k4& operator=(const Gen_t_000ef440_k4&); };
bool operator==(const Gen_t_000ef440_k4&, const Gen_t_000ef440_k4&);
bool operator<(const Gen_t_000ef440_k4&, const Gen_t_000ef440_k4&);
template class _STL::_Rb_tree<Gen_t_000ef440_k4, Gen_t_000ef440_k4, _STL::_Identity<Gen_t_000ef440_k4 >, _STL::less<Gen_t_000ef440_k4 >, _STL::allocator<Gen_t_000ef440_k4 > >;
// 0x00140950 set_k4
struct Gen_t_00140950_k4 { int a[1]; Gen_t_00140950_k4(); Gen_t_00140950_k4(const Gen_t_00140950_k4&); ~Gen_t_00140950_k4(); Gen_t_00140950_k4& operator=(const Gen_t_00140950_k4&); };
bool operator==(const Gen_t_00140950_k4&, const Gen_t_00140950_k4&);
bool operator<(const Gen_t_00140950_k4&, const Gen_t_00140950_k4&);
template class _STL::_Rb_tree<Gen_t_00140950_k4, Gen_t_00140950_k4, _STL::_Identity<Gen_t_00140950_k4 >, _STL::less<Gen_t_00140950_k4 >, _STL::allocator<Gen_t_00140950_k4 > >;
// 0x00195A50 set_k4
struct Gen_t_00195a50_k4 { int a[1]; Gen_t_00195a50_k4(); Gen_t_00195a50_k4(const Gen_t_00195a50_k4&); ~Gen_t_00195a50_k4(); Gen_t_00195a50_k4& operator=(const Gen_t_00195a50_k4&); };
bool operator==(const Gen_t_00195a50_k4&, const Gen_t_00195a50_k4&);
bool operator<(const Gen_t_00195a50_k4&, const Gen_t_00195a50_k4&);
template class _STL::_Rb_tree<Gen_t_00195a50_k4, Gen_t_00195a50_k4, _STL::_Identity<Gen_t_00195a50_k4 >, _STL::less<Gen_t_00195a50_k4 >, _STL::allocator<Gen_t_00195a50_k4 > >;
// 0x00197AE0 set_k4
struct Gen_t_00197ae0_k4 { int a[1]; Gen_t_00197ae0_k4(); Gen_t_00197ae0_k4(const Gen_t_00197ae0_k4&); ~Gen_t_00197ae0_k4(); Gen_t_00197ae0_k4& operator=(const Gen_t_00197ae0_k4&); };
bool operator==(const Gen_t_00197ae0_k4&, const Gen_t_00197ae0_k4&);
bool operator<(const Gen_t_00197ae0_k4&, const Gen_t_00197ae0_k4&);
template class _STL::_Rb_tree<Gen_t_00197ae0_k4, Gen_t_00197ae0_k4, _STL::_Identity<Gen_t_00197ae0_k4 >, _STL::less<Gen_t_00197ae0_k4 >, _STL::allocator<Gen_t_00197ae0_k4 > >;
// 0x001AC070 vec_p48cd
struct Gen_t_001ac070_p48cd { int a[12]; Gen_t_001ac070_p48cd(); Gen_t_001ac070_p48cd(const Gen_t_001ac070_p48cd&); ~Gen_t_001ac070_p48cd(); Gen_t_001ac070_p48cd& operator=(const Gen_t_001ac070_p48cd&); };
bool operator==(const Gen_t_001ac070_p48cd&, const Gen_t_001ac070_p48cd&);
bool operator<(const Gen_t_001ac070_p48cd&, const Gen_t_001ac070_p48cd&);
template class _STL::vector<Gen_t_001ac070_p48cd >;
// 0x001ACEC0 vec_p48cd
struct Gen_t_001acec0_p48cd { int a[12]; Gen_t_001acec0_p48cd(); Gen_t_001acec0_p48cd(const Gen_t_001acec0_p48cd&); ~Gen_t_001acec0_p48cd(); Gen_t_001acec0_p48cd& operator=(const Gen_t_001acec0_p48cd&); };
bool operator==(const Gen_t_001acec0_p48cd&, const Gen_t_001acec0_p48cd&);
bool operator<(const Gen_t_001acec0_p48cd&, const Gen_t_001acec0_p48cd&);
template class _STL::vector<Gen_t_001acec0_p48cd >;
// 0x001B6E60 vec_p40pod
struct Gen_t_001b6e60_p40pod { int a[10]; };
bool operator==(const Gen_t_001b6e60_p40pod&, const Gen_t_001b6e60_p40pod&);
bool operator<(const Gen_t_001b6e60_p40pod&, const Gen_t_001b6e60_p40pod&);
template class _STL::vector<Gen_t_001b6e60_p40pod >;
// 0x002360C0 set_k4
struct Gen_t_002360c0_k4 { int a[1]; Gen_t_002360c0_k4(); Gen_t_002360c0_k4(const Gen_t_002360c0_k4&); ~Gen_t_002360c0_k4(); Gen_t_002360c0_k4& operator=(const Gen_t_002360c0_k4&); };
bool operator==(const Gen_t_002360c0_k4&, const Gen_t_002360c0_k4&);
bool operator<(const Gen_t_002360c0_k4&, const Gen_t_002360c0_k4&);
template class _STL::_Rb_tree<Gen_t_002360c0_k4, Gen_t_002360c0_k4, _STL::_Identity<Gen_t_002360c0_k4 >, _STL::less<Gen_t_002360c0_k4 >, _STL::allocator<Gen_t_002360c0_k4 > >;
// 0x0025BC40 set_k4
struct Gen_t_0025bc40_k4 { int a[1]; Gen_t_0025bc40_k4(); Gen_t_0025bc40_k4(const Gen_t_0025bc40_k4&); ~Gen_t_0025bc40_k4(); Gen_t_0025bc40_k4& operator=(const Gen_t_0025bc40_k4&); };
bool operator==(const Gen_t_0025bc40_k4&, const Gen_t_0025bc40_k4&);
bool operator<(const Gen_t_0025bc40_k4&, const Gen_t_0025bc40_k4&);
template class _STL::_Rb_tree<Gen_t_0025bc40_k4, Gen_t_0025bc40_k4, _STL::_Identity<Gen_t_0025bc40_k4 >, _STL::less<Gen_t_0025bc40_k4 >, _STL::allocator<Gen_t_0025bc40_k4 > >;
// 0x0028DC90 vec_p48pod
struct Gen_t_0028dc90_p48pod { int a[12]; };
bool operator==(const Gen_t_0028dc90_p48pod&, const Gen_t_0028dc90_p48pod&);
bool operator<(const Gen_t_0028dc90_p48pod&, const Gen_t_0028dc90_p48pod&);
template class _STL::vector<Gen_t_0028dc90_p48pod >;
// 0x00296A20 set_k4
struct Gen_t_00296a20_k4 { int a[1]; Gen_t_00296a20_k4(); Gen_t_00296a20_k4(const Gen_t_00296a20_k4&); ~Gen_t_00296a20_k4(); Gen_t_00296a20_k4& operator=(const Gen_t_00296a20_k4&); };
bool operator==(const Gen_t_00296a20_k4&, const Gen_t_00296a20_k4&);
bool operator<(const Gen_t_00296a20_k4&, const Gen_t_00296a20_k4&);
template class _STL::_Rb_tree<Gen_t_00296a20_k4, Gen_t_00296a20_k4, _STL::_Identity<Gen_t_00296a20_k4 >, _STL::less<Gen_t_00296a20_k4 >, _STL::allocator<Gen_t_00296a20_k4 > >;
// 0x0036EA80 set_k4
struct Gen_t_0036ea80_k4 { int a[1]; Gen_t_0036ea80_k4(); Gen_t_0036ea80_k4(const Gen_t_0036ea80_k4&); ~Gen_t_0036ea80_k4(); Gen_t_0036ea80_k4& operator=(const Gen_t_0036ea80_k4&); };
bool operator==(const Gen_t_0036ea80_k4&, const Gen_t_0036ea80_k4&);
bool operator<(const Gen_t_0036ea80_k4&, const Gen_t_0036ea80_k4&);
template class _STL::_Rb_tree<Gen_t_0036ea80_k4, Gen_t_0036ea80_k4, _STL::_Identity<Gen_t_0036ea80_k4 >, _STL::less<Gen_t_0036ea80_k4 >, _STL::allocator<Gen_t_0036ea80_k4 > >;
// 0x003A76B0 vec_p40cd
struct Gen_t_003a76b0_p40cd { int a[10]; Gen_t_003a76b0_p40cd(); Gen_t_003a76b0_p40cd(const Gen_t_003a76b0_p40cd&); ~Gen_t_003a76b0_p40cd(); Gen_t_003a76b0_p40cd& operator=(const Gen_t_003a76b0_p40cd&); };
bool operator==(const Gen_t_003a76b0_p40cd&, const Gen_t_003a76b0_p40cd&);
bool operator<(const Gen_t_003a76b0_p40cd&, const Gen_t_003a76b0_p40cd&);
template class _STL::vector<Gen_t_003a76b0_p40cd >;
// 0x003A7790 vec_p48cd
struct Gen_t_003a7790_p48cd { int a[12]; Gen_t_003a7790_p48cd(); Gen_t_003a7790_p48cd(const Gen_t_003a7790_p48cd&); ~Gen_t_003a7790_p48cd(); Gen_t_003a7790_p48cd& operator=(const Gen_t_003a7790_p48cd&); };
bool operator==(const Gen_t_003a7790_p48cd&, const Gen_t_003a7790_p48cd&);
bool operator<(const Gen_t_003a7790_p48cd&, const Gen_t_003a7790_p48cd&);
template class _STL::vector<Gen_t_003a7790_p48cd >;
// 0x003AEB50 vec_p48cd
struct Gen_t_003aeb50_p48cd { int a[12]; Gen_t_003aeb50_p48cd(); Gen_t_003aeb50_p48cd(const Gen_t_003aeb50_p48cd&); ~Gen_t_003aeb50_p48cd(); Gen_t_003aeb50_p48cd& operator=(const Gen_t_003aeb50_p48cd&); };
bool operator==(const Gen_t_003aeb50_p48cd&, const Gen_t_003aeb50_p48cd&);
bool operator<(const Gen_t_003aeb50_p48cd&, const Gen_t_003aeb50_p48cd&);
template class _STL::vector<Gen_t_003aeb50_p48cd >;
// 0x003B1050 vec_p40cd
struct Gen_t_003b1050_p40cd { int a[10]; Gen_t_003b1050_p40cd(); Gen_t_003b1050_p40cd(const Gen_t_003b1050_p40cd&); ~Gen_t_003b1050_p40cd(); Gen_t_003b1050_p40cd& operator=(const Gen_t_003b1050_p40cd&); };
bool operator==(const Gen_t_003b1050_p40cd&, const Gen_t_003b1050_p40cd&);
bool operator<(const Gen_t_003b1050_p40cd&, const Gen_t_003b1050_p40cd&);
template class _STL::vector<Gen_t_003b1050_p40cd >;
// 0x003B10A0 vec_p48cd
struct Gen_t_003b10a0_p48cd { int a[12]; Gen_t_003b10a0_p48cd(); Gen_t_003b10a0_p48cd(const Gen_t_003b10a0_p48cd&); ~Gen_t_003b10a0_p48cd(); Gen_t_003b10a0_p48cd& operator=(const Gen_t_003b10a0_p48cd&); };
bool operator==(const Gen_t_003b10a0_p48cd&, const Gen_t_003b10a0_p48cd&);
bool operator<(const Gen_t_003b10a0_p48cd&, const Gen_t_003b10a0_p48cd&);
template class _STL::vector<Gen_t_003b10a0_p48cd >;
// 0x003B3360 vec_p48cd
struct Gen_t_003b3360_p48cd { int a[12]; Gen_t_003b3360_p48cd(); Gen_t_003b3360_p48cd(const Gen_t_003b3360_p48cd&); ~Gen_t_003b3360_p48cd(); Gen_t_003b3360_p48cd& operator=(const Gen_t_003b3360_p48cd&); };
bool operator==(const Gen_t_003b3360_p48cd&, const Gen_t_003b3360_p48cd&);
bool operator<(const Gen_t_003b3360_p48cd&, const Gen_t_003b3360_p48cd&);
template class _STL::vector<Gen_t_003b3360_p48cd >;
// 0x003B5310 vec_p40cd
struct Gen_t_003b5310_p40cd { int a[10]; Gen_t_003b5310_p40cd(); Gen_t_003b5310_p40cd(const Gen_t_003b5310_p40cd&); ~Gen_t_003b5310_p40cd(); Gen_t_003b5310_p40cd& operator=(const Gen_t_003b5310_p40cd&); };
bool operator==(const Gen_t_003b5310_p40cd&, const Gen_t_003b5310_p40cd&);
bool operator<(const Gen_t_003b5310_p40cd&, const Gen_t_003b5310_p40cd&);
template class _STL::vector<Gen_t_003b5310_p40cd >;
// 0x003B5480 vec_p48cd
struct Gen_t_003b5480_p48cd { int a[12]; Gen_t_003b5480_p48cd(); Gen_t_003b5480_p48cd(const Gen_t_003b5480_p48cd&); ~Gen_t_003b5480_p48cd(); Gen_t_003b5480_p48cd& operator=(const Gen_t_003b5480_p48cd&); };
bool operator==(const Gen_t_003b5480_p48cd&, const Gen_t_003b5480_p48cd&);
bool operator<(const Gen_t_003b5480_p48cd&, const Gen_t_003b5480_p48cd&);
template class _STL::vector<Gen_t_003b5480_p48cd >;
// 0x003B8F80 set_k4
struct Gen_t_003b8f80_k4 { int a[1]; Gen_t_003b8f80_k4(); Gen_t_003b8f80_k4(const Gen_t_003b8f80_k4&); ~Gen_t_003b8f80_k4(); Gen_t_003b8f80_k4& operator=(const Gen_t_003b8f80_k4&); };
bool operator==(const Gen_t_003b8f80_k4&, const Gen_t_003b8f80_k4&);
bool operator<(const Gen_t_003b8f80_k4&, const Gen_t_003b8f80_k4&);
template class _STL::_Rb_tree<Gen_t_003b8f80_k4, Gen_t_003b8f80_k4, _STL::_Identity<Gen_t_003b8f80_k4 >, _STL::less<Gen_t_003b8f80_k4 >, _STL::allocator<Gen_t_003b8f80_k4 > >;
// 0x004041B0 tree_int_p32pod
struct Gen_t_004041b0_p32pod { int a[8]; };
bool operator==(const Gen_t_004041b0_p32pod&, const Gen_t_004041b0_p32pod&);
bool operator<(const Gen_t_004041b0_p32pod&, const Gen_t_004041b0_p32pod&);
typedef _STL::pair<const int, Gen_t_004041b0_p32pod > TgPair_tree_int_p32pod_004041b0;
template class _STL::_Rb_tree<int, TgPair_tree_int_p32pod_004041b0, _STL::_Select1st<TgPair_tree_int_p32pod_004041b0 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p32pod_004041b0 > >;
// 0x00405B70 tree_int_p32cd
struct Gen_t_00405b70_p32cd { int a[8]; Gen_t_00405b70_p32cd(); Gen_t_00405b70_p32cd(const Gen_t_00405b70_p32cd&); ~Gen_t_00405b70_p32cd(); Gen_t_00405b70_p32cd& operator=(const Gen_t_00405b70_p32cd&); };
bool operator==(const Gen_t_00405b70_p32cd&, const Gen_t_00405b70_p32cd&);
bool operator<(const Gen_t_00405b70_p32cd&, const Gen_t_00405b70_p32cd&);
typedef _STL::pair<const int, Gen_t_00405b70_p32cd > TgPair_tree_int_p32cd_00405b70;
template class _STL::_Rb_tree<int, TgPair_tree_int_p32cd_00405b70, _STL::_Select1st<TgPair_tree_int_p32cd_00405b70 >, _STL::less<int >, _STL::allocator<TgPair_tree_int_p32cd_00405b70 > >;
// 0x004428E0 set_k4
struct Gen_t_004428e0_k4 { int a[1]; Gen_t_004428e0_k4(); Gen_t_004428e0_k4(const Gen_t_004428e0_k4&); ~Gen_t_004428e0_k4(); Gen_t_004428e0_k4& operator=(const Gen_t_004428e0_k4&); };
bool operator==(const Gen_t_004428e0_k4&, const Gen_t_004428e0_k4&);
bool operator<(const Gen_t_004428e0_k4&, const Gen_t_004428e0_k4&);
template class _STL::_Rb_tree<Gen_t_004428e0_k4, Gen_t_004428e0_k4, _STL::_Identity<Gen_t_004428e0_k4 >, _STL::less<Gen_t_004428e0_k4 >, _STL::allocator<Gen_t_004428e0_k4 > >;
// 0x004D4BD0 set_k4
struct Gen_t_004d4bd0_k4 { int a[1]; Gen_t_004d4bd0_k4(); Gen_t_004d4bd0_k4(const Gen_t_004d4bd0_k4&); ~Gen_t_004d4bd0_k4(); Gen_t_004d4bd0_k4& operator=(const Gen_t_004d4bd0_k4&); };
bool operator==(const Gen_t_004d4bd0_k4&, const Gen_t_004d4bd0_k4&);
bool operator<(const Gen_t_004d4bd0_k4&, const Gen_t_004d4bd0_k4&);
template class _STL::_Rb_tree<Gen_t_004d4bd0_k4, Gen_t_004d4bd0_k4, _STL::_Identity<Gen_t_004d4bd0_k4 >, _STL::less<Gen_t_004d4bd0_k4 >, _STL::allocator<Gen_t_004d4bd0_k4 > >;
// 0x00539970 set_k4
struct Gen_t_00539970_k4 { int a[1]; Gen_t_00539970_k4(); Gen_t_00539970_k4(const Gen_t_00539970_k4&); ~Gen_t_00539970_k4(); Gen_t_00539970_k4& operator=(const Gen_t_00539970_k4&); };
bool operator==(const Gen_t_00539970_k4&, const Gen_t_00539970_k4&);
bool operator<(const Gen_t_00539970_k4&, const Gen_t_00539970_k4&);
template class _STL::_Rb_tree<Gen_t_00539970_k4, Gen_t_00539970_k4, _STL::_Identity<Gen_t_00539970_k4 >, _STL::less<Gen_t_00539970_k4 >, _STL::allocator<Gen_t_00539970_k4 > >;
// 0x0062CA70 set_k4
struct Gen_t_0062ca70_k4 { int a[1]; Gen_t_0062ca70_k4(); Gen_t_0062ca70_k4(const Gen_t_0062ca70_k4&); ~Gen_t_0062ca70_k4(); Gen_t_0062ca70_k4& operator=(const Gen_t_0062ca70_k4&); };
bool operator==(const Gen_t_0062ca70_k4&, const Gen_t_0062ca70_k4&);
bool operator<(const Gen_t_0062ca70_k4&, const Gen_t_0062ca70_k4&);
template class _STL::_Rb_tree<Gen_t_0062ca70_k4, Gen_t_0062ca70_k4, _STL::_Identity<Gen_t_0062ca70_k4 >, _STL::less<Gen_t_0062ca70_k4 >, _STL::allocator<Gen_t_0062ca70_k4 > >;
// 0x00632130 set_k4
struct Gen_t_00632130_k4 { int a[1]; Gen_t_00632130_k4(); Gen_t_00632130_k4(const Gen_t_00632130_k4&); ~Gen_t_00632130_k4(); Gen_t_00632130_k4& operator=(const Gen_t_00632130_k4&); };
bool operator==(const Gen_t_00632130_k4&, const Gen_t_00632130_k4&);
bool operator<(const Gen_t_00632130_k4&, const Gen_t_00632130_k4&);
template class _STL::_Rb_tree<Gen_t_00632130_k4, Gen_t_00632130_k4, _STL::_Identity<Gen_t_00632130_k4 >, _STL::less<Gen_t_00632130_k4 >, _STL::allocator<Gen_t_00632130_k4 > >;
// 0x00632F00 set_k4
struct Gen_t_00632f00_k4 { int a[1]; Gen_t_00632f00_k4(); Gen_t_00632f00_k4(const Gen_t_00632f00_k4&); ~Gen_t_00632f00_k4(); Gen_t_00632f00_k4& operator=(const Gen_t_00632f00_k4&); };
bool operator==(const Gen_t_00632f00_k4&, const Gen_t_00632f00_k4&);
bool operator<(const Gen_t_00632f00_k4&, const Gen_t_00632f00_k4&);
template class _STL::_Rb_tree<Gen_t_00632f00_k4, Gen_t_00632f00_k4, _STL::_Identity<Gen_t_00632f00_k4 >, _STL::less<Gen_t_00632f00_k4 >, _STL::allocator<Gen_t_00632f00_k4 > >;
// 0x00667820 set_k4
struct Gen_t_00667820_k4 { int a[1]; Gen_t_00667820_k4(); Gen_t_00667820_k4(const Gen_t_00667820_k4&); ~Gen_t_00667820_k4(); Gen_t_00667820_k4& operator=(const Gen_t_00667820_k4&); };
bool operator==(const Gen_t_00667820_k4&, const Gen_t_00667820_k4&);
bool operator<(const Gen_t_00667820_k4&, const Gen_t_00667820_k4&);
template class _STL::_Rb_tree<Gen_t_00667820_k4, Gen_t_00667820_k4, _STL::_Identity<Gen_t_00667820_k4 >, _STL::less<Gen_t_00667820_k4 >, _STL::allocator<Gen_t_00667820_k4 > >;
// 0x006DE840 set_k4
struct Gen_t_006de840_k4 { int a[1]; Gen_t_006de840_k4(); Gen_t_006de840_k4(const Gen_t_006de840_k4&); ~Gen_t_006de840_k4(); Gen_t_006de840_k4& operator=(const Gen_t_006de840_k4&); };
bool operator==(const Gen_t_006de840_k4&, const Gen_t_006de840_k4&);
bool operator<(const Gen_t_006de840_k4&, const Gen_t_006de840_k4&);
template class _STL::_Rb_tree<Gen_t_006de840_k4, Gen_t_006de840_k4, _STL::_Identity<Gen_t_006de840_k4 >, _STL::less<Gen_t_006de840_k4 >, _STL::allocator<Gen_t_006de840_k4 > >;
// 0x007684F0 set_k4
struct Gen_t_007684f0_k4 { int a[1]; Gen_t_007684f0_k4(); Gen_t_007684f0_k4(const Gen_t_007684f0_k4&); ~Gen_t_007684f0_k4(); Gen_t_007684f0_k4& operator=(const Gen_t_007684f0_k4&); };
bool operator==(const Gen_t_007684f0_k4&, const Gen_t_007684f0_k4&);
bool operator<(const Gen_t_007684f0_k4&, const Gen_t_007684f0_k4&);
template class _STL::_Rb_tree<Gen_t_007684f0_k4, Gen_t_007684f0_k4, _STL::_Identity<Gen_t_007684f0_k4 >, _STL::less<Gen_t_007684f0_k4 >, _STL::allocator<Gen_t_007684f0_k4 > >;
// 0x009EE8E0 set_k4
struct Gen_t_009ee8e0_k4 { int a[1]; Gen_t_009ee8e0_k4(); Gen_t_009ee8e0_k4(const Gen_t_009ee8e0_k4&); ~Gen_t_009ee8e0_k4(); Gen_t_009ee8e0_k4& operator=(const Gen_t_009ee8e0_k4&); };
bool operator==(const Gen_t_009ee8e0_k4&, const Gen_t_009ee8e0_k4&);
bool operator<(const Gen_t_009ee8e0_k4&, const Gen_t_009ee8e0_k4&);
template class _STL::_Rb_tree<Gen_t_009ee8e0_k4, Gen_t_009ee8e0_k4, _STL::_Identity<Gen_t_009ee8e0_k4 >, _STL::less<Gen_t_009ee8e0_k4 >, _STL::allocator<Gen_t_009ee8e0_k4 > >;
