// cl: /DNDEBUG /MD /EHsc
// GetAsciiNetCommandType, RVA 0x00682FF0, 515 bytes.
// BFME command-type names in retail comparison order, adapted from the
// GeneralsMD NetworkUtil.cpp reference. The old packet-decoder identity
// at this address was false: this body returns an AsciiString by value.
// The actual raw command decoder is at RVA 0x0067EE40.
// Live callers 0x0067481B/0x0067486A pass a command enum and hidden string
// result through ILT 0x00039ACC, then format the name with frame/player/ID.
// EA reference: Copyright 2025 Electronic Arts Inc.; GPL-3.0-or-later.
#include <string.h>
template <typename T> class StringBase {
    friend class AsciiString;
public:
    void set(const T *text) { set(text, text ? strlen(text) : 0); }
    void set(const T *text, int length);
private:
    StringBase() : m_data(0) {}
    StringBase(const StringBase &other);
    ~StringBase();
    void *m_data;
};
class AsciiString : private StringBase<char> {
public:
    AsciiString() : StringBase<char>() {}
    AsciiString(const AsciiString &other) : StringBase<char>(other) {}
    ~AsciiString() {}
    using StringBase<char>::set;
};
enum NetCommandType {
    NETCOMMANDTYPE_UNKNOWN = -1,
    NETCOMMANDTYPE_FRAMEINFO = 3,
    NETCOMMANDTYPE_REQUEST_GAMESPY_STATS_AUTHKEY = 5,
    NETCOMMANDTYPE_GAMESPY_STATS_AUTHKEY = 6,
    NETCOMMANDTYPE_GAMECOMMAND = 4,
    NETCOMMANDTYPE_PLAYERLEAVE = 10,
    NETCOMMANDTYPE_INFORMPLAYERLEAVEFRAME = 8,
    NETCOMMANDTYPE_REQUESTFRAMEDATA = 9,
    NETCOMMANDTYPE_REQUESTPLAYERLEAVE = 7,
    NETCOMMANDTYPE_DESTROYPLAYER = 11,
    NETCOMMANDTYPE_ACKBOTH = 0,
    NETCOMMANDTYPE_ACKSTAGE1 = 1,
    NETCOMMANDTYPE_ACKSTAGE2 = 2,
    NETCOMMANDTYPE_KEEPALIVE = 12,
    NETCOMMANDTYPE_DISCONNECTCHAT = 13,
    NETCOMMANDTYPE_CHAT = 14,
    NETCOMMANDTYPE_DISCONNECTKEEPALIVE = 24,
    NETCOMMANDTYPE_DISCONNECTPLAYER = 25,
    NETCOMMANDTYPE_DISCONNECTVOTE = 26,
    NETCOMMANDTYPE_PROGRESS = 15,
    NETCOMMANDTYPE_LOADCOMPLETE = 16,
    NETCOMMANDTYPE_TIMEOUTSTART = 17,
    NETCOMMANDTYPE_WRAPPER = 18,
    NETCOMMANDTYPE_FILE = 19,
    NETCOMMANDTYPE_FILEANNOUNCE = 20,
    NETCOMMANDTYPE_FILEPROGRESS = 21,
    NETCOMMANDTYPE_DISCONNECTFRAME = 27,
    NETCOMMANDTYPE_DISCONNECTSCREENOFF = 28,
};
AsciiString GetAsciiNetCommandType(NetCommandType type)
{
    AsciiString s;
    if (type == NETCOMMANDTYPE_FRAMEINFO) s.set("NETCOMMANDTYPE_FRAMEINFO");
    else if (type == NETCOMMANDTYPE_REQUEST_GAMESPY_STATS_AUTHKEY) s.set("NETCOMMANDTYPE_REQUEST_GAMESPY_STATS_AUTHKEY");
    else if (type == NETCOMMANDTYPE_GAMESPY_STATS_AUTHKEY) s.set("NETCOMMANDTYPE_GAMESPY_STATS_AUTHKEY");
    else if (type == NETCOMMANDTYPE_GAMECOMMAND) s.set("NETCOMMANDTYPE_GAMECOMMAND");
    else if (type == NETCOMMANDTYPE_PLAYERLEAVE) s.set("NETCOMMANDTYPE_PLAYERLEAVE");
    else if (type == NETCOMMANDTYPE_INFORMPLAYERLEAVEFRAME) s.set("NETCOMMANDTYPE_INFORMPLAYERLEAVEFRAME");
    else if (type == NETCOMMANDTYPE_REQUESTFRAMEDATA) s.set("NETCOMMANDTYPE_REQUESTFRAMEDATA");
    else if (type == NETCOMMANDTYPE_REQUESTPLAYERLEAVE) s.set("NETCOMMANDTYPE_REQUESTPLAYERLEAVE");
    else if (type == NETCOMMANDTYPE_DESTROYPLAYER) s.set("NETCOMMANDTYPE_DESTROYPLAYER");
    else if (type == NETCOMMANDTYPE_ACKBOTH) s.set("NETCOMMANDTYPE_ACKBOTH");
    else if (type == NETCOMMANDTYPE_ACKSTAGE1) s.set("NETCOMMANDTYPE_ACKSTAGE1");
    else if (type == NETCOMMANDTYPE_ACKSTAGE2) s.set("NETCOMMANDTYPE_ACKSTAGE2");
    else if (type == NETCOMMANDTYPE_KEEPALIVE) s.set("NETCOMMANDTYPE_KEEPALIVE");
    else if (type == NETCOMMANDTYPE_DISCONNECTCHAT) s.set("NETCOMMANDTYPE_DISCONNECTCHAT");
    else if (type == NETCOMMANDTYPE_CHAT) s.set("NETCOMMANDTYPE_CHAT");
    else if (type == NETCOMMANDTYPE_DISCONNECTKEEPALIVE) s.set("NETCOMMANDTYPE_DISCONNECTKEEPALIVE");
    else if (type == NETCOMMANDTYPE_DISCONNECTPLAYER) s.set("NETCOMMANDTYPE_DISCONNECTPLAYER");
    else if (type == NETCOMMANDTYPE_DISCONNECTVOTE) s.set("NETCOMMANDTYPE_DISCONNECTVOTE");
    else if (type == NETCOMMANDTYPE_PROGRESS) s.set("NETCOMMANDTYPE_PROGRESS");
    else if (type == NETCOMMANDTYPE_LOADCOMPLETE) s.set("NETCOMMANDTYPE_LOADCOMPLETE");
    else if (type == NETCOMMANDTYPE_TIMEOUTSTART) s.set("NETCOMMANDTYPE_TIMEOUTSTART");
    else if (type == NETCOMMANDTYPE_WRAPPER) s.set("NETCOMMANDTYPE_WRAPPER");
    else if (type == NETCOMMANDTYPE_FILE) s.set("NETCOMMANDTYPE_FILE");
    else if (type == NETCOMMANDTYPE_FILEANNOUNCE) s.set("NETCOMMANDTYPE_FILEANNOUNCE");
    else if (type == NETCOMMANDTYPE_FILEPROGRESS) s.set("NETCOMMANDTYPE_FILEPROGRESS");
    else if (type == NETCOMMANDTYPE_DISCONNECTFRAME) s.set("NETCOMMANDTYPE_DISCONNECTFRAME");
    else if (type == NETCOMMANDTYPE_DISCONNECTSCREENOFF) s.set("NETCOMMANDTYPE_DISCONNECTSCREENOFF");
    else s.set("UNKNOWN");
    return s;
}
