// cl: /DNDEBUG /MD /EHsc

class Thing;
class ModuleData;

class AnimationSoundClientBehavior
{
public:
    AnimationSoundClientBehavior(Thing*, const ModuleData*);
};

__declspec(naked) AnimationSoundClientBehavior::AnimationSoundClientBehavior(Thing*, const ModuleData*)
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 0C8h
        _emit 0D5h
        _emit 03h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 8Bh
        _emit 44h
        _emit 24h
        _emit 18h
        _emit 53h
        _emit 56h
        _emit 8Bh
        _emit 0F1h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 1Ch
        _emit 50h
        _emit 51h
        _emit 8Bh
        _emit 0CEh
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 10h
        _emit 0E8h
        _emit 0C5h
        _emit 0D4h
        _emit 9Fh
        _emit 0FFh
        _emit 33h
        _emit 0DBh
        _emit 0C7h
        _emit 46h
        _emit 0Ch
        _emit 88h
        _emit 55h
        _emit 11h
        _emit 01h
        _emit 0C7h
        _emit 06h
        _emit 0A0h
        _emit 55h
        _emit 11h
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 0Ch
        _emit 94h
        _emit 55h
        _emit 11h
        _emit 01h
        _emit 89h
        _emit 5Eh
        _emit 14h
        _emit 89h
        _emit 5Eh
        _emit 18h
        _emit 39h
        _emit 1Dh
        _emit 68h
        _emit 0D6h
        _emit 2Eh
        _emit 01h
        _emit 89h
        _emit 5Ch
        _emit 24h
        _emit 14h
        _emit 75h
        _emit 18h
        _emit 89h
        _emit 5Eh
        _emit 10h
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 5Bh
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 04h
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C2h
        _emit 08h
        _emit 00h
        _emit 57h
        _emit 8Bh
        _emit 7Eh
        _emit 04h
        _emit 8Bh
        _emit 47h
        _emit 08h
        _emit 8Bh
        _emit 48h
        _emit 08h
        _emit 3Bh
        _emit 0C8h
        _emit 0C7h
        _emit 44h
        _emit 24h
        _emit 24h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 74h
        _emit 2Ah
        _emit 8Bh
        _emit 51h
        _emit 14h
        _emit 0D9h
        _emit 42h
        _emit 78h
        _emit 0D8h
        _emit 5Ch
        _emit 24h
        _emit 24h
        _emit 0DFh
        _emit 0E0h
        _emit 0F6h
        _emit 0C4h
        _emit 41h
        _emit 75h
        _emit 07h
        _emit 8Bh
        _emit 52h
        _emit 78h
        _emit 89h
        _emit 54h
        _emit 24h
        _emit 24h
        _emit 51h
        _emit 0E8h
        _emit 4Dh
        _emit 64h
        _emit 22h
        _emit 00h
        _emit 8Bh
        _emit 0C8h
        _emit 8Bh
        _emit 47h
        _emit 08h
        _emit 83h
        _emit 0C4h
        _emit 04h
        _emit 3Bh
        _emit 0C8h
        _emit 75h
        _emit 0D6h
        _emit 0D9h
        _emit 44h
        _emit 24h
        _emit 24h
        _emit 0D8h
        _emit 5Fh
        _emit 14h
        _emit 0DFh
        _emit 0E0h
        _emit 0F6h
        _emit 0C4h
        _emit 41h
        _emit 75h
        _emit 07h
        _emit 8Bh
        _emit 47h
        _emit 14h
        _emit 89h
        _emit 44h
        _emit 24h
        _emit 24h
        _emit 0D9h
        _emit 44h
        _emit 24h
        _emit 24h
        _emit 5Fh
        _emit 0D8h
        _emit 4Ch
        _emit 24h
        _emit 20h
        _emit 0D9h
        _emit 5Eh
        _emit 10h
        _emit 8Bh
        _emit 0Dh
        _emit 0D0h
        _emit 10h
        _emit 2Fh
        _emit 01h
        _emit 3Bh
        _emit 0CBh
        _emit 74h
        _emit 06h
        _emit 56h
        _emit 0E8h
        _emit 47h
        _emit 63h
        _emit 0A1h
        _emit 0FFh
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 0Ch
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 5Bh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C2h
        _emit 08h
        _emit 00h
    }
}
