class BfmeOwnedP;

class BfmeManagerEntryP
{
public:
	void bfmeRemove(BfmeOwnedP *element);

private:
	char m_bfmeHead[0x88];

public:
	BfmeManagerEntryP *m_bfmeNext;
};

class AudioEventRTS;

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/Common/GameAudio.h
class AudioManager
{
public:
	// Only the recovered release slot is named; anchors preserve its retail +0x168 position.
#define BFME_AUDIO_ANCHOR(n) virtual void bfmeAudioAnchor##n();
	BFME_AUDIO_ANCHOR(00) BFME_AUDIO_ANCHOR(01) BFME_AUDIO_ANCHOR(02) BFME_AUDIO_ANCHOR(03) BFME_AUDIO_ANCHOR(04)
	BFME_AUDIO_ANCHOR(05) BFME_AUDIO_ANCHOR(06) BFME_AUDIO_ANCHOR(07) BFME_AUDIO_ANCHOR(08) BFME_AUDIO_ANCHOR(09)
	BFME_AUDIO_ANCHOR(10) BFME_AUDIO_ANCHOR(11) BFME_AUDIO_ANCHOR(12) BFME_AUDIO_ANCHOR(13) BFME_AUDIO_ANCHOR(14)
	BFME_AUDIO_ANCHOR(15) BFME_AUDIO_ANCHOR(16) BFME_AUDIO_ANCHOR(17) BFME_AUDIO_ANCHOR(18) BFME_AUDIO_ANCHOR(19)
	BFME_AUDIO_ANCHOR(20) BFME_AUDIO_ANCHOR(21) BFME_AUDIO_ANCHOR(22) BFME_AUDIO_ANCHOR(23) BFME_AUDIO_ANCHOR(24)
	BFME_AUDIO_ANCHOR(25) BFME_AUDIO_ANCHOR(26) BFME_AUDIO_ANCHOR(27) BFME_AUDIO_ANCHOR(28) BFME_AUDIO_ANCHOR(29)
	BFME_AUDIO_ANCHOR(30) BFME_AUDIO_ANCHOR(31) BFME_AUDIO_ANCHOR(32) BFME_AUDIO_ANCHOR(33) BFME_AUDIO_ANCHOR(34)
	BFME_AUDIO_ANCHOR(35) BFME_AUDIO_ANCHOR(36) BFME_AUDIO_ANCHOR(37) BFME_AUDIO_ANCHOR(38) BFME_AUDIO_ANCHOR(39)
	BFME_AUDIO_ANCHOR(40) BFME_AUDIO_ANCHOR(41) BFME_AUDIO_ANCHOR(42) BFME_AUDIO_ANCHOR(43) BFME_AUDIO_ANCHOR(44)
	BFME_AUDIO_ANCHOR(45) BFME_AUDIO_ANCHOR(46) BFME_AUDIO_ANCHOR(47) BFME_AUDIO_ANCHOR(48) BFME_AUDIO_ANCHOR(49)
	BFME_AUDIO_ANCHOR(50) BFME_AUDIO_ANCHOR(51) BFME_AUDIO_ANCHOR(52) BFME_AUDIO_ANCHOR(53) BFME_AUDIO_ANCHOR(54)
	BFME_AUDIO_ANCHOR(55) BFME_AUDIO_ANCHOR(56) BFME_AUDIO_ANCHOR(57) BFME_AUDIO_ANCHOR(58) BFME_AUDIO_ANCHOR(59)
	BFME_AUDIO_ANCHOR(60) BFME_AUDIO_ANCHOR(61) BFME_AUDIO_ANCHOR(62) BFME_AUDIO_ANCHOR(63) BFME_AUDIO_ANCHOR(64)
	BFME_AUDIO_ANCHOR(65) BFME_AUDIO_ANCHOR(66) BFME_AUDIO_ANCHOR(67) BFME_AUDIO_ANCHOR(68) BFME_AUDIO_ANCHOR(69)
	BFME_AUDIO_ANCHOR(70) BFME_AUDIO_ANCHOR(71) BFME_AUDIO_ANCHOR(72) BFME_AUDIO_ANCHOR(73) BFME_AUDIO_ANCHOR(74)
	BFME_AUDIO_ANCHOR(75) BFME_AUDIO_ANCHOR(76) BFME_AUDIO_ANCHOR(77) BFME_AUDIO_ANCHOR(78) BFME_AUDIO_ANCHOR(79)
	BFME_AUDIO_ANCHOR(80) BFME_AUDIO_ANCHOR(81) BFME_AUDIO_ANCHOR(82) BFME_AUDIO_ANCHOR(83) BFME_AUDIO_ANCHOR(84)
	BFME_AUDIO_ANCHOR(85) BFME_AUDIO_ANCHOR(86) BFME_AUDIO_ANCHOR(87) BFME_AUDIO_ANCHOR(88) BFME_AUDIO_ANCHOR(89)
#undef BFME_AUDIO_ANCHOR
	virtual void releaseAudioEventRTS(AudioEventRTS *event);
};

extern AudioManager *TheAudio;

class BfmeManagerP
{
public:
	void bfmeRemove(BfmeOwnedP *element);

private:
	char m_bfmeHead[0xA8];
	BfmeManagerEntryP *m_bfmeFirst;
};

// ?bfmeRemove@BfmeManagerP@@QAEXPAVBfmeOwnedP@@@Z
void BfmeManagerP::bfmeRemove(BfmeOwnedP *element)
{
	BfmeManagerEntryP *entry = m_bfmeFirst;

	while (entry)
	{
		entry->bfmeRemove(element);
		entry = entry->m_bfmeNext;
	}

	TheAudio->releaseAudioEventRTS((AudioEventRTS *)element);
}
