// cl: /DNDEBUG /DWIN32 /D_WINDOWS /MD /EHsc

class BfmeX1004
{
public:
	#define BFME_VIRTUAL_SLOT(n) virtual void _v##n( void ) = 0
	BFME_VIRTUAL_SLOT(00); BFME_VIRTUAL_SLOT(01); BFME_VIRTUAL_SLOT(02); BFME_VIRTUAL_SLOT(03);
	BFME_VIRTUAL_SLOT(04); BFME_VIRTUAL_SLOT(05); BFME_VIRTUAL_SLOT(06); BFME_VIRTUAL_SLOT(07);
	BFME_VIRTUAL_SLOT(08); BFME_VIRTUAL_SLOT(09); BFME_VIRTUAL_SLOT(10); BFME_VIRTUAL_SLOT(11);
	BFME_VIRTUAL_SLOT(12); BFME_VIRTUAL_SLOT(13); BFME_VIRTUAL_SLOT(14); BFME_VIRTUAL_SLOT(15);
	BFME_VIRTUAL_SLOT(16); BFME_VIRTUAL_SLOT(17); BFME_VIRTUAL_SLOT(18); BFME_VIRTUAL_SLOT(19);
	BFME_VIRTUAL_SLOT(20); BFME_VIRTUAL_SLOT(21); BFME_VIRTUAL_SLOT(22); BFME_VIRTUAL_SLOT(23);
	BFME_VIRTUAL_SLOT(24); BFME_VIRTUAL_SLOT(25); BFME_VIRTUAL_SLOT(26); BFME_VIRTUAL_SLOT(27);
	BFME_VIRTUAL_SLOT(28); BFME_VIRTUAL_SLOT(29); BFME_VIRTUAL_SLOT(30); BFME_VIRTUAL_SLOT(31);
	BFME_VIRTUAL_SLOT(32); BFME_VIRTUAL_SLOT(33); BFME_VIRTUAL_SLOT(34); BFME_VIRTUAL_SLOT(35);
	BFME_VIRTUAL_SLOT(36); BFME_VIRTUAL_SLOT(37); BFME_VIRTUAL_SLOT(38); BFME_VIRTUAL_SLOT(39);
	BFME_VIRTUAL_SLOT(40); BFME_VIRTUAL_SLOT(41); BFME_VIRTUAL_SLOT(42); BFME_VIRTUAL_SLOT(43);
	BFME_VIRTUAL_SLOT(44); BFME_VIRTUAL_SLOT(45); BFME_VIRTUAL_SLOT(46); BFME_VIRTUAL_SLOT(47);
	BFME_VIRTUAL_SLOT(48); BFME_VIRTUAL_SLOT(49); BFME_VIRTUAL_SLOT(50); BFME_VIRTUAL_SLOT(51);
	BFME_VIRTUAL_SLOT(52); BFME_VIRTUAL_SLOT(53); BFME_VIRTUAL_SLOT(54); BFME_VIRTUAL_SLOT(55);
	BFME_VIRTUAL_SLOT(56); BFME_VIRTUAL_SLOT(57); BFME_VIRTUAL_SLOT(58); BFME_VIRTUAL_SLOT(59);
	BFME_VIRTUAL_SLOT(60); BFME_VIRTUAL_SLOT(61); BFME_VIRTUAL_SLOT(62); BFME_VIRTUAL_SLOT(63);
	BFME_VIRTUAL_SLOT(64); BFME_VIRTUAL_SLOT(65); BFME_VIRTUAL_SLOT(66); BFME_VIRTUAL_SLOT(67);
	BFME_VIRTUAL_SLOT(68); BFME_VIRTUAL_SLOT(69); BFME_VIRTUAL_SLOT(70); BFME_VIRTUAL_SLOT(71);
	BFME_VIRTUAL_SLOT(72); BFME_VIRTUAL_SLOT(73); BFME_VIRTUAL_SLOT(74); BFME_VIRTUAL_SLOT(75);
	BFME_VIRTUAL_SLOT(76); BFME_VIRTUAL_SLOT(77); BFME_VIRTUAL_SLOT(78); BFME_VIRTUAL_SLOT(79);
	BFME_VIRTUAL_SLOT(80); BFME_VIRTUAL_SLOT(81); BFME_VIRTUAL_SLOT(82); BFME_VIRTUAL_SLOT(83);
	virtual unsigned int predicate( void *expected ) = 0;
	#undef BFME_VIRTUAL_SLOT
};

class BfmeHold1004
{
public:
	BfmeX1004 *bfmeFind1004( void );
};

class Rva001DCA60NullableInterfaceFilter
{
public:
	bool accepts( BfmeHold1004 *object );

private:
	unsigned char m_unreconstructed_00[8];
	void *m_expected;
	bool m_match;
};

bool Rva001DCA60NullableInterfaceFilter::accepts( BfmeHold1004 *object )
{
	BfmeX1004 *interfaceObject = object->bfmeFind1004();
	if( interfaceObject != 0 )
	{
		if( interfaceObject->predicate( m_expected ) > 0 )
		{
			return m_match;
		}
	}

	return !m_match;
}
