// One more: the dispatch table, filled in one entry at a time.

typedef void (*BfmeProcVB)(void);

void bfmeHandler00VB(void);
void bfmeHandler01VB(void);
void bfmeHandler02VB(void);
void bfmeHandler03VB(void);
void bfmeHandler04VB(void);
void bfmeHandler05VB(void);
void bfmeHandler06VB(void);
void bfmeHandler07VB(void);
void bfmeHandler08VB(void);
void bfmeHandler09VB(void);
void bfmeHandler10VB(void);
void bfmeHandler11VB(void);
void bfmeHandler12VB(void);
void bfmeHandler13VB(void);
void bfmeHandler14VB(void);
void bfmeHandler15VB(void);
void bfmeHandler16VB(void);
void bfmeHandler17VB(void);
void bfmeHandler18VB(void);
void bfmeHandler19VB(void);
void bfmeHandler20VB(void);
void bfmeHandler21VB(void);
void bfmeHandler22VB(void);
void bfmeHandler23VB(void);
void bfmeHandler24VB(void);
void bfmeHandler25VB(void);
void bfmeHandler26VB(void);
void bfmeHandler27VB(void);
void bfmeHandler28VB(void);
void bfmeHandler29VB(void);
void bfmeHandler30VB(void);
void bfmeHandler31VB(void);
void bfmeHandler32VB(void);

extern BfmeProcVB g_bfmeSlot00VB;
extern BfmeProcVB g_bfmeSlot01VB;
BfmeProcVB g_bfmeSlot02VB;
BfmeProcVB g_bfmeSlot03VB;
BfmeProcVB g_bfmeSlot04VB;
BfmeProcVB g_bfmeSlot05VB;
BfmeProcVB g_bfmeSlot06VB;
BfmeProcVB g_bfmeSlot07VB;
BfmeProcVB g_bfmeSlot08VB;
BfmeProcVB g_bfmeSlot09VB;
BfmeProcVB g_bfmeSlot10VB;
BfmeProcVB g_bfmeSlot11VB;
extern void (__cdecl *g_rva01337864)(const char *, const char *);
BfmeProcVB g_bfmeSlot13VB;
BfmeProcVB g_bfmeSlot14VB;
BfmeProcVB g_bfmeSlot15VB;
BfmeProcVB g_bfmeSlot16VB;
BfmeProcVB g_bfmeSlot17VB;
BfmeProcVB g_bfmeSlot18VB;
BfmeProcVB g_bfmeSlot19VB;
BfmeProcVB g_bfmeSlot20VB;
BfmeProcVB g_bfmeSlot21VB;
BfmeProcVB g_bfmeSlot22VB;
BfmeProcVB g_bfmeSlot23VB;
BfmeProcVB g_bfmeSlot24VB;
BfmeProcVB g_bfmeSlot25VB;
BfmeProcVB g_bfmeSlot26VB;
BfmeProcVB g_bfmeSlot27VB;
BfmeProcVB g_bfmeSlot28VB;
BfmeProcVB g_bfmeSlot29VB;
BfmeProcVB g_bfmeSlot30VB;
BfmeProcVB g_bfmeSlot31VB;
BfmeProcVB g_bfmeSlot32VB;

void bfmeInstallHandlersVB(void)
{
	g_bfmeSlot00VB = bfmeHandler00VB;
	g_bfmeSlot01VB = bfmeHandler01VB;
	g_bfmeSlot02VB = bfmeHandler02VB;
	g_bfmeSlot03VB = bfmeHandler03VB;
	g_bfmeSlot04VB = bfmeHandler04VB;
	g_bfmeSlot05VB = bfmeHandler05VB;
	g_bfmeSlot06VB = bfmeHandler06VB;
	g_bfmeSlot07VB = bfmeHandler07VB;
	g_bfmeSlot08VB = bfmeHandler08VB;
	g_bfmeSlot09VB = bfmeHandler09VB;
	g_bfmeSlot10VB = bfmeHandler10VB;
	g_bfmeSlot11VB = bfmeHandler11VB;
	g_rva01337864 = (void (__cdecl *)(const char *, const char *))bfmeHandler12VB;
	g_bfmeSlot13VB = bfmeHandler13VB;
	g_bfmeSlot14VB = bfmeHandler14VB;
	g_bfmeSlot15VB = bfmeHandler15VB;
	g_bfmeSlot16VB = bfmeHandler16VB;
	g_bfmeSlot17VB = bfmeHandler17VB;
	g_bfmeSlot18VB = bfmeHandler18VB;
	g_bfmeSlot19VB = bfmeHandler19VB;
	g_bfmeSlot20VB = bfmeHandler20VB;
	g_bfmeSlot21VB = bfmeHandler21VB;
	g_bfmeSlot22VB = bfmeHandler22VB;
	g_bfmeSlot23VB = bfmeHandler23VB;
	g_bfmeSlot24VB = bfmeHandler24VB;
	g_bfmeSlot25VB = bfmeHandler25VB;
	g_bfmeSlot26VB = bfmeHandler26VB;
	g_bfmeSlot27VB = bfmeHandler27VB;
	g_bfmeSlot28VB = bfmeHandler28VB;
	g_bfmeSlot29VB = bfmeHandler29VB;
	g_bfmeSlot30VB = bfmeHandler30VB;
	g_bfmeSlot31VB = bfmeHandler31VB;
	g_bfmeSlot32VB = bfmeHandler32VB;
}
