// Exact 501-byte retail unit at RVA 0x002C1061.
extern "C" __declspec(naked) void bfme_AIAttackMoveStateMachineCtor_2C1061()
{
    __asm {
        __emit 0x8B
        __emit 0x56
        __emit 0x48
        __emit 0x8B
        __emit 0x0D
        __emit 0x10
        __emit 0xD8
        __emit 0x2E
        __emit 0x01
        __emit 0x52
        __emit 0x8B
        __emit 0xD8
        __emit 0xE8
        __emit 0xBC
        __emit 0x3B
        __emit 0xD8
        __emit 0xFF
        __emit 0x85
        __emit 0xDB
        __emit 0x75
        __emit 0x4E
        __emit 0x85
        __emit 0xC0
        __emit 0x74
        __emit 0x7B
        __emit 0x8D
        __emit 0x4C
        __emit 0x24
        __emit 0x10
        __emit 0x51
        __emit 0x8B
        __emit 0xC8
        __emit 0xE8
        __emit 0x78
        __emit 0x31
        __emit 0xD6
        __emit 0xFF
        __emit 0x8B
        __emit 0x54
        __emit 0x24
        __emit 0x18
        __emit 0x8B
        __emit 0x74
        __emit 0x24
        __emit 0x14
        __emit 0x8B
        __emit 0x5C
        __emit 0x24
        __emit 0x10
        __emit 0xD9
        __emit 0x47
        __emit 0x28
        __emit 0x8D
        __emit 0x4F
        __emit 0x28
        __emit 0xD8
        __emit 0x64
        __emit 0x24
        __emit 0x10
        __emit 0xD9
        __emit 0xC0
        __emit 0xD8
        __emit 0xC9
        __emit 0xD8
        __emit 0x1D
        __emit 0x18
        __emit 0x64
        __emit 0x09
        __emit 0x01
        __emit 0xDF
        __emit 0xE0
        __emit 0xDD
        __emit 0xD8
        __emit 0xF6
        __emit 0xC4
        __emit 0x41
        __emit 0x75
        __emit 0x2C
        __emit 0x89
        __emit 0x19
        __emit 0x5B
        __emit 0x89
        __emit 0x71
        __emit 0x04
        __emit 0x5E
        __emit 0x5F
        __emit 0x89
        __emit 0x51
        __emit 0x08
        __emit 0xB8
        __emit 0xFE
        __emit 0xFF
        __emit 0xFF
        __emit 0xFF
        __emit 0x5D
        __emit 0x83
        __emit 0xC4
        __emit 0x0C
        __emit 0xC3
        __emit 0x83
        __emit 0xC3
        __emit 0x38
        __emit 0x8B
        __emit 0xC3
        __emit 0x8B
        __emit 0x18
        __emit 0x8B
        __emit 0x70
        __emit 0x04
        __emit 0x8B
        __emit 0x50
        __emit 0x08
        __emit 0x89
        __emit 0x5C
        __emit 0x24
        __emit 0x10
        __emit 0x89
        __emit 0x74
        __emit 0x24
        __emit 0x14
        __emit 0xEB
        __emit 0xB7
        __emit 0xD9
        __emit 0x47
        __emit 0x2C
        __emit 0xD8
        __emit 0x64
        __emit 0x24
        __emit 0x14
        __emit 0xD9
        __emit 0xC0
        __emit 0xD8
        __emit 0xC9
        __emit 0xD8
        __emit 0x1D
        __emit 0x18
        __emit 0x64
        __emit 0x09
        __emit 0x01
        __emit 0xDF
        __emit 0xE0
        __emit 0xDD
        __emit 0xD8
        __emit 0xF6
        __emit 0xC4
        __emit 0x41
        __emit 0x74
        __emit 0xBA
        __emit 0x8B
        __emit 0x47
        __emit 0x24
        __emit 0x5B
        __emit 0x5E
        __emit 0x5F
        __emit 0x2B
        __emit 0xC5
        __emit 0x5D
        __emit 0x83
        __emit 0xC4
        __emit 0x0C
        __emit 0xC3
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0x51
        __emit 0x56
        __emit 0x51
        __emit 0x8B
        __emit 0xF1
        __emit 0x89
        __emit 0x64
        __emit 0x24
        __emit 0x08
        __emit 0x8B
        __emit 0xCC
        __emit 0x68
        __emit 0x28
        __emit 0x61
        __emit 0x09
        __emit 0x01
        __emit 0xE8
        __emit 0x5B
        __emit 0x7A
        __emit 0x5C
        __emit 0x00
        __emit 0x8B
        __emit 0x44
        __emit 0x24
        __emit 0x10
        __emit 0x50
        __emit 0x8B
        __emit 0xCE
        __emit 0xE8
        __emit 0x11
        __emit 0x10
        __emit 0xD7
        __emit 0xFF
        __emit 0xC7
        __emit 0x46
        __emit 0x50
        __emit 0x00
        __emit 0x00
        __emit 0x00
        __emit 0x00
        __emit 0xC7
        __emit 0x06
        __emit 0x30
        __emit 0x7D
        __emit 0x0C
        __emit 0x01
        __emit 0x8B
        __emit 0xC6
        __emit 0x5E
        __emit 0x59
        __emit 0xC2
        __emit 0x04
        __emit 0x00
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0x56
        __emit 0x8B
        __emit 0xF1
        __emit 0xE8
        __emit 0xF7
        __emit 0xD0
        __emit 0xD5
        __emit 0xFF
        __emit 0xF6
        __emit 0x44
        __emit 0x24
        __emit 0x08
        __emit 0x01
        __emit 0x74
        __emit 0x09
        __emit 0x56
        __emit 0xE8
        __emit 0xFB
        __emit 0x0C
        __emit 0x5C
        __emit 0x00
        __emit 0x83
        __emit 0xC4
        __emit 0x04
        __emit 0x8B
        __emit 0xC6
        __emit 0x5E
        __emit 0xC2
        __emit 0x04
        __emit 0x00
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xE9
        __emit 0x22
        __emit 0x99
        __emit 0xD8
        __emit 0xFF
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0x51
        __emit 0x56
        __emit 0x51
        __emit 0x8B
        __emit 0xF1
        __emit 0x89
        __emit 0x64
        __emit 0x24
        __emit 0x08
        __emit 0x8B
        __emit 0xCC
        __emit 0x68
        __emit 0xDC
        __emit 0x7D
        __emit 0x0C
        __emit 0x01
        __emit 0xE8
        __emit 0xCB
        __emit 0x79
        __emit 0x5C
        __emit 0x00
        __emit 0x8B
        __emit 0x44
        __emit 0x24
        __emit 0x10
        __emit 0x50
        __emit 0x8B
        __emit 0xCE
        __emit 0xE8
        __emit 0xB1
        __emit 0x23
        __emit 0xD4
        __emit 0xFF
        __emit 0x33
        __emit 0xC0
        __emit 0xC7
        __emit 0x06
        __emit 0x88
        __emit 0x7D
        __emit 0x0C
        __emit 0x01
        __emit 0x89
        __emit 0x46
        __emit 0x28
        __emit 0x89
        __emit 0x46
        __emit 0x38
        __emit 0x89
        __emit 0x46
        __emit 0x3C
        __emit 0xC7
        __emit 0x46
        __emit 0x24
        __emit 0xD4
        __emit 0x74
        __emit 0x0C
        __emit 0x01
        __emit 0x89
        __emit 0x46
        __emit 0x2C
        __emit 0x89
        __emit 0x46
        __emit 0x30
        __emit 0x89
        __emit 0x46
        __emit 0x34
        __emit 0x88
        __emit 0x46
        __emit 0x44
        __emit 0x89
        __emit 0x46
        __emit 0x40
        __emit 0x8B
        __emit 0xC6
        __emit 0x5E
        __emit 0x59
        __emit 0xC2
        __emit 0x04
        __emit 0x00
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xCC
        __emit 0xB8
        __emit 0xDC
        __emit 0x7D
        __emit 0x0C
        __emit 0x01
        __emit 0xC3
    }
}
