// cl: /DNDEBUG /MD /EHsc

class Thing;
class ModuleData;

class AttributeModifierAuraUpdate
{
public:
    AttributeModifierAuraUpdate(Thing*, const ModuleData*);
};

__declspec(naked) AttributeModifierAuraUpdate::AttributeModifierAuraUpdate(Thing*, const ModuleData*)
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 58h
        _emit 08h
        _emit 01h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 8Bh
        _emit 44h
        _emit 24h
        _emit 18h
        _emit 56h
        _emit 57h
        _emit 8Bh
        _emit 0F1h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 1Ch
        _emit 50h
        _emit 51h
        _emit 8Bh
        _emit 0CEh
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 10h
        _emit 0E8h
        _emit 0E5h
        _emit 6Fh
        _emit 0D9h
        _emit 0FFh
        _emit 0C7h
        _emit 46h
        _emit 0Ch
        _emit 0D0h
        _emit 0C9h
        _emit 09h
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 10h
        _emit 0A0h
        _emit 0CBh
        _emit 09h
        _emit 01h
        _emit 83h
        _emit 0C8h
        _emit 0FFh
        _emit 0C7h
        _emit 06h
        _emit 94h
        _emit 0CDh
        _emit 09h
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 0Ch
        _emit 0D0h
        _emit 0CCh
        _emit 09h
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 10h
        _emit 0ACh
        _emit 0CBh
        _emit 09h
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 14h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 46h
        _emit 18h
        _emit 89h
        _emit 46h
        _emit 1Ch
        _emit 8Dh
        _emit 7Eh
        _emit 20h
        _emit 8Bh
        _emit 0CFh
        _emit 0C7h
        _emit 44h
        _emit 24h
        _emit 14h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 0E8h
        _emit 0Bh
        _emit 0D1h
        _emit 0DBh
        _emit 0FFh
        _emit 8Bh
        _emit 56h
        _emit 08h
        _emit 6Ah
        _emit 01h
        _emit 52h
        _emit 8Bh
        _emit 0CEh
        _emit 0C7h
        _emit 06h
        _emit 74h
        _emit 0B0h
        _emit 0Bh
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 0Ch
        _emit 0B0h
        _emit 0AFh
        _emit 0Bh
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 10h
        _emit 0A0h
        _emit 0AFh
        _emit 0Bh
        _emit 01h
        _emit 0C7h
        _emit 07h
        _emit 08h
        _emit 0ADh
        _emit 0Bh
        _emit 01h
        _emit 0E8h
        _emit 70h
        _emit 56h
        _emit 0D9h
        _emit 0FFh
        _emit 8Bh
        _emit 46h
        _emit 04h
        _emit 8Ah
        _emit 88h
        _emit 90h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 84h
        _emit 0C9h
        _emit 74h
        _emit 1Eh
        _emit 8Bh
        _emit 17h
        _emit 8Bh
        _emit 0CFh
        _emit 0FFh
        _emit 52h
        _emit 2Ch
        _emit 8Bh
        _emit 07h
        _emit 8Bh
        _emit 0CFh
        _emit 0FFh
        _emit 50h
        _emit 34h
        _emit 8Bh
        _emit 17h
        _emit 8Bh
        _emit 0CFh
        _emit 0FFh
        _emit 52h
        _emit 24h
        _emit 8Bh
        _emit 07h
        _emit 6Ah
        _emit 01h
        _emit 8Bh
        _emit 0CFh
        _emit 0FFh
        _emit 50h
        _emit 20h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 0Ch
        _emit 5Fh
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C2h
        _emit 08h
        _emit 00h
    }
}
