// cl: /DNDEBUG /MD /EHsc

class PartTheHeavensUpdateModuleData
{
public:
    PartTheHeavensUpdateModuleData();
};

__declspec(naked) PartTheHeavensUpdateModuleData::PartTheHeavensUpdateModuleData()
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 44h
        _emit 21h
        _emit 01h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 53h
        _emit 55h
        _emit 56h
        _emit 8Bh
        _emit 0E9h
        _emit 57h
        _emit 89h
        _emit 6Ch
        _emit 24h
        _emit 10h
        _emit 33h
        _emit 0F6h
        _emit 0C7h
        _emit 45h
        _emit 00h
        _emit 0A8h
        _emit 08h
        _emit 0Ch
        _emit 01h
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 1Ch
        _emit 89h
        _emit 75h
        _emit 08h
        _emit 8Dh
        _emit 4Dh
        _emit 10h
        _emit 89h
        _emit 75h
        _emit 0Ch
        _emit 89h
        _emit 31h
        _emit 89h
        _emit 71h
        _emit 04h
        _emit 89h
        _emit 71h
        _emit 08h
        _emit 89h
        _emit 71h
        _emit 0Ch
        _emit 89h
        _emit 71h
        _emit 10h
        _emit 8Bh
        _emit 41h
        _emit 0Ch
        _emit 89h
        _emit 41h
        _emit 18h
        _emit 89h
        _emit 71h
        _emit 28h
        _emit 89h
        _emit 71h
        _emit 24h
        _emit 89h
        _emit 71h
        _emit 20h
        _emit 89h
        _emit 71h
        _emit 1Ch
        _emit 8Dh
        _emit 7Dh
        _emit 3Ch
        _emit 89h
        _emit 37h
        _emit 89h
        _emit 77h
        _emit 04h
        _emit 89h
        _emit 77h
        _emit 08h
        _emit 89h
        _emit 77h
        _emit 0Ch
        _emit 89h
        _emit 77h
        _emit 10h
        _emit 8Bh
        _emit 47h
        _emit 0Ch
        _emit 89h
        _emit 47h
        _emit 18h
        _emit 89h
        _emit 77h
        _emit 28h
        _emit 89h
        _emit 77h
        _emit 24h
        _emit 89h
        _emit 77h
        _emit 20h
        _emit 89h
        _emit 77h
        _emit 1Ch
        _emit 8Dh
        _emit 5Dh
        _emit 68h
        _emit 89h
        _emit 33h
        _emit 89h
        _emit 73h
        _emit 04h
        _emit 89h
        _emit 73h
        _emit 08h
        _emit 89h
        _emit 73h
        _emit 0Ch
        _emit 89h
        _emit 73h
        _emit 10h
        _emit 8Bh
        _emit 43h
        _emit 0Ch
        _emit 89h
        _emit 43h
        _emit 18h
        _emit 89h
        _emit 73h
        _emit 28h
        _emit 89h
        _emit 73h
        _emit 24h
        _emit 89h
        _emit 73h
        _emit 20h
        _emit 89h
        _emit 73h
        _emit 1Ch
        _emit 56h
        _emit 56h
        _emit 56h
        _emit 56h
        _emit 0C6h
        _emit 44h
        _emit 24h
        _emit 2Ch
        _emit 04h
        _emit 0E8h
        _emit 0E3h
        _emit 8Fh
        _emit 0D9h
        _emit 0FFh
        _emit 56h
        _emit 56h
        _emit 68h
        _emit 00h
        _emit 00h
        _emit 80h
        _emit 3Fh
        _emit 56h
        _emit 8Bh
        _emit 0CFh
        _emit 0E8h
        _emit 0D4h
        _emit 8Fh
        _emit 0D9h
        _emit 0FFh
        _emit 56h
        _emit 56h
        _emit 56h
        _emit 56h
        _emit 8Bh
        _emit 0CBh
        _emit 0E8h
        _emit 0C9h
        _emit 8Fh
        _emit 0D9h
        _emit 0FFh
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 14h
        _emit 5Fh
        _emit 5Eh
        _emit 8Bh
        _emit 0C5h
        _emit 5Dh
        _emit 5Bh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C3h
    }
}
