// cl: /DNDEBUG /MD /EHsc

class RubbleRiseUpdateModuleData
{
public:
    RubbleRiseUpdateModuleData();
};

__declspec(naked) RubbleRiseUpdateModuleData::RubbleRiseUpdateModuleData()
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 0Eh
        _emit 1Ch
        _emit 00h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 53h
        _emit 56h
        _emit 8Bh
        _emit 0F1h
        _emit 57h
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 0Ch
        _emit 33h
        _emit 0FFh
        _emit 8Dh
        _emit 4Eh
        _emit 08h
        _emit 89h
        _emit 7Ch
        _emit 24h
        _emit 18h
        _emit 0C7h
        _emit 06h
        _emit 0F8h
        _emit 0EAh
        _emit 08h
        _emit 01h
        _emit 0E8h
        _emit 0E1h
        _emit 0F6h
        _emit 0EDh
        _emit 0FFh
        _emit 68h
        _emit 3Bh
        _emit 2Dh
        _emit 42h
        _emit 00h
        _emit 68h
        _emit 0B1h
        _emit 7Dh
        _emit 44h
        _emit 00h
        _emit 6Ah
        _emit 04h
        _emit 6Ah
        _emit 0Ch
        _emit 8Dh
        _emit 46h
        _emit 54h
        _emit 50h
        _emit 0E8h
        _emit 0CAh
        _emit 0F3h
        _emit 8Ch
        _emit 00h
        _emit 68h
        _emit 77h
        _emit 74h
        _emit 41h
        _emit 00h
        _emit 68h
        _emit 5Ch
        _emit 47h
        _emit 43h
        _emit 00h
        _emit 6Ah
        _emit 04h
        _emit 6Ah
        _emit 0Ch
        _emit 8Dh
        _emit 8Eh
        _emit 84h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 0BBh
        _emit 01h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 88h
        _emit 5Ch
        _emit 24h
        _emit 2Ch
        _emit 0E8h
        _emit 0A7h
        _emit 0F3h
        _emit 8Ch
        _emit 00h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 10h
        _emit 89h
        _emit 7Eh
        _emit 34h
        _emit 89h
        _emit 7Eh
        _emit 38h
        _emit 89h
        _emit 7Eh
        _emit 50h
        _emit 89h
        _emit 7Eh
        _emit 48h
        _emit 89h
        _emit 7Eh
        _emit 4Ch
        _emit 89h
        _emit 7Eh
        _emit 44h
        _emit 0C7h
        _emit 46h
        _emit 3Ch
        _emit 0Fh
        _emit 27h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 9Eh
        _emit 0B4h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 9Eh
        _emit 0C4h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 9Eh
        _emit 0B8h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 9Eh
        _emit 0C8h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 9Eh
        _emit 0BCh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 9Eh
        _emit 0CCh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 9Eh
        _emit 0C0h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 9Eh
        _emit 0D0h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 5Fh
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 5Bh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C3h
    }
}

