// ?bfmeRunJL@BfmeSelfJL@@QAEHXZ
// cl: /DNDEBUG /DWIN32 /MD /D_STLP_USE_STATIC_LIB
// stlport

#define _STLP_NO_EXCEPTIONS 1
#include <bitset>

#define DECLARE_BFME_JL_SLOT(n) virtual void bfmeSlot920D##n();
class BfmeArgJL
{
public:
	enum _dummy_kInit { kInit };
	BfmeArgJL() {}
	BfmeArgJL(_dummy_kInit, int index) { m_bits.set(index); }

private:
	_STL::bitset<320> m_bits;
};

class Rva001CF980Result
{
public:
	DECLARE_BFME_JL_SLOT(0) DECLARE_BFME_JL_SLOT(1) DECLARE_BFME_JL_SLOT(2) DECLARE_BFME_JL_SLOT(3) DECLARE_BFME_JL_SLOT(4) DECLARE_BFME_JL_SLOT(5) DECLARE_BFME_JL_SLOT(6) DECLARE_BFME_JL_SLOT(7) DECLARE_BFME_JL_SLOT(8) DECLARE_BFME_JL_SLOT(9)
	DECLARE_BFME_JL_SLOT(10) DECLARE_BFME_JL_SLOT(11) DECLARE_BFME_JL_SLOT(12) DECLARE_BFME_JL_SLOT(13) DECLARE_BFME_JL_SLOT(14) DECLARE_BFME_JL_SLOT(15) DECLARE_BFME_JL_SLOT(16) DECLARE_BFME_JL_SLOT(17) DECLARE_BFME_JL_SLOT(18) DECLARE_BFME_JL_SLOT(19)
	DECLARE_BFME_JL_SLOT(20) DECLARE_BFME_JL_SLOT(21) DECLARE_BFME_JL_SLOT(22) DECLARE_BFME_JL_SLOT(23) DECLARE_BFME_JL_SLOT(24) DECLARE_BFME_JL_SLOT(25) DECLARE_BFME_JL_SLOT(26) DECLARE_BFME_JL_SLOT(27) DECLARE_BFME_JL_SLOT(28) DECLARE_BFME_JL_SLOT(29)
	DECLARE_BFME_JL_SLOT(30) DECLARE_BFME_JL_SLOT(31) DECLARE_BFME_JL_SLOT(32) DECLARE_BFME_JL_SLOT(33) DECLARE_BFME_JL_SLOT(34) DECLARE_BFME_JL_SLOT(35) DECLARE_BFME_JL_SLOT(36) DECLARE_BFME_JL_SLOT(37) DECLARE_BFME_JL_SLOT(38) DECLARE_BFME_JL_SLOT(39)
	DECLARE_BFME_JL_SLOT(40) DECLARE_BFME_JL_SLOT(41) DECLARE_BFME_JL_SLOT(42) DECLARE_BFME_JL_SLOT(43) DECLARE_BFME_JL_SLOT(44) DECLARE_BFME_JL_SLOT(45) DECLARE_BFME_JL_SLOT(46) DECLARE_BFME_JL_SLOT(47) DECLARE_BFME_JL_SLOT(48) DECLARE_BFME_JL_SLOT(49)
	DECLARE_BFME_JL_SLOT(50) DECLARE_BFME_JL_SLOT(51) DECLARE_BFME_JL_SLOT(52) DECLARE_BFME_JL_SLOT(53) DECLARE_BFME_JL_SLOT(54) DECLARE_BFME_JL_SLOT(55) DECLARE_BFME_JL_SLOT(56) DECLARE_BFME_JL_SLOT(57) DECLARE_BFME_JL_SLOT(58) DECLARE_BFME_JL_SLOT(59)
	DECLARE_BFME_JL_SLOT(60) DECLARE_BFME_JL_SLOT(61) DECLARE_BFME_JL_SLOT(62) DECLARE_BFME_JL_SLOT(63) DECLARE_BFME_JL_SLOT(64) DECLARE_BFME_JL_SLOT(65) DECLARE_BFME_JL_SLOT(66) DECLARE_BFME_JL_SLOT(67) DECLARE_BFME_JL_SLOT(68) DECLARE_BFME_JL_SLOT(69)
	DECLARE_BFME_JL_SLOT(70) DECLARE_BFME_JL_SLOT(71) DECLARE_BFME_JL_SLOT(72) DECLARE_BFME_JL_SLOT(73) DECLARE_BFME_JL_SLOT(74) DECLARE_BFME_JL_SLOT(75) DECLARE_BFME_JL_SLOT(76) DECLARE_BFME_JL_SLOT(77) DECLARE_BFME_JL_SLOT(78) DECLARE_BFME_JL_SLOT(79)
	DECLARE_BFME_JL_SLOT(80) DECLARE_BFME_JL_SLOT(81) DECLARE_BFME_JL_SLOT(82) DECLARE_BFME_JL_SLOT(83) DECLARE_BFME_JL_SLOT(84) DECLARE_BFME_JL_SLOT(85) DECLARE_BFME_JL_SLOT(86) DECLARE_BFME_JL_SLOT(87) DECLARE_BFME_JL_SLOT(88) DECLARE_BFME_JL_SLOT(89)
	DECLARE_BFME_JL_SLOT(90) DECLARE_BFME_JL_SLOT(91) DECLARE_BFME_JL_SLOT(92) DECLARE_BFME_JL_SLOT(93)
	virtual void bfmeSlot920D94(int a, int b, BfmeArgJL x, BfmeArgJL y);
};

#undef DECLARE_BFME_JL_SLOT

#define OBJECT_TU_MEMBERS Rva001CF980Result *queryAt001CF980();
#include "../Object/Object.h"
#undef OBJECT_TU_MEMBERS

class BfmeOwnJL
{
public:
	unsigned char m_bfmeHeadJL[0x10];
	Object *m_bfme10JL;
};

class BfmeSelfJL
{
public:
	int bfmeRunJL();

	unsigned char m_bfmeHeadJL[0x1c];
	BfmeOwnJL *m_bfme1cJL;
};

int BfmeSelfJL::bfmeRunJL()
{
	BfmeOwnJL *a = m_bfme1cJL;
	Object *sub = a->m_bfme10JL;

	if (sub == 0)
		return -2;

	Rva001CF980Result *target = sub->queryAt001CF980();
	if (target == 0)
		return -2;

	BfmeArgJL s1(BfmeArgJL::kInit, 280);
	BfmeArgJL s2(BfmeArgJL::kInit, 279);

	target->bfmeSlot920D94(0x32, 0x3c, s2, s1);
	return 0;
}
