// cl: /DNDEBUG /MD /EHsc

class ClearanceTestingSlowDeathBehaviorModuleData
{
public:
    ClearanceTestingSlowDeathBehaviorModuleData();
};

__declspec(naked) ClearanceTestingSlowDeathBehaviorModuleData::ClearanceTestingSlowDeathBehaviorModuleData()
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 0D8h
        _emit 0AEh
        _emit 00h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 56h
        _emit 8Bh
        _emit 0F1h
        _emit 57h
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 08h
        _emit 0E8h
        _emit 0E7h
        _emit 03h
        _emit 0E1h
        _emit 0FFh
        _emit 68h
        _emit 00h
        _emit 00h
        _emit 80h
        _emit 3Fh
        _emit 68h
        _emit 00h
        _emit 00h
        _emit 80h
        _emit 3Fh
        _emit 33h
        _emit 0FFh
        _emit 68h
        _emit 00h
        _emit 00h
        _emit 80h
        _emit 3Fh
        _emit 57h
        _emit 57h
        _emit 8Dh
        _emit 8Eh
        _emit 0A8h
        _emit 01h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 7Ch
        _emit 24h
        _emit 28h
        _emit 0C7h
        _emit 06h
        _emit 28h
        _emit 31h
        _emit 0Ah
        _emit 01h
        _emit 0E8h
        _emit 53h
        _emit 08h
        _emit 0E4h
        _emit 0FFh
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 0Ch
        _emit 89h
        _emit 0BEh
        _emit 04h
        _emit 02h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 0BEh
        _emit 08h
        _emit 02h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 0BEh
        _emit 0Ch
        _emit 02h
        _emit 00h
        _emit 00h
        _emit 0B8h
        _emit 0CDh
        _emit 0CCh
        _emit 8Ch
        _emit 3Fh
        _emit 89h
        _emit 86h
        _emit 14h
        _emit 02h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 86h
        _emit 1Ch
        _emit 02h
        _emit 00h
        _emit 00h
        _emit 0C7h
        _emit 86h
        _emit 10h
        _emit 02h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 0A0h
        _emit 41h
        _emit 0C7h
        _emit 86h
        _emit 18h
        _emit 02h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 0A0h
        _emit 0C1h
        _emit 5Fh
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C3h
    }
}
