// cl: /DNDEBUG /MD /EHsc

class Thing;
class ModuleData;

class BezierProjectileBehavior
{
public:
    BezierProjectileBehavior(Thing*, const ModuleData*);
};

__declspec(naked) BezierProjectileBehavior::BezierProjectileBehavior(Thing*, const ModuleData*)
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 8Eh
        _emit 0A9h
        _emit 00h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 8Bh
        _emit 44h
        _emit 24h
        _emit 18h
        _emit 53h
        _emit 56h
        _emit 8Bh
        _emit 0F1h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 1Ch
        _emit 50h
        _emit 51h
        _emit 8Bh
        _emit 0CEh
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 10h
        _emit 0E8h
        _emit 45h
        _emit 5Ch
        _emit 0E2h
        _emit 0FFh
        _emit 0C7h
        _emit 46h
        _emit 0Ch
        _emit 0D0h
        _emit 0C9h
        _emit 09h
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 10h
        _emit 0A0h
        _emit 0CBh
        _emit 09h
        _emit 01h
        _emit 83h
        _emit 0C8h
        _emit 0FFh
        _emit 33h
        _emit 0DBh
        _emit 89h
        _emit 5Eh
        _emit 14h
        _emit 89h
        _emit 46h
        _emit 18h
        _emit 89h
        _emit 46h
        _emit 1Ch
        _emit 0C7h
        _emit 46h
        _emit 20h
        _emit 00h
        _emit 1Eh
        _emit 0Ah
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 24h
        _emit 0E4h
        _emit 1Dh
        _emit 0Ah
        _emit 01h
        _emit 0C7h
        _emit 06h
        _emit 3Ch
        _emit 25h
        _emit 0Ah
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 0Ch
        _emit 78h
        _emit 24h
        _emit 0Ah
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 10h
        _emit 6Ch
        _emit 24h
        _emit 0Ah
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 20h
        _emit 50h
        _emit 24h
        _emit 0Ah
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 24h
        _emit 34h
        _emit 24h
        _emit 0Ah
        _emit 01h
        _emit 89h
        _emit 5Eh
        _emit 44h
        _emit 89h
        _emit 5Eh
        _emit 48h
        _emit 89h
        _emit 5Ch
        _emit 24h
        _emit 14h
        _emit 89h
        _emit 5Eh
        _emit 4Ch
        _emit 6Ah
        _emit 0Ch
        _emit 0C6h
        _emit 44h
        _emit 24h
        _emit 18h
        _emit 01h
        _emit 89h
        _emit 5Eh
        _emit 7Ch
        _emit 0E8h
        _emit 39h
        _emit 0D0h
        _emit 63h
        _emit 00h
        _emit 89h
        _emit 00h
        _emit 89h
        _emit 40h
        _emit 04h
        _emit 89h
        _emit 46h
        _emit 7Ch
        _emit 89h
        _emit 5Eh
        _emit 28h
        _emit 89h
        _emit 5Eh
        _emit 2Ch
        _emit 89h
        _emit 5Eh
        _emit 30h
        _emit 89h
        _emit 5Eh
        _emit 34h
        _emit 53h
        _emit 89h
        _emit 5Eh
        _emit 38h
        _emit 89h
        _emit 5Eh
        _emit 3Ch
        _emit 89h
        _emit 5Eh
        _emit 40h
        _emit 8Bh
        _emit 4Eh
        _emit 44h
        _emit 8Bh
        _emit 46h
        _emit 48h
        _emit 8Dh
        _emit 54h
        _emit 24h
        _emit 28h
        _emit 52h
        _emit 51h
        _emit 50h
        _emit 50h
        _emit 0C6h
        _emit 44h
        _emit 24h
        _emit 2Ch
        _emit 02h
        _emit 0E8h
        _emit 3Eh
        _emit 38h
        _emit 0E2h
        _emit 0FFh
        _emit 89h
        _emit 46h
        _emit 48h
        _emit 89h
        _emit 5Eh
        _emit 6Ch
        _emit 89h
        _emit 5Eh
        _emit 68h
        _emit 89h
        _emit 5Eh
        _emit 50h
        _emit 89h
        _emit 5Eh
        _emit 54h
        _emit 89h
        _emit 5Eh
        _emit 58h
        _emit 89h
        _emit 5Eh
        _emit 5Ch
        _emit 89h
        _emit 5Eh
        _emit 60h
        _emit 89h
        _emit 5Eh
        _emit 64h
        _emit 8Bh
        _emit 46h
        _emit 08h
        _emit 83h
        _emit 0C4h
        _emit 18h
        _emit 68h
        _emit 0FFh
        _emit 0FFh
        _emit 0FFh
        _emit 3Fh
        _emit 50h
        _emit 8Bh
        _emit 0CEh
        _emit 89h
        _emit 5Eh
        _emit 70h
        _emit 89h
        _emit 5Eh
        _emit 74h
        _emit 88h
        _emit 9Eh
        _emit 80h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 5Eh
        _emit 78h
        _emit 0C7h
        _emit 86h
        _emit 84h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 80h
        _emit 3Fh
        _emit 0E8h
        _emit 56h
        _emit 42h
        _emit 0E2h
        _emit 0FFh
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 0Ch
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 5Bh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C2h
        _emit 08h
        _emit 00h
    }
}
