#pragma once

enum
{
	COLL_TYPE_ALL			= 0x01,
	COLL_TYPE_0				= 0x02,
	COLL_TYPE_1				= 0x04,
	COLL_TYPE_2				= 0x08,
	COLL_TYPE_3				= 0x10,
	COLL_TYPE_4				= 0x20,
	COLL_TYPE_5				= 0x40,
	COLL_TYPE_6				= 0x80,
	COLL_TYPE_PHYSICAL		= COLL_TYPE_0,
	COLL_TYPE_PROJECTILE	= COLL_TYPE_1,
	COLL_TYPE_VIS			= COLL_TYPE_2,
	COLL_TYPE_CAMERA		= COLL_TYPE_3,
	COLL_TYPE_VEHICLE		= COLL_TYPE_4,
	COLL_TYPE_MASK			= 0xFFFFFFFF,
};
