// ?d_007df1f0@@YAXXZ
// partial score=0.416 date=2026-09-16
// Function-sized candidate extracted from W3DShaderManager.cpp.
// Supporting BFME_SET_* and bfme* helpers remain in that TU; see docs/whales.md.
Int TerrainShader8Stage::set(Int pass)
{
	if (pass == 0)
	{
		//force WW3D2 system to set it's states so it won't later overwrite our custom settings.
		DX8Wrapper::Apply_Render_State_Changes();

		BFME_SET_SAMP(0, 1, D3DTADDRESS_CLAMP);
		BFME_SET_SAMP(0, 2, D3DTADDRESS_CLAMP);
		BFME_SET_SAMP(1, 1, D3DTADDRESS_CLAMP);
		BFME_SET_SAMP(1, 2, D3DTADDRESS_CLAMP);
		setTerrainTextureFilters(0);
		setTerrainTextureFilters(1);

		{
			BfmeHandleCX stage0_texture = bfmeGet(0);
			IDirect3DDevice8 *stage0_device = DX8Wrapper::_Get_D3D_Device8();
			bfmeSetTextureOnDevice(stage0_device, 0,
				((TextureBaseClass &)stage0_texture).Peek_D3D_Base_Texture());
		}
		{
			BfmeHandleCX stage1_texture = bfmeGet(1);
			IDirect3DDevice8 *stage1_device = DX8Wrapper::_Get_D3D_Device8();
			bfmeSetTextureOnDevice(stage1_device, 1,
				((TextureBaseClass &)stage1_texture).Peek_D3D_Base_Texture());
		}

		BFME_SET_TSS(0, D3DTSS_COLOROP, D3DTOP_MODULATE);
		BFME_SET_TSS(0, D3DTSS_TEXCOORDINDEX, 0);
		BFME_SET_TSS(0, D3DTSS_COLORARG1, D3DTA_TEXTURE);
		BFME_SET_TSS(0, D3DTSS_COLORARG2, D3DTA_DIFFUSE);
		BFME_SET_TSS(0, D3DTSS_ALPHAOP, D3DTOP_MODULATE);
		BFME_SET_TSS(0, D3DTSS_ALPHAARG1, D3DTA_TEXTURE);
		BFME_SET_TSS(0, D3DTSS_ALPHAARG2, D3DTA_DIFFUSE);

		BFME_SET_TSS(1, D3DTSS_COLOROP, D3DTOP_ADD);
		BFME_SET_TSS(1, D3DTSS_TEXCOORDINDEX, 1);
		BFME_SET_TSS(1, D3DTSS_COLORARG1, D3DTA_DIFFUSE | D3DTA_COMPLEMENT | D3DTA_ALPHAREPLICATE);
		BFME_SET_TSS(1, D3DTSS_COLORARG2, D3DTA_DIFFUSE);
		BFME_SET_TSS(1, D3DTSS_ALPHAOP, D3DTOP_ADD);
		BFME_SET_TSS(1, D3DTSS_ALPHAARG1, D3DTA_TFACTOR | D3DTA_COMPLEMENT);
		BFME_SET_TSS(1, D3DTSS_ALPHAARG2, D3DTA_TFACTOR);

		bfmeSetDX8Texture(2, NULL);
		BFME_SET_TSS(2, D3DTSS_COLOROP, D3DTOP_MODULATE);
		BFME_SET_TSS(2, D3DTSS_TEXCOORDINDEX, 2);
		BFME_SET_TSS(2, D3DTSS_COLORARG1, D3DTA_TEXTURE);
		BFME_SET_TSS(2, D3DTSS_COLORARG2, D3DTA_TEXTURE);
		BFME_SET_TSS(2, D3DTSS_ALPHAOP, D3DTOP_MODULATE);
		BFME_SET_TSS(2, D3DTSS_ALPHAARG1, D3DTA_TFACTOR);
		BFME_SET_TSS(2, D3DTSS_ALPHAARG2, D3DTA_TFACTOR);

		bfmeSetDX8Texture(3, NULL);
		BFME_SET_TSS(3, D3DTSS_COLOROP, D3DTOP_SELECTARG1);
		BFME_SET_TSS(3, D3DTSS_TEXCOORDINDEX, 3);
		BFME_SET_TSS(3, D3DTSS_COLORARG1, D3DTA_DIFFUSE | D3DTA_ALPHAREPLICATE);
		BFME_SET_TSS(3, D3DTSS_COLORARG2, D3DTA_DIFFUSE);
		BFME_SET_TSS(3, D3DTSS_ALPHAOP, D3DTOP_SELECTARG1);
		BFME_SET_TSS(3, D3DTSS_ALPHAARG1, D3DTA_TFACTOR);
		BFME_SET_TSS(3, D3DTSS_ALPHAARG2, D3DTA_TFACTOR);

		bfmeSetDX8Texture(4, NULL);
		BFME_SET_TSS(4, D3DTSS_COLOROP, D3DTOP_MODULATE);
		BFME_SET_TSS(4, D3DTSS_TEXCOORDINDEX, 4);
		BFME_SET_TSS(4, D3DTSS_COLORARG1, D3DTA_CURRENT);
		BFME_SET_TSS(4, D3DTSS_COLORARG2, D3DTA_DIFFUSE);
		BFME_SET_TSS(4, D3DTSS_ALPHAOP, D3DTOP_MODULATE);
		BFME_SET_TSS(4, D3DTSS_ALPHAARG1, D3DTA_CURRENT);
		BFME_SET_TSS(4, D3DTSS_ALPHAARG2, D3DTA_DIFFUSE);

		bfmeSetDX8Texture(5, NULL);
		BFME_SET_TSS(5, D3DTSS_COLOROP, D3DTOP_ADD);
		BFME_SET_TSS(5, D3DTSS_TEXCOORDINDEX, 5);
		BFME_SET_TSS(5, D3DTSS_COLORARG1, D3DTA_DIFFUSE);
		BFME_SET_TSS(5, D3DTSS_COLORARG2, D3DTA_DIFFUSE);
		BFME_SET_TSS(5, D3DTSS_ALPHAOP, D3DTOP_ADD);
		BFME_SET_TSS(5, D3DTSS_ALPHAARG1, D3DTA_TFACTOR | D3DTA_COMPLEMENT);
		BFME_SET_TSS(5, D3DTSS_ALPHAARG2, D3DTA_TFACTOR);

		bfmeSetDX8Texture(6, NULL);
		BFME_SET_TSS(6, D3DTSS_COLOROP, D3DTOP_MODULATE);
		BFME_SET_TSS(6, D3DTSS_TEXCOORDINDEX, 6);
		BFME_SET_TSS(6, D3DTSS_COLORARG1, D3DTA_TFACTOR);
		BFME_SET_TSS(6, D3DTSS_COLORARG2, D3DTA_TFACTOR);
		BFME_SET_TSS(6, D3DTSS_ALPHAOP, D3DTOP_MODULATE);
		BFME_SET_TSS(6, D3DTSS_ALPHAARG1, D3DTA_TFACTOR);
		BFME_SET_TSS(6, D3DTSS_ALPHAARG2, D3DTA_TFACTOR);

		bfmeSetDX8Texture(7, NULL);
		BFME_SET_TSS(7, D3DTSS_COLOROP, D3DTOP_SELECTARG1);
		BFME_SET_TSS(7, D3DTSS_TEXCOORDINDEX, 7);
		BFME_SET_TSS(7, D3DTSS_COLORARG1, D3DTA_TFACTOR);
		BFME_SET_TSS(7, D3DTSS_COLORARG2, D3DTA_TFACTOR);
		BFME_SET_TSS(7, D3DTSS_ALPHAOP, D3DTOP_SELECTARG1);
		BFME_SET_TSS(7, D3DTSS_ALPHAARG1, D3DTA_TFACTOR);
		BFME_SET_TSS(7, D3DTSS_ALPHAARG2, D3DTA_TFACTOR);
	}
	else
	{
		BFME_SET_TSS(2, D3DTSS_COLOROP, D3DTOP_DISABLE);
		BFME_SET_TSS(2, D3DTSS_ALPHAOP, D3DTOP_DISABLE);
		BFME_SET_TSS(3, D3DTSS_COLOROP, D3DTOP_DISABLE);
		BFME_SET_TSS(3, D3DTSS_ALPHAOP, D3DTOP_DISABLE);
		DX8Wrapper::Invalidate_Cached_Render_States();

		terrainShader2Stage.set(2);
	}
	return TRUE;
}
