// cl: /DNDEBUG /MD /EHsc

class Thing;
class ModuleData;

class ArrowStormUpdate
{
public:
    ArrowStormUpdate(Thing*, const ModuleData*);
};

__declspec(naked) ArrowStormUpdate::ArrowStormUpdate(Thing*, const ModuleData*)
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 26h
        _emit 0EEh
        _emit 00h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 8Bh
        _emit 44h
        _emit 24h
        _emit 18h
        _emit 53h
        _emit 56h
        _emit 57h
        _emit 8Bh
        _emit 0F1h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 20h
        _emit 50h
        _emit 51h
        _emit 8Bh
        _emit 0CEh
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 14h
        _emit 0E8h
        _emit 52h
        _emit 0BDh
        _emit 0DBh
        _emit 0FFh
        _emit 33h
        _emit 0DBh
        _emit 0C7h
        _emit 06h
        _emit 0C0h
        _emit 37h
        _emit 0Bh
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 0Ch
        _emit 0F8h
        _emit 36h
        _emit 0Bh
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 10h
        _emit 0E8h
        _emit 36h
        _emit 0Bh
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 20h
        _emit 0BCh
        _emit 36h
        _emit 0Bh
        _emit 01h
        _emit 6Ah
        _emit 0Ch
        _emit 89h
        _emit 5Ch
        _emit 24h
        _emit 1Ch
        _emit 89h
        _emit 9Eh
        _emit 0E8h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 0E8h
        _emit 02h
        _emit 6Eh
        _emit 5Dh
        _emit 00h
        _emit 89h
        _emit 00h
        _emit 89h
        _emit 40h
        _emit 04h
        _emit 83h
        _emit 0C4h
        _emit 04h
        _emit 89h
        _emit 86h
        _emit 0E8h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 8Bh
        _emit 38h
        _emit 3Bh
        _emit 0F8h
        _emit 0C6h
        _emit 44h
        _emit 24h
        _emit 18h
        _emit 01h
        _emit 74h
        _emit 19h
        _emit 8Bh
        _emit 0C7h
        _emit 8Bh
        _emit 3Fh
        _emit 6Ah
        _emit 0Ch
        _emit 50h
        _emit 0E8h
        _emit 8Dh
        _emit 6Eh
        _emit 5Dh
        _emit 00h
        _emit 8Bh
        _emit 86h
        _emit 0E8h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 08h
        _emit 3Bh
        _emit 0F8h
        _emit 75h
        _emit 0E7h
        _emit 8Bh
        _emit 86h
        _emit 0E8h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 10h
        _emit 89h
        _emit 00h
        _emit 8Bh
        _emit 86h
        _emit 0E8h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 40h
        _emit 04h
        _emit 89h
        _emit 9Eh
        _emit 0ECh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 9Eh
        _emit 0F0h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 89h
        _emit 9Eh
        _emit 0F4h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 88h
        _emit 9Eh
        _emit 0F8h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 5Fh
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 5Bh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C2h
        _emit 08h
        _emit 00h
    }
}
