// cl: /DNDEBUG /MD /EHsc

class LargeGroupAudioUpdateModuleData
{
public:
    LargeGroupAudioUpdateModuleData();
};

__declspec(naked) LargeGroupAudioUpdateModuleData::LargeGroupAudioUpdateModuleData()
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 03h
        _emit 1Eh
        _emit 01h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0ECh
        _emit 10h
        _emit 56h
        _emit 8Bh
        _emit 0F1h
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 08h
        _emit 8Dh
        _emit 4Eh
        _emit 08h
        _emit 0C7h
        _emit 44h
        _emit 24h
        _emit 1Ch
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 0C7h
        _emit 06h
        _emit 60h
        _emit 0FAh
        _emit 0Bh
        _emit 01h
        _emit 0E8h
        _emit 29h
        _emit 76h
        _emit 0D8h
        _emit 0FFh
        _emit 0DDh
        _emit 05h
        _emit 50h
        _emit 0FAh
        _emit 0Bh
        _emit 01h
        _emit 83h
        _emit 0ECh
        _emit 08h
        _emit 0DDh
        _emit 1Ch
        _emit 24h
        _emit 0C6h
        _emit 44h
        _emit 24h
        _emit 24h
        _emit 01h
        _emit 0FFh
        _emit 15h
        _emit 94h
        _emit 93h
        _emit 35h
        _emit 01h
        _emit 83h
        _emit 0C4h
        _emit 08h
        _emit 0E8h
        _emit 0F4h
        _emit 0FBh
        _emit 75h
        _emit 00h
        _emit 89h
        _emit 46h
        _emit 14h
        _emit 8Dh
        _emit 44h
        _emit 24h
        _emit 04h
        _emit 50h
        _emit 8Dh
        _emit 4Ch
        _emit 24h
        _emit 10h
        _emit 51h
        _emit 0B9h
        _emit 0A0h
        _emit 0FFh
        _emit 2Eh
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 18h
        _emit 01h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 66h
        _emit 0C7h
        _emit 46h
        _emit 1Ch
        _emit 01h
        _emit 00h
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 0Ch
        _emit 0E8h
        _emit 16h
        _emit 45h
        _emit 0DAh
        _emit 0FFh
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 14h
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 1Ch
        _emit 0C3h
    }
}
